/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jni;

public class BinaryMapPrimitivesTile extends MapTiledData {
  private long swigCPtr;
  private boolean swigCMemOwnDerived;

  protected BinaryMapPrimitivesTile(long cPtr, boolean cMemoryOwn) {
    super(OsmAndCoreJNI.BinaryMapPrimitivesTile_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BinaryMapPrimitivesTile obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        OsmAndCoreJNI.delete_BinaryMapPrimitivesTile(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public BinaryMapDataTile getDataTile() {
    long cPtr = OsmAndCoreJNI.BinaryMapPrimitivesTile_dataTile_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BinaryMapDataTile(cPtr, true);
  }

  public Primitiviser.PrimitivisedArea getPrimitivisedArea() {
    long cPtr = OsmAndCoreJNI.BinaryMapPrimitivesTile_primitivisedArea_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Primitiviser.PrimitivisedArea(cPtr, true);
  }

  public void releaseConsumableContent() {
    OsmAndCoreJNI.BinaryMapPrimitivesTile_releaseConsumableContent(swigCPtr, this);
  }

}
