/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jni;

public class BinaryMapRasterBitmapTileProvider_Software extends BinaryMapRasterBitmapTileProvider {
  private long swigCPtr;
  private boolean swigCMemOwnDerived;

  protected BinaryMapRasterBitmapTileProvider_Software(long cPtr, boolean cMemoryOwn) {
    super(OsmAndCoreJNI.BinaryMapRasterBitmapTileProvider_Software_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BinaryMapRasterBitmapTileProvider_Software obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        OsmAndCoreJNI.delete_BinaryMapRasterBitmapTileProvider_Software(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public BinaryMapRasterBitmapTileProvider_Software(BinaryMapPrimitivesProvider primitivesProvider) {
    this(OsmAndCoreJNI.new_BinaryMapRasterBitmapTileProvider_Software(BinaryMapPrimitivesProvider.getCPtr(primitivesProvider), primitivesProvider), true);
  }

}
