/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jni;

public class BinaryMapStaticSymbolsTile extends TiledMapSymbolsData {
  private long swigCPtr;
  private boolean swigCMemOwnDerived;

  protected BinaryMapStaticSymbolsTile(long cPtr, boolean cMemoryOwn) {
    super(OsmAndCoreJNI.BinaryMapStaticSymbolsTile_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BinaryMapStaticSymbolsTile obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        OsmAndCoreJNI.delete_BinaryMapStaticSymbolsTile(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public BinaryMapPrimitivesTile getDataTile() {
    long cPtr = OsmAndCoreJNI.BinaryMapStaticSymbolsTile_dataTile_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BinaryMapPrimitivesTile(cPtr, true);
  }

}
