/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jni;

public class DoublePtr {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected DoublePtr(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DoublePtr obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OsmAndCoreJNI.delete_DoublePtr(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DoublePtr() {
    this(OsmAndCoreJNI.new_DoublePtr(), true);
  }

  public void assign(double value) {
    OsmAndCoreJNI.DoublePtr_assign(swigCPtr, this, value);
  }

  public double value() {
    return OsmAndCoreJNI.DoublePtr_value(swigCPtr, this);
  }

  public SWIGTYPE_p_double cast() {
    long cPtr = OsmAndCoreJNI.DoublePtr_cast(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public static DoublePtr frompointer(SWIGTYPE_p_double t) {
    long cPtr = OsmAndCoreJNI.DoublePtr_frompointer(SWIGTYPE_p_double.getCPtr(t));
    return (cPtr == 0) ? null : new DoublePtr(cPtr, false);
  }

}
