/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jni;

public class IMapDataProvider {
  private long swigCPtr;
  private boolean swigCMemOwn;

  protected IMapDataProvider(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IMapDataProvider obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OsmAndCoreJNI.delete_IMapDataProvider(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public IMapDataProvider.DataType getDataType() {
    return IMapDataProvider.DataType.swigToEnum(OsmAndCoreJNI.IMapDataProvider_dataType_get(swigCPtr, this));
  }

  public enum DataType {
    Unknown(OsmAndCoreJNI.IMapDataProvider_DataType_Unknown_get()),
    BinaryMapDataTile,
    BinaryMapPrimitivesTile,
    RasterBitmapTile,
    ElevationDataTile,
    SymbolsTile,
    Symbols;

    public final int swigValue() {
      return swigValue;
    }

    public static DataType swigToEnum(int swigValue) {
      DataType[] swigValues = DataType.class.getEnumConstants();
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (DataType swigEnum : swigValues)
        if (swigEnum.swigValue == swigValue)
          return swigEnum;
      throw new IllegalArgumentException("No enum " + DataType.class + " with value " + swigValue);
    }

    @SuppressWarnings("unused")
    private DataType() {
      this.swigValue = SwigNext.next++;
    }

    @SuppressWarnings("unused")
    private DataType(int swigValue) {
      this.swigValue = swigValue;
      SwigNext.next = swigValue+1;
    }

    @SuppressWarnings("unused")
    private DataType(DataType swigEnum) {
      this.swigValue = swigEnum.swigValue;
      SwigNext.next = this.swigValue+1;
    }

    private final int swigValue;

    private static class SwigNext {
      private static int next = 0;
    }
  }

}
