/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jni;

public class IntPtr {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IntPtr(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IntPtr obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OsmAndCoreJNI.delete_IntPtr(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public IntPtr() {
    this(OsmAndCoreJNI.new_IntPtr(), true);
  }

  public void assign(int value) {
    OsmAndCoreJNI.IntPtr_assign(swigCPtr, this, value);
  }

  public int value() {
    return OsmAndCoreJNI.IntPtr_value(swigCPtr, this);
  }

  public SWIGTYPE_p_int cast() {
    long cPtr = OsmAndCoreJNI.IntPtr_cast(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public static IntPtr frompointer(SWIGTYPE_p_int t) {
    long cPtr = OsmAndCoreJNI.IntPtr_frompointer(SWIGTYPE_p_int.getCPtr(t));
    return (cPtr == 0) ? null : new IntPtr(cPtr, false);
  }

}
