/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jni;

public class ObfFile {
  private long swigCPtr;
  private boolean swigCMemOwn;

  protected ObfFile(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ObfFile obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OsmAndCoreJNI.delete_ObfFile(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ObfFile(String filePath) {
    this(OsmAndCoreJNI.new_ObfFile__SWIG_0(filePath), true);
  }

  public ObfFile(String filePath, java.math.BigInteger fileSize) {
    this(OsmAndCoreJNI.new_ObfFile__SWIG_1(filePath, fileSize), true);
  }

  public String getFilePath() {
    return OsmAndCoreJNI.ObfFile_filePath_get(swigCPtr, this);
  }

  public java.math.BigInteger getFileSize() {
    return OsmAndCoreJNI.ObfFile_fileSize_get(swigCPtr, this);
  }

  public ObfInfo getObfInfo() {
    long cPtr = OsmAndCoreJNI.ObfFile_obfInfo_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ObfInfo(cPtr, true);
  }

}
