/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jni;

public class ObfInfo {
  private long swigCPtr;
  private boolean swigCMemOwn;

  protected ObfInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ObfInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OsmAndCoreJNI.delete_ObfInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int getVersion() {
    return OsmAndCoreJNI.ObfInfo_version_get(swigCPtr, this);
  }

  public java.math.BigInteger getCreationTimestamp() {
    return OsmAndCoreJNI.ObfInfo_creationTimestamp_get(swigCPtr, this);
  }

  public boolean getIsBasemap() {
    return OsmAndCoreJNI.ObfInfo_isBasemap_get(swigCPtr, this);
  }

  public SWIGTYPE_p_QListT_std__shared_ptrT_OsmAnd__ObfMapSectionInfo_t_t getMapSections() {
    return new SWIGTYPE_p_QListT_std__shared_ptrT_OsmAnd__ObfMapSectionInfo_t_t(OsmAndCoreJNI.ObfInfo_mapSections_get(swigCPtr, this), false);
  }

  public SWIGTYPE_p_QListT_std__shared_ptrT_OsmAnd__ObfAddressSectionInfo_t_t getAddressSections() {
    return new SWIGTYPE_p_QListT_std__shared_ptrT_OsmAnd__ObfAddressSectionInfo_t_t(OsmAndCoreJNI.ObfInfo_addressSections_get(swigCPtr, this), false);
  }

  public SWIGTYPE_p_QListT_std__shared_ptrT_OsmAnd__ObfRoutingSectionInfo_t_t getRoutingSections() {
    return new SWIGTYPE_p_QListT_std__shared_ptrT_OsmAnd__ObfRoutingSectionInfo_t_t(OsmAndCoreJNI.ObfInfo_routingSections_get(swigCPtr, this), false);
  }

  public SWIGTYPE_p_QListT_std__shared_ptrT_OsmAnd__ObfPoiSectionInfo_t_t getPoiSections() {
    return new SWIGTYPE_p_QListT_std__shared_ptrT_OsmAnd__ObfPoiSectionInfo_t_t(OsmAndCoreJNI.ObfInfo_poiSections_get(swigCPtr, this), false);
  }

  public SWIGTYPE_p_QListT_std__shared_ptrT_OsmAnd__ObfTransportSectionInfo_t_t getTransportSections() {
    return new SWIGTYPE_p_QListT_std__shared_ptrT_OsmAnd__ObfTransportSectionInfo_t_t(OsmAndCoreJNI.ObfInfo_transportSections_get(swigCPtr, this), false);
  }

}
