/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jni;

public class ObfsCollection extends IObfsCollection {
  private long swigCPtr;
  private boolean swigCMemOwnDerived;

  protected ObfsCollection(long cPtr, boolean cMemoryOwn) {
    super(OsmAndCoreJNI.ObfsCollection_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ObfsCollection obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        OsmAndCoreJNI.delete_ObfsCollection(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ObfsCollection() {
    this(OsmAndCoreJNI.new_ObfsCollection(), true);
  }

  public int addDirectory(SWIGTYPE_p_QDir dir, boolean recursive) {
    return OsmAndCoreJNI.ObfsCollection_addDirectory__SWIG_0(swigCPtr, this, SWIGTYPE_p_QDir.getCPtr(dir), recursive);
  }

  public int addDirectory(SWIGTYPE_p_QDir dir) {
    return OsmAndCoreJNI.ObfsCollection_addDirectory__SWIG_1(swigCPtr, this, SWIGTYPE_p_QDir.getCPtr(dir));
  }

  public int addDirectory(String dirPath, boolean recursive) {
    return OsmAndCoreJNI.ObfsCollection_addDirectory__SWIG_2(swigCPtr, this, dirPath, recursive);
  }

  public int addDirectory(String dirPath) {
    return OsmAndCoreJNI.ObfsCollection_addDirectory__SWIG_3(swigCPtr, this, dirPath);
  }

  public int addFile(SWIGTYPE_p_QFileInfo fileInfo) {
    return OsmAndCoreJNI.ObfsCollection_addFile__SWIG_0(swigCPtr, this, SWIGTYPE_p_QFileInfo.getCPtr(fileInfo));
  }

  public int addFile(String filePath) {
    return OsmAndCoreJNI.ObfsCollection_addFile__SWIG_1(swigCPtr, this, filePath);
  }

  public boolean remove(int entryId) {
    return OsmAndCoreJNI.ObfsCollection_remove(swigCPtr, this, entryId);
  }

  public SWIGTYPE_p_QListT_std__shared_ptrT_ObfFile_const_t_t getObfFiles() {
    return new SWIGTYPE_p_QListT_std__shared_ptrT_ObfFile_const_t_t(OsmAndCoreJNI.ObfsCollection_getObfFiles(swigCPtr, this), true);
  }

  public ObfDataInterface obtainDataInterface() {
    long cPtr = OsmAndCoreJNI.ObfsCollection_obtainDataInterface(swigCPtr, this);
    return (cPtr == 0) ? null : new ObfDataInterface(cPtr, true);
  }

}
