/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jni;

public class QStringList {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected QStringList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(QStringList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OsmAndCoreJNI.delete_QStringList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public QStringList() {
    this(OsmAndCoreJNI.new_QStringList(), true);
  }

  public long size() {
    return OsmAndCoreJNI.QStringList_size(swigCPtr, this);
  }

  public void reserve(long n) {
    OsmAndCoreJNI.QStringList_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return OsmAndCoreJNI.QStringList_isEmpty(swigCPtr, this);
  }

  public void clear() {
    OsmAndCoreJNI.QStringList_clear(swigCPtr, this);
  }

  public void add(String x) {
    OsmAndCoreJNI.QStringList_add(swigCPtr, this, x);
  }

  public String get(int i) {
    return OsmAndCoreJNI.QStringList_get(swigCPtr, this, i);
  }

  public void set(int i, String val) {
    OsmAndCoreJNI.QStringList_set(swigCPtr, this, i, val);
  }

}
