/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jni;

public enum Quadrant {
  NE(OsmAndCoreJNI.Quadrant_NE_get()),
  SE,
  SW,
  NW;

  public final int swigValue() {
    return swigValue;
  }

  public static Quadrant swigToEnum(int swigValue) {
    Quadrant[] swigValues = Quadrant.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (Quadrant swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + Quadrant.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private Quadrant() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private Quadrant(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private Quadrant(Quadrant swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

