/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jni;

public class SWIGTYPE_p_QDir {
  private long swigCPtr;

  protected SWIGTYPE_p_QDir(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_QDir() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_QDir obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

