/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jni;

public class TiledMapSymbolsData extends MapTiledData {
  private long swigCPtr;
  private boolean swigCMemOwnDerived;

  protected TiledMapSymbolsData(long cPtr, boolean cMemoryOwn) {
    super(OsmAndCoreJNI.TiledMapSymbolsData_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TiledMapSymbolsData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        OsmAndCoreJNI.delete_TiledMapSymbolsData(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public TiledMapSymbolsData(SWIGTYPE_p_QListT_std__shared_ptrT_OsmAnd__MapSymbolsGroup_t_t symbolsGroups, TileId tileId, ZoomLevel zoom) {
    this(OsmAndCoreJNI.new_TiledMapSymbolsData(SWIGTYPE_p_QListT_std__shared_ptrT_OsmAnd__MapSymbolsGroup_t_t.getCPtr(symbolsGroups), TileId.getCPtr(tileId), tileId, zoom.swigValue()), true);
  }

  public void setSymbolsGroups(SWIGTYPE_p_QListT_std__shared_ptrT_OsmAnd__MapSymbolsGroup_t_t value) {
    OsmAndCoreJNI.TiledMapSymbolsData_symbolsGroups_set(swigCPtr, this, SWIGTYPE_p_QListT_std__shared_ptrT_OsmAnd__MapSymbolsGroup_t_t.getCPtr(value));
  }

  public SWIGTYPE_p_QListT_std__shared_ptrT_OsmAnd__MapSymbolsGroup_t_t getSymbolsGroups() {
    long cPtr = OsmAndCoreJNI.TiledMapSymbolsData_symbolsGroups_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_QListT_std__shared_ptrT_OsmAnd__MapSymbolsGroup_t_t(cPtr, false);
  }

  public void releaseConsumableContent() {
    OsmAndCoreJNI.TiledMapSymbolsData_releaseConsumableContent(swigCPtr, this);
  }

}
