/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jni;

public class UIntPtr {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected UIntPtr(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UIntPtr obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OsmAndCoreJNI.delete_UIntPtr(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public UIntPtr() {
    this(OsmAndCoreJNI.new_UIntPtr(), true);
  }

  public void assign(long value) {
    OsmAndCoreJNI.UIntPtr_assign(swigCPtr, this, value);
  }

  public long value() {
    return OsmAndCoreJNI.UIntPtr_value(swigCPtr, this);
  }

  public SWIGTYPE_p_unsigned_int cast() {
    long cPtr = OsmAndCoreJNI.UIntPtr_cast(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
  }

  public static UIntPtr frompointer(SWIGTYPE_p_unsigned_int t) {
    long cPtr = OsmAndCoreJNI.UIntPtr_frompointer(SWIGTYPE_p_unsigned_int.getCPtr(t));
    return (cPtr == 0) ? null : new UIntPtr(cPtr, false);
  }

}
