package net.osmand.plus;

public enum AppInitEvents {
	FAVORITES_INITIALIZED,
	NATIVE_INITIALIZED,
	NATIVE_OPEN_GL_INITIALIZED,
	TASK_CHANGED,
	MAPS_INITIALIZED,
	POI_TYPES_INITIALIZED,
	POI_FILTERS_INITIALIZED,
	ASSETS_COPIED,
	INIT_RENDERERS,
	INDEX_REGION_BOUNDARIES,
	SAVE_GPX_TRACKS,
	LOAD_GPX_TRACKS,
	ROUTING_CONFIG_INITIALIZED
}