package net.osmand.plus.settings.backend.backup;

public enum SettingsItemType {
	GLOBAL,
	PROFILE,
	PLUGIN,
	DATA,
	FILE,
	RESOURCES,
	QUICK_ACTIONS,
	POI_UI_FILTERS,
	MAP_SOURCES,
	AVOID_ROADS,
	SUGGESTED_DOWNLOADS,
	DOWNLOADS,
	MARKERS,
	FAVORITES,
	TRACKS,
	AUDIO_VIDEO_NOTES,
	OSM_CHANGES
}