package net.osmand.plus.myplaces.tracks.filters

import androidx.annotation.StringRes
import net.osmand.plus.R
import net.osmand.plus.myplaces.tracks.filters.NonDbTrackParam.VISIBLE_ON_MAP
import net.osmand.plus.myplaces.tracks.filters.NonDbTrackParam.WITH_WAYPOINTS
import net.osmand.gpx.GpxParameter
import java.util.Collections

enum class FilterType(
	@StringRes val nameResId: Int,
	val filterDisplayType: FilterDisplayType,
	val propertyList: List<GpxParameter>,
	val measureUnitType: MeasureUnitType,
	val defaultParams: List<Any>?,
	val updateOnOtherFiltersChangeNeeded: Boolean,
	val additionalData: Any? = null) {

	NAME(
		R.string.shared_string_name,
		FilterDisplayType.TEXT,
		Collections.singletonList(GpxParameter.FILE_NAME),
		MeasureUnitType.NONE,
		null,
		false),
	DURATION(
		R.string.duration,
		FilterDisplayType.RANGE,
		Collections.singletonList(GpxParameter.TIME_SPAN),
		MeasureUnitType.TIME_DURATION,
		listOf(0L, TrackFiltersConstants.DEFAULT_MAX_VALUE.toLong()),
		false),
	TIME_IN_MOTION(
		R.string.moving_time,
		FilterDisplayType.RANGE,
		Collections.singletonList(GpxParameter.TIME_MOVING),
		MeasureUnitType.TIME_DURATION,
		listOf(0L, TrackFiltersConstants.DEFAULT_MAX_VALUE.toLong()),
		false),
	LENGTH(
		R.string.routing_attr_length_name,
		FilterDisplayType.RANGE,
		Collections.singletonList(GpxParameter.TOTAL_DISTANCE),
		MeasureUnitType.DISTANCE,
		listOf(0.0, TrackFiltersConstants.LENGTH_MAX_VALUE.toDouble()),
		false),
	AVERAGE_SPEED(
		R.string.average_speed,
		FilterDisplayType.RANGE,
		Collections.singletonList(GpxParameter.AVG_SPEED),
		MeasureUnitType.SPEED,
		listOf(0.0, TrackFiltersConstants.SPEED_MAX_VALUE.toDouble()),
		false),
	AVERAGE_SENSOR_SPEED(
		R.string.avg_sensor_speed,
		FilterDisplayType.RANGE,
		Collections.singletonList(GpxParameter.AVG_SENSOR_SPEED),
		MeasureUnitType.SPEED,
		listOf(0.0, TrackFiltersConstants.SPEED_MAX_VALUE.toDouble()),
		false),
	MAX_SENSOR_SPEED(
		R.string.max_sensor_speed,
		FilterDisplayType.RANGE,
		Collections.singletonList(GpxParameter.MAX_SENSOR_SPEED),
		MeasureUnitType.SPEED,
		listOf(0.0, TrackFiltersConstants.SPEED_MAX_VALUE.toDouble()),
		false),
	AVERAGE_SENSOR_HEART_RATE(
		R.string.avg_sensor_heartrate,
		FilterDisplayType.RANGE,
		Collections.singletonList(GpxParameter.AVG_SENSOR_HEART_RATE),
		MeasureUnitType.BPM,
		listOf(0.0, TrackFiltersConstants.HEART_RATE_MAX_VALUE.toDouble()),
		false),
	MAX_SENSOR_HEART_RATE(
		R.string.max_sensor_heartrate,
		FilterDisplayType.RANGE,
		Collections.singletonList(GpxParameter.MAX_SENSOR_HEART_RATE),
		MeasureUnitType.BPM,
		listOf(0, TrackFiltersConstants.HEART_RATE_MAX_VALUE),
		false),
	AVERAGE_SENSOR_CADENCE(
		R.string.avg_sensor_cadence,
		FilterDisplayType.RANGE,
		Collections.singletonList(GpxParameter.AVG_SENSOR_CADENCE),
		MeasureUnitType.ROTATIONS,
		listOf(0.0, TrackFiltersConstants.DEFAULT_MAX_VALUE.toDouble()),
		false),
	MAX_SENSOR_CADENCE(
		R.string.max_sensor_cadence,
		FilterDisplayType.RANGE,
		Collections.singletonList(GpxParameter.MAX_SENSOR_CADENCE),
		MeasureUnitType.ROTATIONS,
		listOf(0.0, TrackFiltersConstants.DEFAULT_MAX_VALUE.toDouble()),
		false),
	AVERAGE_SENSOR_BICYCLE_POWER(
		R.string.avg_sensor_bycicle_power,
		FilterDisplayType.RANGE,
		Collections.singletonList(GpxParameter.AVG_SENSOR_POWER),
		MeasureUnitType.POWER,
		listOf(0.0, TrackFiltersConstants.DEFAULT_MAX_VALUE.toDouble()),
		false),
	MAX_SENSOR_BICYCLE_POWER(
		R.string.max_sensor_bycicle_power,
		FilterDisplayType.RANGE,
		Collections.singletonList(GpxParameter.MAX_SENSOR_POWER),
		MeasureUnitType.POWER,
		listOf(0, TrackFiltersConstants.DEFAULT_MAX_VALUE.toInt()),
		false),
	AVERAGE_SENSOR_TEMPERATURE(
		R.string.avg_sensor_temperature,
		FilterDisplayType.RANGE,
		Collections.singletonList(GpxParameter.AVG_SENSOR_TEMPERATURE),
		MeasureUnitType.TEMPERATURE,
		listOf(0.0, TrackFiltersConstants.TEMPERATURE_MAX_VALUE.toDouble()),
		false),
	MAX_SENSOR_TEMPERATURE(
		R.string.max_sensor_temperature,
		FilterDisplayType.RANGE,
		Collections.singletonList(GpxParameter.MAX_SENSOR_TEMPERATURE),
		MeasureUnitType.TEMPERATURE,
		listOf(0, TrackFiltersConstants.TEMPERATURE_MAX_VALUE),
		false),
	MAX_SPEED(
		R.string.max_speed,
		FilterDisplayType.RANGE,
		Collections.singletonList(GpxParameter.MAX_SPEED),
		MeasureUnitType.SPEED,
		listOf(0.0, TrackFiltersConstants.SPEED_MAX_VALUE.toDouble()),
		false),
	UPHILL(
		R.string.shared_string_uphill,
		FilterDisplayType.RANGE,
		Collections.singletonList(GpxParameter.DIFF_ELEVATION_UP),
		MeasureUnitType.ALTITUDE,
		listOf(0.0, TrackFiltersConstants.ALTITUDE_MAX_VALUE.toDouble()),
		false),
	DOWNHILL(
		R.string.shared_string_downhill,
		FilterDisplayType.RANGE,
		Collections.singletonList(GpxParameter.DIFF_ELEVATION_DOWN),
		MeasureUnitType.ALTITUDE,
		listOf(0.0, TrackFiltersConstants.ALTITUDE_MAX_VALUE.toDouble()),
		false),
	AVERAGE_ALTITUDE(
		R.string.average_altitude,
		FilterDisplayType.RANGE,
		Collections.singletonList(GpxParameter.AVG_ELEVATION),
		MeasureUnitType.ALTITUDE,
		listOf(0.0, TrackFiltersConstants.ALTITUDE_MAX_VALUE.toDouble()),
		false),
	MAX_ALTITUDE(
		R.string.max_altitude,
		FilterDisplayType.RANGE,
		Collections.singletonList(GpxParameter.MAX_ELEVATION),
		MeasureUnitType.ALTITUDE,
		listOf(0.0, TrackFiltersConstants.ALTITUDE_MAX_VALUE.toDouble()),
		false),
	DATE_CREATION(
		R.string.date_of_creation,
		FilterDisplayType.DATE_RANGE,
		Collections.singletonList(GpxParameter.FILE_CREATION_TIME),
		MeasureUnitType.NONE,
		null,
		false),
	FOLDER(
		R.string.folder,
		FilterDisplayType.SINGLE_FIELD_LIST,
		Collections.singletonList(GpxParameter.FILE_DIR),
		MeasureUnitType.NONE,
		null,
		true,
		FolderSingleFieldTrackFilterParams()),
	CITY(
		R.string.nearest_cities,
		FilterDisplayType.SINGLE_FIELD_LIST,
		Collections.singletonList(GpxParameter.NEAREST_CITY_NAME),
		MeasureUnitType.NONE,
		null,
		false,
		SingleFieldTrackFilterParams()),
	COLOR(
		R.string.shared_string_color,
		FilterDisplayType.SINGLE_FIELD_LIST,
		Collections.singletonList(GpxParameter.COLOR),
		MeasureUnitType.NONE,
		null,
		false,
		ColorSingleFieldTrackFilterParams()),
	WIDTH(
		R.string.shared_string_width,
		FilterDisplayType.SINGLE_FIELD_LIST,
		Collections.singletonList(GpxParameter.WIDTH),
		MeasureUnitType.NONE,
		null,
		false,
		WidthSingleFieldTrackFilterParams()),
	OTHER(
		R.string.shared_string_other,
		FilterDisplayType.OTHER,
		Collections.emptyList(),
		MeasureUnitType.NONE,
		null,
		false,
		listOf(VISIBLE_ON_MAP, WITH_WAYPOINTS));
}