package net.osmand.plus.onlinerouting;

public enum EngineParameter {
	KEY,
	VEHICLE_KEY,
	CUSTOM_NAME,
	NAME_INDEX,
	CUSTOM_URL,
	APPROXIMATION_ROUTING_PROFILE,
	APPROXIMATION_DERIVED_PROFILE,
	NETWORK_APPROXIMATE_ROUTE,
	USE_EXTERNAL_TIMESTAMPS,
	USE_ROUTING_FALLBACK,
	API_KEY
}
