package net.osmand.plus;

public interface OsmAndConstants {

	int UI_HANDLER_MAP_VIEW = 3000;
	int UI_HANDLER_MAP_CONTROLS = 4000;
	int UI_HANDLER_LOCATION_SERVICE = 5000;
	int UI_HANDLER_PROGRESS = 6000;
	int UI_HANDLER_SEARCH = 7000;
	int UI_HANDLER_GPS_FILTER = 8000;
	int UI_HANDLER_WEATHER_WIDGET = 9000;
}