package net.osmand.plus.routing;

import static net.osmand.router.RouteExporter.OSMAND_ROUTER_V2;

import androidx.annotation.NonNull;

import net.osmand.gpx.GPXFile;
import net.osmand.gpx.GPXUtilities.WptPt;
import net.osmand.Location;
import net.osmand.PlatformUtil;
import net.osmand.data.LatLon;
import net.osmand.data.LocationPoint;
import net.osmand.data.WptLocationPoint;
import net.osmand.plus.OsmandApplication;
import net.osmand.plus.R;
import net.osmand.plus.settings.backend.OsmandSettings;
import net.osmand.router.RouteSegmentResult;
import net.osmand.util.Algorithms;
import net.osmand.util.MapUtils;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public class GPXRouteParams {

	public static final String OSMAND_ROUTER = "OsmAndRouter";

	protected List<LocationPoint> wpt;
	protected List<RouteSegmentResult> route;
	protected List<RouteDirectionInfo> directions;
	protected List<Location> points = new ArrayList<>();
	protected List<Location> segmentEndpoints = new ArrayList<>();
	protected List<WptPt> routePoints = new ArrayList<>();
	protected boolean reverse;
	protected boolean passWholeRoute;
	protected boolean calculateOsmAndRoute;
	protected boolean connectPointsStraightly;
	protected boolean useIntermediatePointsRTE;
	protected boolean calculateOsmAndRouteParts;
	protected boolean calculatedRouteTimeSpeed;

	boolean addMissingTurns = true;

	public List<Location> getPoints() {
		return points;
	}

	public List<RouteSegmentResult> getRoute() {
		return route;
	}

	public List<LocationPoint> getWpt() {
		return wpt;
	}

	public LatLon getLastPoint() {
		if (!points.isEmpty()) {
			Location l = points.get(points.size() - 1);
			return new LatLon(l.getLatitude(), l.getLongitude());
		}
		return null;
	}

	public GPXRouteParams prepareGPXFile(@NonNull GPXRouteParamsBuilder builder) {
		GPXFile file = builder.file;
		reverse = builder.reverse;
		passWholeRoute = builder.passWholeRoute;
		calculateOsmAndRouteParts = builder.calculateOsmAndRouteParts;
		calculatedRouteTimeSpeed = builder.calculatedRouteTimeSpeed;
		connectPointsStraightly = builder.connectPointsStraightly;
		useIntermediatePointsRTE = builder.useIntermediateRtePoints;
		builder.calculateOsmAndRoute = false; // Disabled temporary builder.calculateOsmAndRoute;
		if (!file.isPointsEmpty()) {
			wpt = new ArrayList<>(file.getPoints().size());
			for (WptPt w : file.getPoints()) {
				wpt.add(new WptLocationPoint(w));
			}
		}
		int selectedRoute = builder.getSelectedRoute();
		int selectedSegment = builder.getSelectedSegment();
		if (OSMAND_ROUTER_V2.equals(file.author)) {
			route = RouteProvider.parseOsmAndGPXRoute(points, file, segmentEndpoints, selectedSegment, builder.leftSide);
			if (selectedSegment == -1) {
				routePoints = file.getRoutePoints();
			} else {
				routePoints = file.getRoutePoints(selectedSegment);
			}
			if (reverse) {
				Collections.reverse(points);
				Collections.reverse(routePoints);
				Collections.reverse(segmentEndpoints);
			}
			addMissingTurns = route != null && route.isEmpty();
		} else if (file.isCloudmadeRouteFile() || OSMAND_ROUTER.equals(file.author)) {
			directions = RouteProvider.parseOsmAndGPXRoute(points, file, segmentEndpoints,
					OSMAND_ROUTER.equals(file.author), builder.leftSide, 10, selectedSegment);
			if (OSMAND_ROUTER.equals(file.author) && file.hasRtePt()) {
				// For files generated by OSMAND_ROUTER use directions contained unaltered
				addMissingTurns = false;
			}
			if (reverse) {
				// clear directions all turns should be recalculated
				directions = null;
				Collections.reverse(points);
				Collections.reverse(segmentEndpoints);
				addMissingTurns = true;
			}
		} else {
			if (useIntermediatePointsRTE) {
				List<WptPt> rtePoints = selectedRoute == -1 ? file.getRoutePoints() : file.getRoutePoints(selectedRoute);
				for (WptPt pt : rtePoints) {
					points.add(RouteProvider.createLocation(pt));
				}
			} else {
				RouteProvider.collectSegmentPointsFromGpx(file, points, segmentEndpoints, selectedSegment);
			}
			if (reverse) {
				Collections.reverse(points);
				Collections.reverse(segmentEndpoints);
			}
		}
		return this;
	}

	public static class GPXRouteParamsBuilder {

		private static final org.apache.commons.logging.Log log = PlatformUtil.getLog(GPXRouteParamsBuilder.class);

		boolean calculateOsmAndRoute;
		// parameters
		private final GPXFile file;
		private final boolean leftSide;
		private boolean reverse;
		private boolean passWholeRoute;
		private boolean calculateOsmAndRouteParts;
		private boolean calculatedRouteTimeSpeed;
		private boolean connectPointsStraightly;
		private boolean useIntermediateRtePoints;
		private int selectedSegment = -1;
		private int selectedRoute = -1;

		public GPXRouteParamsBuilder(@NonNull GPXFile file, @NonNull OsmandSettings settings) {
			this.file = file;
			this.leftSide = settings.DRIVING_REGION.get().leftHandDriving;
			updateIntermediateRtePoints();
		}

		private void updateIntermediateRtePoints() {
			if (selectedRoute == -1) {
				useIntermediateRtePoints = file.hasRtePt() && !file.hasTrkPt();
			} else {
				useIntermediateRtePoints = file.routes.size() > selectedRoute && file.routes.get(selectedRoute).points.isEmpty();
			}
		}

		public boolean isReverse() {
			return reverse;
		}

		public boolean isCalculateOsmAndRouteParts() {
			return calculateOsmAndRouteParts;
		}

		public void setCalculateOsmAndRouteParts(boolean calculateOsmAndRouteParts) {
			this.calculateOsmAndRouteParts = calculateOsmAndRouteParts;
		}

		public boolean isCalculateOsmAndRoute() {
			return calculateOsmAndRoute;
		}

		public void setCalculateOsmAndRoute(boolean calculateOsmAndRoute) {
			this.calculateOsmAndRoute = calculateOsmAndRoute;
		}

		public boolean hasCalculatedRouteTimeSpeed() {
			return calculatedRouteTimeSpeed;
		}

		public void setCalculatedRouteTimeSpeed(boolean calculatedRouteTimeSpeed) {
			this.calculatedRouteTimeSpeed = calculatedRouteTimeSpeed;
		}

		public boolean shouldConnectPointsStraightly() {
			return connectPointsStraightly;
		}

		public void setConnectPointStraightly(boolean connectPointStraightly) {
			this.connectPointsStraightly = connectPointStraightly;
		}

		public int getSelectedSegment() {
			return selectedSegment;
		}

		public void setSelectedSegment(int selectedSegment) {
			this.selectedSegment = selectedSegment;
		}

		public int getSelectedRoute() {
			return selectedRoute;
		}

		public void setSelectedRoute(int selectedRoute) {
			this.selectedRoute = selectedRoute;
			updateIntermediateRtePoints();
		}

		public boolean shouldUseIntermediateRtePoints() {
			return useIntermediateRtePoints;
		}

		public void setPassWholeRoute(boolean passWholeRoute) {
			this.passWholeRoute = passWholeRoute;
		}

		public boolean isPassWholeRoute() {
			return passWholeRoute;
		}

		public GPXRouteParams build(OsmandApplication app) {
			return build(app, null);
		}

		public GPXRouteParams build(OsmandApplication app, LatLon targetPoint) {
			GPXRouteParams gpxRouteParams = new GPXRouteParams();
			try {
				gpxRouteParams.prepareGPXFile(this);
				if (targetPoint != null && !targetPoint.equals(gpxRouteParams.getLastPoint())) {
					cutGpxTail(gpxRouteParams, targetPoint);
				}
			} catch (RuntimeException e) {
				log.error(e.getMessage(), e);
				app.showShortToastMessage(app.getString(R.string.gpx_parse_error) + " " + e.getMessage());
			}
			return gpxRouteParams;
		}

		private void cutGpxTail(GPXRouteParams gpxRouteParams, LatLon targetPoint) {
			int lastIdx = 0;
			double minDist = Float.MAX_VALUE;
			List<Location> locations = gpxRouteParams.points;
			for (int i = 0; i < locations.size(); i++) {
				Location point = locations.get(i);
				double distance = MapUtils.getDistance(point.getLatitude(), point.getLongitude(),
						targetPoint.getLatitude(), targetPoint.getLongitude());
				if (distance < minDist) {
					minDist = distance;
					lastIdx = i;
				}
			}
			if (!Algorithms.isEmpty(gpxRouteParams.segmentEndpoints)) {
				List<Location> removedLocations = gpxRouteParams.points.subList(lastIdx, gpxRouteParams.points.size());
				List<Location> endpoints = gpxRouteParams.segmentEndpoints;
				int firstRemovedIdx = 0;
				for (; firstRemovedIdx < endpoints.size(); firstRemovedIdx++) {
					Location point = endpoints.get(firstRemovedIdx);
					if (removedLocations.contains(point)) {
						break;
					}
				}
				if (firstRemovedIdx < endpoints.size()) {
					endpoints.subList(firstRemovedIdx, endpoints.size()).clear();
				}
			}
			if (!Algorithms.isEmpty(gpxRouteParams.routePoints)) {
				List<WptPt> routePoints = gpxRouteParams.routePoints;
				int firstRemovedIdx = 1;
				for (; firstRemovedIdx < routePoints.size(); firstRemovedIdx++) {
					WptPt routePoint = routePoints.get(firstRemovedIdx);
					if (routePoint.getTrkPtIndex() > lastIdx) {
						break;
					}
				}
				if (firstRemovedIdx < routePoints.size()) {
					routePoints.subList(firstRemovedIdx, routePoints.size()).clear();
				}
			}
			gpxRouteParams.points.subList(lastIdx, gpxRouteParams.points.size()).clear();
			if (!Algorithms.isEmpty(gpxRouteParams.route)) {
				gpxRouteParams.route.clear();
			}
		}

		public void setReverse(boolean reverse) {
			this.reverse = reverse;
		}

		public GPXFile getFile() {
			return file;
		}

		public List<Location> getPoints(OsmandApplication app) {
			GPXRouteParams copy = build(app);
			return copy.getPoints();
		}

		@NonNull
		@Override
		public String toString() {
			return "GPXRouteParamsBuilder{" +
					"calculateOsmAndRoute=" + calculateOsmAndRoute +
					", file=" + file.path +
					", leftSide=" + leftSide +
					", reverse=" + reverse +
					", passWholeRoute=" + passWholeRoute +
					", calculateOsmAndRouteParts=" + calculateOsmAndRouteParts +
					", calculatedRouteTimeSpeed=" + calculatedRouteTimeSpeed +
					", connectPointsStraightly=" + connectPointsStraightly +
					", useIntermediateRtePoints=" + useIntermediateRtePoints +
					", selectedSegment=" + selectedSegment +
					", selectedRoute=" + selectedRoute +
					'}';
		}
	}
}