package net.osmand.router;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import net.osmand.data.TransportRoute;
import net.osmand.data.TransportStop;
import net.osmand.osm.edit.Way;
import net.osmand.router.TransportRoutePlanner.TransportRouteResultSegment;
import net.osmand.router.TransportRoutePlanner.TransportRouteSegment;

/**
 * Public transport ferries generated by the map creator from route=ferry ways without a route relation.
 * Their stop flags are stored as route tags with indexes of the route stops.
 */
public class TransportFerryHelper {

	private static final String FERRY = "ferry";
	// stops generated at ferry way ends (not present in OSM): "0,5"
	public static final String SYNTHETIC_STOPS_TAG = "osmand:synthetic_ferry_stops";
	// synthetic stops in the water joining ferry ways: only a change to the next ferry way at the same stop
	public static final String JUNCTION_STOPS_TAG = "osmand:ferry_junction_stops";
	// non-ferry route goes over a ferry before these stops: "stop index:ferry interval:ferry duration" (seconds, 0 - unknown)
	public static final String CROSSINGS_TAG = "osmand:ferry_crossings";

	public static void addStopTag(Map<String, String> tags, String tag, int stop, Object value) {
		tags.merge(tag, value == null ? String.valueOf(stop) : stop + ":" + value, (a, b) -> a + "," + b);
	}

	public static boolean isFerry(TransportRoute route) {
		return FERRY.equals(route.getType());
	}

	public static boolean isSyntheticStop(TransportRoute route, int stop) {
		return getStopValue(route, SYNTHETIC_STOPS_TAG, stop) != null;
	}

	public static boolean isJunctionStop(TransportRoute route, int stop) {
		return getStopValue(route, JUNCTION_STOPS_TAG, stop) != null;
	}

	// synthetic stop from the stops tree is marked in the stop lists of its routes
	public static boolean isSyntheticStop(TransportStop stop) {
		if (stop.getRoutes() != null) {
			for (TransportRoute route : stop.getRoutes()) {
				List<TransportStop> stops = route.getForwardStops();
				for (int i = 0; i < stops.size(); i++) {
					if (stops.get(i).getId().longValue() == stop.getId().longValue()) {
						return isSyntheticStop(route, i);
					}
				}
			}
		}
		return false;
	}

	public static List<TransportStop> getVisibleStops(TransportRoute route) {
		List<TransportStop> stops = new ArrayList<>();
		for (int i = 0; i < route.getForwardStops().size(); i++) {
			if (!isSyntheticStop(route, i)) {
				stops.add(route.getForwardStops().get(i));
			}
		}
		return stops;
	}

	// ferry crossing time from its duration tag, 0 if unknown (then it's calculated with the ferry speed)
	public static int getDuration(TransportRoute route) {
		return isFerry(route) ? TransportRoute.parseDurationTagToSeconds(route.getTags().get(TransportRoute.DURATION_KEY),
				route.getDistance()) : 0;
	}

	// waiting for a ferry on the way to the stop, same as boarding the ferry itself
	public static double getCrossingWaitTime(TransportRoutingConfiguration cfg, TransportRoute route, int stop) {
		String[] crossing = getCrossing(route, stop);
		return crossing == null ? 0 : cfg.getWaitTime(FERRY, Integer.parseInt(crossing[0]));
	}

	public static int getCrossingDuration(TransportRoute route, int stop) {
		String[] crossing = getCrossing(route, stop);
		return crossing == null ? 0 : Integer.parseInt(crossing[1]);
	}

	private static String[] getCrossing(TransportRoute route, int stop) {
		String value = getStopValue(route, CROSSINGS_TAG, stop);
		return value == null ? null : value.split(":"); // interval, duration
	}

	// TODO #17773 temporary: show only routes with ferries
	static boolean usesFerry(TransportRouteSegment segment) {
		return isFerry(segment.road) || segment.parentRoute != null && usesFerry(segment.parentRoute);
	}

	// ferry ways joined by a junction stop in the water are one ferry ride
	public static void mergeJunctionSegments(List<TransportRouteResultSegment> segments) {
		for (int i = segments.size() - 1; i > 0; i--) {
			TransportRouteResultSegment s = segments.get(i - 1);
			if (isJunctionStop(s.route, s.end)) {
				segments.set(i - 1, merge(s, segments.remove(i)));
			}
		}
	}

	private static TransportRouteResultSegment merge(TransportRouteResultSegment s, TransportRouteResultSegment next) {
		List<TransportStop> stops = new ArrayList<>(s.getTravelStops().subList(0, s.end - s.start));
		stops.addAll(next.getTravelStops().subList(1, next.end - next.start + 1));
		List<Way> ways = new ArrayList<>();
		for (Way w : s.route.getForwardWays()) {
			ways.add(new Way(w, w.getId()));
		}
		for (Way w : next.route.getForwardWays()) {
			ways.add(new Way(w, w.getId()));
		}
		TransportRouteResultSegment res = new TransportRouteResultSegment();
		res.route = new TransportRoute(s.route, stops, ways);
		res.start = 0;
		res.end = stops.size() - 1;
		res.walkDist = s.walkDist;
		res.walkTime = s.walkTime;
		res.depTime = s.depTime;
		res.travelTime = s.travelTime + next.travelTime;
		res.travelDistApproximate = s.travelDistApproximate + next.travelDistApproximate;
		return res;
	}

	private static String getStopValue(TransportRoute route, String tag, int stop) {
		String value = route.getTags().get(tag);
		if (value != null) {
			for (String v : value.split(",")) {
				int sep = v.indexOf(':');
				if (Integer.parseInt(sep < 0 ? v : v.substring(0, sep)) == stop) {
					return sep < 0 ? "" : v.substring(sep + 1);
				}
			}
		}
		return null;
	}
}
