package net.osmand.plus.specialPhrases;

/*
 * DO NOT EDIT THIS CLASS
 *  
 * This class is generated by the generate.sh script, and the data comes from 
 * http://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases
 * 
 * If you want to edit the data, please edit it on the wiki and run the script again
 * If you want to edit the formatting, please edit the generate.sh script and run it again
 */


import java.util.HashMap;
import java.util.Map;

/**
 * class that contains the special phrases and is used to create the map
 * 
 * Data CC-BY-SA http://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases
 * 
 * @author sander
 * 
 */
 public class SpecialPhrasesJA {
     public static Map<String,String> createMap(){
        HashMap<String,String> sp = new HashMap<String,String>(); // maybe search an optimal load factor and initial capacity
        sp.put( "aeroway_aerodrome", "空港");
        sp.put( "amenity_bank", "銀行");
        sp.put( "amenity_car_rental", "レンタカー");
        sp.put( "amenity_car_wash", "洗車");
        sp.put( "amenity_casino", "賭場");
        sp.put( "amenity_college", "大学");
        sp.put( "amenity_dentist", "歯科医");
        sp.put( "amenity_embassy", "大使館");
        sp.put( "amenity_hotel", "ホテル");
        sp.put( "amenity_kindergarten", "幼稚園");
        sp.put( "amenity_library", "図書館");
        sp.put( "amenity_pub", "パブ（立ち吞み屋）");
        sp.put( "amenity_sauna", "サウナ");
        sp.put( "amenity_school", "学校");
        sp.put( "amenity_shop", "店舗");
        sp.put( "amenity_taxi", "タクシー乗り場");
        sp.put( "amenity_university", "大学");
        sp.put( "amenity_wifi", "WiFiアクセスポイント");
        sp.put( "highway_bus_stop", "バス停");
        sp.put( "highway_steps", "階段");
        sp.put( "place_city", "市");
        sp.put( "tourism_theme_park", "テーマパーク");
        sp.put( "tourism_valley", "谷");
        sp.put( "tourism_zoo", "動物園");
        return sp;
    }
}
