package net.osmand.plus.specialPhrases;

/*
 * DO NOT EDIT THIS CLASS
 *  
 * This class is generated by the generate.sh script, and the data comes from 
 * http://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases
 * 
 * If you want to edit the data, please edit it on the wiki and run the script again
 * If you want to edit the formatting, please edit the generate.sh script and run it again
 */


import java.util.HashMap;
import java.util.Map;

/**
 * class that contains the special phrases and is used to create the map
 * 
 * Data CC-BY-SA http://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases
 * 
 * @author sander
 * 
 */
 public class SpecialPhrasesPT {
     public static Map<String,String> createMap(){
        HashMap<String,String> sp = new HashMap<String,String>(); // maybe search an optimal load factor and initial capacity
        sp.put( "aerodrome", "Aeroporto");
        sp.put( "amenity", "Caixa");
        sp.put( "amenity", "Caixa");
        sp.put( "Multibanco", "Caixa");
        sp.put( "atm", "Multibanco");
        sp.put( "atm", "Multicaixa");
        sp.put( "amenity", "Agência");
        sp.put( "bank", "Banco");
        sp.put( "bar", "Bar");
        sp.put( "bureau_de_change", "Câmbio");
        sp.put( "bureau_de_change", "Cambista");
        sp.put( "Autocarros", "Estação");
        sp.put( "Camionagem", "Estação");
        sp.put( "Ônibus", "Estação");
        sp.put( "amenity", "Estação");
        sp.put( "amenity", "Terminal");
        sp.put( "pub", "Bar");
        sp.put( "school", "Escola");
        sp.put( "amenity", "Câmara");
        sp.put( "townhall", "Município");
        sp.put( "university", "Universidade");
        sp.put( "Autocarro", "Paragem");
        sp.put( "Autocarros", "Paragem");
        sp.put( "ônibus", "Parada");
        sp.put( "ônibus", "Ponto");
        sp.put( "parada", "Ponto");
        sp.put( "road", "Estrada");
        sp.put( "castle", "Castelo");
        sp.put( "ruins", "Ruína");
        sp.put( "beach", "Praia");
        sp.put( "island", "Ilha");
        sp.put( "islet", "Ilhéu");
        sp.put( "river", "Rio");
        sp.put( "place", "Código");
        sp.put( "funicular", "Funicular");
        sp.put( "Nível", "Passagem");
        sp.put( "Nível", "Passagens");
        sp.put( "station", "Estação");
        sp.put( "Comboio", "Estação");
        sp.put( "Comboios", "Estação");
        sp.put( "railway", "Estação");
        sp.put( "Metro", "Estação");
        sp.put( "Metrô", "Estação");
        sp.put( "Metropolitano", "Estação");
        sp.put( "Trem", "Estação");
        sp.put( "Trens", "Estação");
        sp.put( "museum", "Museu");
        return sp;
    }
}
