package net.osmand.plus.specialPhrases;

/*
 * DO NOT EDIT THIS CLASS
 *  
 * This class is generated by the generate.sh script, and the data comes from 
 * http://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases
 * 
 * If you want to edit the data, please edit it on the wiki and run the script again
 * If you want to edit the formatting, please edit the generate.sh script and run it again
 */


import java.util.HashMap;
import java.util.Map;

/**
 * class that contains the special phrases and is used to create the map
 * 
 * Data CC-BY-SA http://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases
 * 
 * @author sander
 * 
 */
 public class SpecialPhrasesCS {
     public static Map<String,String> createMap(){
        HashMap<String,String> sp = new HashMap<String,String>(); // maybe search an optimal load factor and initial capacity
        sp.put( "cinema", "Kino");
        sp.put( "parking", "Parkoviště");
        sp.put( "post_office", "Pošta");
        sp.put( "toilets", "Toalety");
        sp.put( "train_station", "Železniční stanice");
        sp.put( "bus_stop", "Autobusová zastávka");
        sp.put( "gate", "Brána");
        sp.put( "residential", "Ulice");
        sp.put( "secondary", "Silnice II. třídy");
        sp.put( "steps", "Schodiště");
        sp.put( "steps", "Schody");
        sp.put( "museum", "Muzeum");
        sp.put( "cemetery", "Hřbitov");
        sp.put( "construction", "Staveniště");
        sp.put( "vineyard", "Vinice");
        sp.put( "garden", "Zahrada");
        sp.put( "golf_course", "Golfové hřiště");
        sp.put( "ice_rink", "Kluziště");
        sp.put( "miniature_golf", "Minigolf");
        sp.put( "nature_reserve", "Přírodní rezervace");
        sp.put( "park", "Park");
        sp.put( "pitch", "Hřiště");
        sp.put( "stadium", "Stadion");
        sp.put( "swimming_pool", "Bazén");
        sp.put( "beach", "Pláž");
        sp.put( "glacier", "Ledovec");
        sp.put( "hill", "Kopec");
        sp.put( "island", "Ostrov");
        sp.put( "tree", "Strom");
        sp.put( "valley", "Údolí");
        sp.put( "aerodrome", "Letiště");
        sp.put( "city", "Velkoměsto");
        sp.put( "country", "Stát");
        sp.put( "farm", "Farma");
        sp.put( "hamlet", "Osada");
        sp.put( "house", "Dům");
        sp.put( "houses", "Budova");
        sp.put( "island", "Ostrov");
        sp.put( "islet", "Ostrůvek");
        sp.put( "locality", "Oblast");
        sp.put( "municipality", "Obecní úřad");
        sp.put( "postcode", "PSČ");
        sp.put( "region", "Kraj");
        sp.put( "sea", "Moře");
        sp.put( "state", "Stát");
        sp.put( "suburb", "Městská část");
        sp.put( "town", "Město");
        sp.put( "village", "Vesnice");
        sp.put( "halt", "Železniční zastávka");
        sp.put( "subway", "Stanice metra");
        sp.put( "hairdresser", "Kadeřnictví");
        sp.put( "alpine_hut", "Vysokohorská chata");
        sp.put( "attraction", "Turistická atrakce");
        sp.put( "camp_site", "Tábořiště, kemp");
        sp.put( "caravan_site", "Autokemping");
        sp.put( "chalet", "Velká chata");
        sp.put( "guest_house", "Penzion");
        sp.put( "hostel", "Hostel");
        sp.put( "hotel", "Hotel");
        sp.put( "information", "Turistické informace");
        sp.put( "lean_to", "Přístřešek");
        sp.put( "motel", "Motel");
        sp.put( "museum", "Muzeum");
        sp.put( "theme_park", "Zábavní park");
        sp.put( "valley", "Údolí");
        sp.put( "viewpoint", "Místo s dobrým výhledem");
        sp.put( "zoo", "Zoo");
        return sp;
    }
}
