package net.osmand.plus.specialPhrases;

/*
 * DO NOT EDIT THIS CLASS
 *  
 * This class is generated by the generate.sh script, and the data comes from 
 * http://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases
 * 
 * If you want to edit the data, please edit it on the wiki and run the script again
 * If you want to edit the formatting, please edit the generate.sh script and run it again
 */


import java.util.HashMap;
import java.util.Map;

/**
 * class that contains the special phrases and is used to create the map
 * 
 * Data CC-BY-SA http://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases
 * 
 * @author sander
 * 
 */
 public class SpecialPhrasesET {
     public static Map<String,String> createMap(){
        HashMap<String,String> sp = new HashMap<String,String>(); // maybe search an optimal load factor and initial capacity
        sp.put( "aeroway_aerodrome", "Lennujaam");
        sp.put( "amenity_atm", "Pangaautomaat");
        sp.put( "amenity_auditorium", "Auditoorium");
        sp.put( "amenity_bank", "Pank");
        sp.put( "amenity_bench", "Pink");
        sp.put( "amenity_bicycle_parking", "Jalgrattaparkla");
        sp.put( "amenity_bicycle_rental", "Jalgrattarent");
        sp.put( "amenity_bureau_de_change", "Rahavahetus");
        sp.put( "amenity_bus_station", "Bussijaam");
        sp.put( "amenity_cafe", "Kohvik");
        sp.put( "amenity_car_rental", "Autorent");
        sp.put( "amenity_car_wash", "Autopesu");
        sp.put( "amenity_casino", "Kasiino");
        sp.put( "amenity_cinema", "Kino");
        sp.put( "amenity_clinic", "Kliinik");
        sp.put( "amenity_club", "Klubi");
        sp.put( "amenity_courthouse", "Kohtuhoone");
        sp.put( "amenity_crematorium", "Krematoorium");
        sp.put( "amenity_dentist", "Hambaarst");
        sp.put( "amenity_drinking_water", "Joogivesi");
        sp.put( "amenity_driving_school", "Autokool");
        sp.put( "amenity_embassy", "Saatkond");
        sp.put( "amenity_fast_food", "Kiirtoit");
        sp.put( "amenity_fuel", "Kütus");
        sp.put( "amenity_grave_yard", "Surnuaed");
        sp.put( "amenity_hospital", "Haigla");
        sp.put( "amenity_hotel", "Hotell");
        sp.put( "amenity_ice_cream", "Jäätis");
        sp.put( "amenity_kindergarten", "Lasteaed");
        sp.put( "amenity_library", "Raamatukogu");
        sp.put( "amenity_market", "Turg");
        sp.put( "amenity_nightclub", "Ööklubi");
        sp.put( "amenity_pharmacy", "Apteek");
        sp.put( "amenity_police", "Politsei");
        sp.put( "amenity_post_box", "Postkast");
        sp.put( "amenity_post_office", "Postkontor");
        sp.put( "amenity_preschool", "Lasteaed");
        sp.put( "amenity_prison", "Vangla");
        sp.put( "amenity_reception_area", "Vastuvõtt");
        sp.put( "amenity_restaurant", "Restoran");
        sp.put( "amenity_retirement_home", "Vanadekodu");
        sp.put( "amenity_sauna", "Saun");
        sp.put( "amenity_school", "Kool");
        sp.put( "amenity_shop", "Kauplus");
        sp.put( "amenity_supermarket", "Supermarket");
        sp.put( "amenity_taxi", "Takso");
        sp.put( "amenity_theatre", "Teater");
        sp.put( "amenity_toilets", "WC");
        sp.put( "amenity_university", "Ülikool");
        sp.put( "amenity_waste_basket", "Prügikast");
        sp.put( "amenity_wifi", "WiFi");
        sp.put( "amenity_youth_centre", "Noortekeskus");
        sp.put( "amenity_youth_centre", "Noortekeskuss");
        sp.put( "building_chapel", "Kabel");
        sp.put( "building_church", "Kirik");
        sp.put( "building_hotel", "Hotell");
        sp.put( "building_school", "Koolihoone");
        sp.put( "building_shop", "Kauplus");
        sp.put( "building_stadium", "Staadion");
        sp.put( "building_tower", "Torn");
        sp.put( "building_train_station", "Raudteejaam");
        sp.put( "building_university", "Ülikoolihoone");
        sp.put( "building_&quot;yes&quot;", "Hoone");
        sp.put( "highway_bus_stop", "Bussipeatus");
        sp.put( "highway_cycleway", "Jalgrattatee");
        sp.put( "highway_footway", "Jalgrada");
        sp.put( "highway_pedestrian", "Jalakäijatele");
        sp.put( "historic_castle", "Kindlus");
        sp.put( "historic_church", "Kirik");
        sp.put( "historic_icon", "Ikoon");
        sp.put( "historic_manor", "Mõis");
        sp.put( "historic_museum", "Muuseum");
        sp.put( "historic_ruins", "Varemed");
        sp.put( "historic_tower", "Torn");
        sp.put( "landuse_cemetery", "Surnuaed");
        sp.put( "landuse_forest", "Mets");
        sp.put( "landuse_mountain", "Mägi");
        sp.put( "landuse_railway", "Raudtee");
        sp.put( "landuse_wetland", "Soo");
        sp.put( "leisure_garden", "Aed");
        sp.put( "leisure_golf_course", "Golfiväljak");
        sp.put( "leisure_ice_rink", "Uisuväli");
        sp.put( "leisure_miniature_golf", "Minigolf");
        sp.put( "leisure_park", "Park");
        sp.put( "leisure_playground", "Mänguväljak");
        sp.put( "leisure_sports_centre", "Spordikeskus");
        sp.put( "leisure_stadium", "Saadion");
        sp.put( "leisure_swimming_pool", "Ujula");
        sp.put( "leisure_water_park", "Veepark");
        sp.put( "natural_beach", "Rand");
        sp.put( "sissepääs_natural", "Koopa");
        sp.put( "natural_coastline", "Rannajoon");
        sp.put( "natural_crater", "Kraater");
        sp.put( "natural_fjord", "Fjord");
        sp.put( "natural_geyser", "Geiser");
        sp.put( "natural_hill", "Mägi");
        sp.put( "natural_island", "Saar");
        sp.put( "natural_mud", "Muda");
        sp.put( "natural_peak", "Mäetipp");
        sp.put( "natural_river", "Jõgi");
        sp.put( "natural_spring", "Allikas");
        sp.put( "natural_tree", "Puu");
        sp.put( "natural_volcano", "Vulkaan");
        sp.put( "natural_water", "Vesi");
        sp.put( "natural_wetlands", "Soo");
        sp.put( "place_city", "Linn");
        sp.put( "place_country", "Riik");
        sp.put( "place_county", "Maakond");
        sp.put( "place_house", "Maja");
        sp.put( "place_houses", "Majad");
        sp.put( "place_island", "Saar");
        sp.put( "place_islet", "Saareke");
        sp.put( "place_municipality", "Vald");
        sp.put( "place_postcode", "Sihtnumber");
        sp.put( "place_state", "Osariik");
        sp.put( "place_town", "Linn");
        sp.put( "place_village", "Küla");
        sp.put( "railway_station", "Raudteejaam");
        sp.put( "railway_tram", "Trammitee");
        sp.put( "railway_tram_stop", "Trammipeatus");
        sp.put( "shop_books", "Raamatupood");
        sp.put( "shop_car_repair", "Autoparandus");
        sp.put( "shop_carpet", "Vaibakauplus");
        sp.put( "shop_clothes", "Riidepood");
        sp.put( "shop_computer", "Arvutikauplus");
        sp.put( "shop_cosmetics", "Kosmeetikapood");
        sp.put( "shop_drugstore", "Apteek");
        sp.put( "puhastus_shop", "Keemiline");
        sp.put( "shop_fish", "Kalapood");
        sp.put( "shop_food", "Toidupood");
        sp.put( "shop_furniture", "Mööbel");
        sp.put( "shop_gallery", "Galerii");
        sp.put( "shop_hairdresser", "Juuksur");
        sp.put( "shop_insurance", "Kindlustus");
        sp.put( "shop_jewelry", "Juveelipood");
        sp.put( "shop_kiosk", "Kiosk");
        sp.put( "pood_shop", "Mobiiltelefonide");
        sp.put( "shop_music", "Muusikapood");
        sp.put( "shop_pet", "Lemmikloomapood");
        sp.put( "shop_shoes", "Kingapood");
        sp.put( "shop_sports", "Spordipood");
        sp.put( "shop_supermarket", "Supermarket");
        sp.put( "shop_toys", "Mänguasjapood");
        sp.put( "shop_travel_agency", "Reisiagentuur");
        sp.put( "tourism_attraction", "Turismiatraktsioon");
        sp.put( "tourism_camp_site", "Laagriplats");
        sp.put( "tourism_guest_house", "Külalistemaja");
        sp.put( "tourism_hotel", "Hotell");
        sp.put( "tourism_information", "Informatsioon");
        sp.put( "tourism_motel", "Motell");
        sp.put( "tourism_museum", "Muuseum");
        sp.put( "tourism_picnic_site", "Piknikuplats");
        sp.put( "tourism_theme_park", "Teemapark");
        sp.put( "tourism_zoo", "Loomaaed");
        return sp;
    }
}
