package net.osmand.plus.specialPhrases;

/*
 * DO NOT EDIT THIS CLASS
 *  
 * This class is generated by the generate.sh script, and the data comes from 
 * http://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases
 * 
 * If you want to edit the data, please edit it on the wiki and run the script again
 * If you want to edit the formatting, please edit the generate.sh script and run it again
 */


import java.util.HashMap;
import java.util.Map;

/**
 * class that contains the special phrases and is used to create the map
 * 
 * Data CC-BY-SA http://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases
 * 
 * @author sander
 * 
 */
 public class SpecialPhrasesPT {
     public static Map<String,String> createMap(){
        HashMap<String,String> sp = new HashMap<String,String>(); // maybe search an optimal load factor and initial capacity
        sp.put( "aeroway_aerodrome", "Aeroporto");
        sp.put( "Eletrônico_amenity", "Caixa");
        sp.put( "Multibanco_amenity", "Caixa");
        sp.put( "de_Multibanco", "Caixa");
        sp.put( "amenity_atm", "Multibanco");
        sp.put( "amenity_atm", "Multicaixa");
        sp.put( "Bancária_amenity", "Agência");
        sp.put( "amenity_bank", "Banco");
        sp.put( "amenity_bar", "Bar");
        sp.put( "amenity_bureau_de_change", "Câmbio");
        sp.put( "amenity_bureau_de_change", "Cambista");
        sp.put( "de_Autocarros", "Estação");
        sp.put( "de_Camionagem", "Estação");
        sp.put( "de_Ônibus", "Estação");
        sp.put( "Rodoviária_amenity", "Estação");
        sp.put( "Rodoviário_amenity", "Terminal");
        sp.put( "amenity_pub", "Bar");
        sp.put( "amenity_school", "Escola");
        sp.put( "Municipal_amenity", "Câmara");
        sp.put( "amenity_townhall", "Município");
        sp.put( "amenity_university", "Universidade");
        sp.put( "de_Autocarro", "Paragem");
        sp.put( "de_Autocarros", "Paragem");
        sp.put( "de_ônibus", "Parada");
        sp.put( "de_ônibus", "Ponto");
        sp.put( "de_parada", "Ponto");
        sp.put( "highway_road", "Estrada");
        sp.put( "historic_castle", "Castelo");
        sp.put( "historic_ruins", "Ruína");
        sp.put( "natural_beach", "Praia");
        sp.put( "natural_island", "Ilha");
        sp.put( "natural_islet", "Ilhéu");
        sp.put( "natural_river", "Rio");
        sp.put( "Postal_place", "Código");
        sp.put( "railway_funicular", "Funicular");
        sp.put( "de_Nível", "Passagem");
        sp.put( "de_Nível", "Passagens");
        sp.put( "railway_station", "Estação");
        sp.put( "de_Comboio", "Estação");
        sp.put( "de_Comboios", "Estação");
        sp.put( "Ferroviária_railway", "Estação");
        sp.put( "de_Metro", "Estação");
        sp.put( "de_Metrô", "Estação");
        sp.put( "de_Metropolitano", "Estação");
        sp.put( "de_Trem", "Estação");
        sp.put( "de_Trens", "Estação");
        sp.put( "tourism_museum", "Museu");
        return sp;
    }
}
