package net.osmand.plus.specialPhrases;

/*
 * DO NOT EDIT THIS CLASS
 *  
 * This class is generated by the generate.sh script, and the data comes from 
 * http://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases
 * 
 * If you want to edit the data, please edit it on the wiki and run the script again
 * If you want to edit the formatting, please edit the generate.sh script and run it again
 */


import java.util.HashMap;
import java.util.Map;

/**
 * class that contains the special phrases and is used to create the map
 * 
 * Data CC-BY-SA http://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases
 * 
 * @author sander
 * 
 */
 public class SpecialPhrasesIT {
     public static Map<String,String> createMap(){
        HashMap<String,String> sp = new HashMap<String,String>(); // maybe search an optimal load factor and initial capacity
        sp.put( "aeroway_aerodrome", "Aeroporto");
        sp.put( "amenity_atm", "Bancomat");
        sp.put( "amenity_bank", "Banca");
        sp.put( "amenity_bar", "Bar");
        sp.put( "amenity_bench", "Panchina");
        sp.put( "per_biciclette", "Parcheggio");
        sp.put( "biciclette_amenity", "Noleggio");
        sp.put( "biciclette_amenity", "Noleggi");
        sp.put( "amenity_brothel", "Bordello");
        sp.put( "amenity_bureau_de_change", "Cambiavalute");
        sp.put( "valute_amenity", "Cambia");
        sp.put( "amenity_cafe", "Caffè");
        sp.put( "amenity_car_rental", "Autonoleggio");
        sp.put( "amenity_car_wash", "Autolavaggio");
        sp.put( "amenity_casino", "Casinò");
        sp.put( "amenity_cinema", "Cinema");
        sp.put( "superiore_amenity", "Scuola");
        sp.put( "amenity_courthouse", "Tribunale");
        sp.put( "amenity_crematorium", "Crematorio");
        sp.put( "amenity_dentist", "Dentista");
        sp.put( "amenity_dormitory", "Dormitorio");
        sp.put( "guida_amenity", "Scuola");
        sp.put( "amenity_embassy", "Ambasciata");
        sp.put( "SOS_amenity", "Colonnina");
        sp.put( "food_amenity", "Fast");
        sp.put( "traghetto_amenity", "Terminal");
        sp.put( "antincendio_amenity", "Pompa");
        sp.put( "del_fuoco", "Vigili");
        sp.put( "amenity_fire_station", "Pompieri");
        sp.put( "di_rifornimento", "Stazione");
        sp.put( "amenity_grave_yard", "Cimitero");
        sp.put( "amenity_hospital", "Ospedale");
        sp.put( "amenity_hotel", "Hotel");
        sp.put( "amenity_hotel", "Albergo");
        sp.put( "di_caccia", "Postazione");
        sp.put( "amenity_ice_cream", "Gelateria");
        sp.put( "infantile_amenity", "Asilo");
        sp.put( "amenity_library", "Biblioteca");
        sp.put( "alpino_amenity", "Soccorso");
        sp.put( "nido_amenity", "Asilo");
        sp.put( "amenity_parking", "Parcheggio");
        sp.put( "amenity_pharmacy", "Farmacia");
        sp.put( "di_culto", "Luogo");
        sp.put( "amenity_police", "Polizia");
        sp.put( "postale_amenity", "Cassetta");
        sp.put( "delle_lettere", "Cassetta");
        sp.put( "postale_amenity", "Ufficio");
        sp.put( "amenity_prison", "Prigione");
        sp.put( "amenity_pub", "Pub");
        sp.put( "pubblico_amenity", "Edificio");
        sp.put( "amenity_restaurant", "Ristorante");
        sp.put( "amenity_sauna", "Sauna");
        sp.put( "amenity_school", "Scuola");
        sp.put( "amenity_shelter", "Pensilina/ricovero");
        sp.put( "amenity_supermarket", "Supermercato");
        sp.put( "amenity_taxi", "Taxi");
        sp.put( "pubblico_amenity", "Telefono");
        sp.put( "amenity_theatre", "Teatro");
        sp.put( "pubblico_amenity", "Gabinetto");
        sp.put( "amenity_townhall", "Municipio");
        sp.put( "amenity_university", "Università");
        sp.put( "automatico_amenity", "Distributore");
        sp.put( "amenity_veterinary", "Veterinario");
        sp.put( "di_accesso", "Punto");
        sp.put( "building_church", "Chiesa");
        sp.put( "building_dormitory", "Dormitorio");
        sp.put( "per_equitazione", "Percorso");
        sp.put( "guidato_highway", "Autobus");
        sp.put( "autobus_highway", "Fermata");
        sp.put( "(UK)_highway", "Byway");
        sp.put( "in_costruzione", "Strada");
        sp.put( "ciclabile_highway", "Percorso");
        sp.put( "SOS_highway", "Colonnina");
        sp.put( "pedonale_highway", "Percorso");
        sp.put( "highway_ford", "Guado");
        sp.put( "highway_gate", "Cancello");
        sp.put( "highway_motorway", "Autostrada/tangenziale");
        sp.put( "highway_motorway_junction", "Svincolo");
        sp.put( "pedonale_highway", "Percorso");
        sp.put( "primaria_highway", "Strada");
        sp.put( "primaria_highway", "Strada");
        sp.put( "residenziale_highway", "Strada");
        sp.put( "secondaria_highway", "Strada");
        sp.put( "secondaria_highway", "Strada");
        sp.put( "di_servizio", "Strada");
        sp.put( "di_servizio", "Stazione");
        sp.put( "highway_steps", "Scala");
        sp.put( "highway_stile", "Scaletta");
        sp.put( "terziaria_highway", "Strada");
        sp.put( "escursionistico_highway", "Percorso");
        sp.put( "non_classificata", "Strada");
        sp.put( "archeologico_historic", "Sito");
        sp.put( "historic_building", "Edificio");
        sp.put( "historic_castle", "Castello");
        sp.put( "historic_church", "Chiesa");
        sp.put( "historic_mine", "Miniera");
        sp.put( "historic_monument", "Monumento");
        sp.put( "historic_museum", "Museo");
        sp.put( "historic_ruins", "Rovine");
        sp.put( "historic_tower", "Torre");
        sp.put( "landuse_cemetery", "Cimitero");
        sp.put( "landuse_grass", "Prato");
        sp.put( "industriale_landuse", "Zona");
        sp.put( "residenziale_landuse", "Area");
        sp.put( "comune_(UK)", "Area");
        sp.put( "di_pesca", "Riserva");
        sp.put( "leisure_garden", "Giardino");
        sp.put( "da_golf", "Campo");
        sp.put( "di_ghiaccio", "Pista");
        sp.put( "turistico_leisure", "Porto");
        sp.put( "leisure_miniature_golf", "Minigolf");
        sp.put( "naturale_leisure", "Riserva");
        sp.put( "leisure_park", "Parco");
        sp.put( "sportivo_leisure", "Campo");
        sp.put( "giochi_leisure", "Parco");
        sp.put( "di_svago", "Area");
        sp.put( "di_alaggio", "Rampa");
        sp.put( "sportivo_leisure", "Centro");
        sp.put( "leisure_stadium", "Stadio");
        sp.put( "leisure_swimming_pool", "Piscina");
        sp.put( "da_corsa", "Pista");
        sp.put( "acquatico_leisure", "Parco");
        sp.put( "natural_bay", "Baia");
        sp.put( "natural_beach", "Spiaggia");
        sp.put( "natural_cape", "Capo");
        sp.put( "di_grotta/caverna", "Entrata");
        sp.put( "natural_channel", "Canale");
        sp.put( "natural_cliff", "Rupe");
        sp.put( "di_costa", "Linea");
        sp.put( "natural_crater", "Cratere");
        sp.put( "natural_feature", "Caratteristica");
        sp.put( "alpino_natural", "Prato");
        sp.put( "natural_fjord", "Fiordo");
        sp.put( "natural_geyser", "Geyser");
        sp.put( "natural_glacier", "Ghiacciaio");
        sp.put( "natural_heath", "Brughiera");
        sp.put( "natural_hill", "Collina");
        sp.put( "natural_island", "Isola");
        sp.put( "alluvionale_natural", "Palude");
        sp.put( "fangosa_(sabbie", "Zona");
        sp.put( "montuoso_natural", "Picco");
        sp.put( "natural_reef", "Scogliera");
        sp.put( "montuosa_natural", "Cresta");
        sp.put( "natural_river", "Fiume");
        sp.put( "natural_rock", "Roccia");
        sp.put( "natural_scree", "Ghiaione");
        sp.put( "natural_scrub", "Boscaglia");
        sp.put( "natural_shoal", "Secca");
        sp.put( "natural_spring", "Sorgente");
        sp.put( "natural_tree", "Albero");
        sp.put( "natural_valley", "Valle");
        sp.put( "natural_volcano", "Vulcano");
        sp.put( "umida_natural", "Zona");
        sp.put( "umida_natural", "Zona");
        sp.put( "natural_wood", "Bosco");
        sp.put( "place_city", "Città");
        sp.put( "place_country", "Nazione");
        sp.put( "place_country", "Nazioni");
        sp.put( "(in_Italia", "Contea");
        sp.put( "(in_Italia", "Contee");
        sp.put( "agricola_place", "Area");
        sp.put( "place_hamlet", "Borgo");
        sp.put( "place_house", "Casa");
        sp.put( "di_case", "Gruppo");
        sp.put( "place_island", "Isola");
        sp.put( "place_islet", "Isoletta");
        sp.put( "(luogo_con", "Località");
        sp.put( "place_municipality", "Comune");
        sp.put( "place_postcode", "CAP");
        sp.put( "place_region", "Provincia");
        sp.put( "place_sea", "Mare");
        sp.put( "place_state", "Regione");
        sp.put( "place_subdivision", "Suddivisione");
        sp.put( "place_suburb", "Quartiere");
        sp.put( "place_town", "Paese");
        sp.put( "place_village", "Frazione");
        sp.put( "shop_bakery", "Panetteria");
        sp.put( "shop_books", "Libreria");
        sp.put( "shop_butcher", "Macellaio");
        sp.put( "shop_car", "Concessionaria");
        sp.put( "shop_dry_cleaning", "Lavasecco");
        sp.put( "immobiliare_shop", "Agenzia");
        sp.put( "shop_florist", "Fioraio");
        sp.put( "shop_food", "Alimentari");
        sp.put( "shop_greengrocer", "Fruttivendolo");
        sp.put( "shop_grocery", "Fruttivendolo");
        sp.put( "shop_insurance", "Assicurazioni");
        sp.put( "shop_jewelry", "Gioielleria");
        sp.put( "shop_laundry", "Lavanderia");
        sp.put( "shop_optician", "Ottico");
        sp.put( "shop_supermarket", "Supermercato");
        sp.put( "di_viaggi", "Agenzia");
        sp.put( "viaggi_shop", "Agenzia");
        sp.put( "viaggio_shop", "Agenzia");
        sp.put( "alpino_tourism", "Rifugio");
        sp.put( "d'arte_tourism", "Opera");
        sp.put( "turistica_tourism", "Attrazione");
        sp.put( "and_Breakfast", "Bed");
        sp.put( "tourism_camp_site", "Campeggio");
        sp.put( "caravan_e", "Area");
        sp.put( "(chalet)_tourism", "Casetta");
        sp.put( "house_tourism", "Guest");
        sp.put( "tourism_hostel", "Ostello");
        sp.put( "tourism_hotel", "Hotel");
        sp.put( "tourism_information", "Informazioni");
        sp.put( "tourism_motel", "Motel");
        sp.put( "tourism_museum", "Museo");
        sp.put( "picnic_tourism", "Area");
        sp.put( "divertimenti_tourism", "Parco");
        sp.put( "panoramico_tourism", "Punto");
        sp.put( "tourism_zoo", "Zoo");
        sp.put( "amenity_fuel", "Benzinaio");
        return sp;
    }
}
