package net.osmand.plus.specialPhrases;

/*
 * DO NOT EDIT THIS CLASS
 *  
 * This class is generated by the generate.sh script, and the data comes from 
 * http://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases
 * 
 * If you want to edit the data, please edit it on the wiki and run the script again
 * If you want to edit the formatting, please edit the generate.sh script and run it again
 */


import java.util.HashMap;
import java.util.Map;

/**
 * class that contains the special phrases and is used to create the map
 * 
 * Data CC-BY-SA http://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases
 * 
 * @author sander
 * 
 */
 public class SpecialPhrasesCS {
     public static Map<String,String> createMap(){
        HashMap<String,String> sp = new HashMap<String,String>(); // maybe search an optimal load factor and initial capacity
        sp.put( "cinema", "Kino");
        sp.put( "parking", "Parkoviště");
        sp.put( "post_office", "Pošta");
        sp.put( "toilets", "Toalety");
        sp.put( "building", "Železniční");
        sp.put( "highway", "Autobusová");
        sp.put( "gate", "Brána");
        sp.put( "residential", "Ulice");
        sp.put( "třídy", "Silnice");
        sp.put( "steps", "Schodiště");
        sp.put( "steps", "Schody");
        sp.put( "museum", "Muzeum");
        sp.put( "cemetery", "Hřbitov");
        sp.put( "construction", "Staveniště");
        sp.put( "vineyard", "Vinice");
        sp.put( "garden", "Zahrada");
        sp.put( "leisure", "Golfové");
        sp.put( "ice_rink", "Kluziště");
        sp.put( "miniature_golf", "Minigolf");
        sp.put( "leisure", "Přírodní");
        sp.put( "park", "Park");
        sp.put( "pitch", "Hřiště");
        sp.put( "stadium", "Stadion");
        sp.put( "swimming_pool", "Bazén");
        sp.put( "beach", "Pláž");
        sp.put( "glacier", "Ledovec");
        sp.put( "hill", "Kopec");
        sp.put( "island", "Ostrov");
        sp.put( "tree", "Strom");
        sp.put( "valley", "Údolí");
        sp.put( "aerodrome", "Letiště");
        sp.put( "city", "Velkoměsto");
        sp.put( "country", "Stát");
        sp.put( "farm", "Farma");
        sp.put( "hamlet", "Osada");
        sp.put( "house", "Dům");
        sp.put( "houses", "Budova");
        sp.put( "island", "Ostrov");
        sp.put( "islet", "Ostrůvek");
        sp.put( "locality", "Oblast");
        sp.put( "place", "Obecní");
        sp.put( "postcode", "PSČ");
        sp.put( "region", "Kraj");
        sp.put( "sea", "Moře");
        sp.put( "state", "Stát");
        sp.put( "place", "Městská");
        sp.put( "town", "Město");
        sp.put( "village", "Vesnice");
        sp.put( "railway", "Železniční");
        sp.put( "railway", "Stanice");
        sp.put( "hairdresser", "Kadeřnictví");
        sp.put( "tourism", "Vysokohorská");
        sp.put( "tourism", "Turistická");
        sp.put( "tourism", "Tábořiště,");
        sp.put( "caravan_site", "Autokemping");
        sp.put( "tourism", "Velká");
        sp.put( "guest_house", "Penzion");
        sp.put( "hostel", "Hostel");
        sp.put( "hotel", "Hotel");
        sp.put( "tourism", "Turistické");
        sp.put( "lean_to", "Přístřešek");
        sp.put( "motel", "Motel");
        sp.put( "museum", "Muzeum");
        sp.put( "tourism", "Zábavní");
        sp.put( "valley", "Údolí");
        sp.put( "dobrým", "Místo");
        sp.put( "zoo", "Zoo");
        return sp;
    }
}
