package net.osmand.plus.specialPhrases;

/*
 * DO NOT EDIT THIS CLASS
 *  
 * This class is generated by the generate.sh script, and the data comes from 
 * http://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases
 * 
 * If you want to edit the data, please edit it on the wiki and run the script again
 * If you want to edit the formatting, please edit the generate.sh script and run it again
 */


import java.util.HashMap;
import java.util.Map;

/**
 * class that contains the special phrases and is used to create the map
 * 
 * Data CC-BY-SA http://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases
 * 
 * @author sander
 * 
 */
 public class SpecialPhrasesSV {
     public static Map<String,String> createMap(){
        HashMap<String,String> sp = new HashMap<String,String>(); // maybe search an optimal load factor and initial capacity
        sp.put( "aeroway_aerodrome", "Flygplats");
        sp.put( "amenity_atm", "Bankomat");
        sp.put( "amenity_bank", "Bank");
        sp.put( "amenity_bar", "Bar");
        sp.put( "amenity_bench", "Bänk");
        sp.put( "amenity_bicycle_parking", "Cykelparkering");
        sp.put( "amenity_bicycle_rental", "Cykeluthyrning");
        sp.put( "amenity_brothel", "Bordell");
        sp.put( "amenity_bureau_de_change", "Växlingskontor");
        sp.put( "amenity_bus_station", "Busstation");
        sp.put( "amenity_car_rental", "Biluthyrning");
        sp.put( "amenity_car_sharing", "Bilpool");
        sp.put( "amenity_car_wash", "Biltvätt");
        sp.put( "amenity_cinema", "Biograf");
        sp.put( "amenity_crematorium", "Krematorium");
        sp.put( "amenity_dentist", "Tandläkare");
        sp.put( "amenity_doctors", "Läkare");
        sp.put( "amenity_drinking_water", "Dricksvatten");
        sp.put( "amenity_driving_school", "Körskola");
        sp.put( "amenity_embassy", "Ambassad");
        sp.put( "amenity_emergency_phone", "Nödtelefon");
        sp.put( "amenity_emergency_phone", "Nödtelefons");
        sp.put( "amenity_fast_food", "Snabbmat");
        sp.put( "amenity_ferry_terminal", "Färjeterminal");
        sp.put( "amenity_fire_hydrant", "Brandpost");
        sp.put( "amenity_fire_station", "Brandstation");
        sp.put( "amenity_fountain", "Fontän");
        sp.put( "amenity_fuel", "Bränsle");
        sp.put( "amenity_grave_yard", "Begravningsplats");
        sp.put( "amenity_hospital", "Sjukhus");
        sp.put( "amenity_hotel", "Hotell");
        sp.put( "amenity_ice_cream", "Glass");
        sp.put( "amenity_kindergarten", "Dagis");
        sp.put( "amenity_library", "Bibliotek");
        sp.put( "amenity_market", "Torghandel");
        sp.put( "amenity_marketplace", "nMarknad");
        sp.put( "amenity_nightclub", "Nattklubb");
        sp.put( "amenity_nightclub", "Nattklubbs");
        sp.put( "amenity_office", "Kontor");
        sp.put( "amenity_parking", "Parkeringsplats");
        sp.put( "amenity_pharmacy", "Apotek");
        sp.put( "för_tillbedjan", "Plats");
        sp.put( "amenity_police", "Polis");
        sp.put( "amenity_post_office", "Postkontor");
        sp.put( "amenity_preschool", "Förskola");
        sp.put( "amenity_prison", "Fängelse");
        sp.put( "amenity_pub", "Pub");
        sp.put( "byggnad_amenity", "Offentlig");
        sp.put( "amenity_recycling", "Återvinningsstation");
        sp.put( "amenity_restaurant", "Restaurang");
        sp.put( "amenity_retirement_home", "Äldreboende");
        sp.put( "amenity_sauna", "Bastu");
        sp.put( "amenity_school", "Skola");
        sp.put( "amenity_shop", "Affär");
        sp.put( "amenity_taxi", "Taxi");
        sp.put( "amenity_theatre", "Teater");
        sp.put( "amenity_toilets", "Toaletter");
        sp.put( "amenity_vending_machine", "Varumaskin");
        sp.put( "amenity_veterinary", "Veterinär");
        sp.put( "amenity_waste_basket", "Papperskorg");
        sp.put( "amenity_youth_centre", "Ungdomscenter");
        sp.put( "building_chapel", "Kapell");
        sp.put( "building_church", "Kyrka");
        sp.put( "building_garage", "Garage");
        sp.put( "building_hospital", "Sjukhusbyggnad");
        sp.put( "building_hotel", "Hotell");
        sp.put( "building_house", "Hus");
        sp.put( "building_office", "Kontorsbyggnad");
        sp.put( "building_school", "Skolbyggnad");
        sp.put( "building_shop", "Affär");
        sp.put( "building_terrace", "Terass");
        sp.put( "building_train_station", "Järnvägsstation");
        sp.put( "highway_bus_stop", "Busshållplats");
        sp.put( "under_konstruktion", "Väg");
        sp.put( "highway_cycleway", "Cykelspår");
        sp.put( "highway_footway", "Gångväg");
        sp.put( "highway_gate", "Grind");
        sp.put( "highway_motorway", "Motorväg");
        sp.put( "highway_pedestrian", "Gångväg");
        sp.put( "highway_platform", "Perrong");
        sp.put( "highway_road", "Väg");
        sp.put( "highway_steps", "Trappa");
        sp.put( "highway_trail", "Vandringsled");
        sp.put( "väg_highway", "Oasfalterad");
        sp.put( "plats_historic", "Arkeologisk");
        sp.put( "historic_battlefield", "Slagfält");
        sp.put( "historic_boundary_stone", "Gränssten");
        sp.put( "historic_building", "Byggnad");
        sp.put( "historic_castle", "Slott");
        sp.put( "historic_church", "Kyrka");
        sp.put( "historic_house", "Hus");
        sp.put( "historic_icon", "Ikon");
        sp.put( "historic_mine", "Gruva");
        sp.put( "historic_monument", "Monument");
        sp.put( "historic_museum", "Museum");
        sp.put( "historic_ruins", "Ruin");
        sp.put( "historic_tower", "Torn");
        sp.put( "historic_wreck", "Vrak");
        sp.put( "landuse_allotments", "Kolonilotter");
        sp.put( "landuse_cemetery", "Begravningsplats");
        sp.put( "landuse_farm", "Bondgård");
        sp.put( "landuse_forest", "Skog");
        sp.put( "landuse_industrial", "Industriområde");
        sp.put( "landuse_military", "Militärområde");
        sp.put( "landuse_mine", "Gruva");
        sp.put( "landuse_park", "Park");
        sp.put( "landuse_residential", "Bostadsområde");
        sp.put( "landuse_vineyard", "Vingård");
        sp.put( "leisure_fishing", "Fiskevatten");
        sp.put( "leisure_garden", "Trädgård");
        sp.put( "leisure_golf_course", "Golfbana");
        sp.put( "leisure_ice_rink", "Isrink");
        sp.put( "leisure_marina", "Marina");
        sp.put( "leisure_miniature_golf", "Minigolf");
        sp.put( "leisure_nature_reserve", "Naturreservat");
        sp.put( "leisure_nature_reserve", "Naturreservats");
        sp.put( "leisure_park", "Park");
        sp.put( "leisure_playground", "Lekplats");
        sp.put( "leisure_sports_centre", "Sporthall");
        sp.put( "leisure_stadium", "Stadium");
        sp.put( "leisure_water_park", "Vattenpark");
        sp.put( "natural_bay", "Bukt");
        sp.put( "natural_beach", "Strand");
        sp.put( "natural_cape", "Udde");
        sp.put( "natural_cave_entrance", "Grottmynning");
        sp.put( "natural_channel", "Kanal");
        sp.put( "natural_cliff", "Klippa");
        sp.put( "natural_coastline", "Kustlinje");
        sp.put( "natural_crater", "Krater");
        sp.put( "natural_fjord", "Fjord");
        sp.put( "natural_geyser", "Gejser");
        sp.put( "natural_glacier", "Glaciär");
        sp.put( "natural_hill", "Kulle");
        sp.put( "natural_island", "Ö");
        sp.put( "natural_marsh", "Träsk");
        sp.put( "natural_moor", "Hed");
        sp.put( "natural_mud", "Lera");
        sp.put( "natural_peak", "Topp");
        sp.put( "natural_reef", "Rev");
        sp.put( "natural_river", "Flod");
        sp.put( "natural_rock", "Klippa");
        sp.put( "natural_scree", "Taluskon");
        sp.put( "natural_shoal", "Sandbank");
        sp.put( "natural_spring", "Källa");
        sp.put( "natural_tree", "Träd");
        sp.put( "natural_valley", "Dal");
        sp.put( "natural_volcano", "Vulkan");
        sp.put( "natural_water", "Vatten");
        sp.put( "natural_wetland", "Våtmark");
        sp.put( "natural_wood", "Skog");
        sp.put( "place_city", "Stad");
        sp.put( "place_country", "Land");
        sp.put( "place_county", "Län");
        sp.put( "place_farm", "Bondgård");
        sp.put( "place_hamlet", "By");
        sp.put( "place_house", "Hus");
        sp.put( "place_houses", "Hus");
        sp.put( "place_island", "Ö");
        sp.put( "place_islet", "Holme");
        sp.put( "place_municipality", "Kommun");
        sp.put( "place_postcode", "Postnummer");
        sp.put( "place_region", "Region");
        sp.put( "place_sea", "Hav");
        sp.put( "place_suburb", "Förort");
        sp.put( "place_town", "Ort");
        sp.put( "ort_place", "Mindre");
        sp.put( "järnvägsstation_railway", "Nedlagd");
        sp.put( "järnvägsstations_railway", "Nedlagd");
        sp.put( "railway_funicular", "Bergbana");
        sp.put( "railway_light_rail", "Spårvagn");
        sp.put( "railway_narrow_gauge", "Smalspårsjärnväg");
        sp.put( "railway_platform", "Tågperrong");
        sp.put( "railway_station", "Tågstation");
        sp.put( "railway_subway_entrance", "Tunnelbaneingång");
        sp.put( "shop_bakery", "Bageri");
        sp.put( "shop_bicycle", "Cykelaffär");
        sp.put( "shop_books", "Bokhandel");
        sp.put( "shop_butcher", "Slaktare");
        sp.put( "shop_car_dealer", "Bilförsäljare");
        sp.put( "shop_car_parts", "Bildelar");
        sp.put( "shop_car_repair", "Bilverkstad");
        sp.put( "shop_computer", "Datorbutik");
        sp.put( "shop_convenience", "Närköp");
        sp.put( "shop_convenience", "Närköps");
        sp.put( "shop_dry_cleaning", "Kemtvätt");
        sp.put( "shop_florist", "Blommor");
        sp.put( "shop_food", "Mataffär");
        sp.put( "shop_funeral_directors", "Begravningsbyrå");
        sp.put( "shop_gallery", "Galleri");
        sp.put( "shop_hairdresser", "Frisör");
        sp.put( "shop_insurance", "Försäkring");
        sp.put( "shop_jewelry", "Guldsmed");
        sp.put( "shop_kiosk", "Kiosk");
        sp.put( "shop_mall", "Köpcentrum");
        sp.put( "shop_optician", "Optiker");
        sp.put( "shop_pet", "Djuraffär");
        sp.put( "shop_photo", "Fotoaffär");
        sp.put( "shop_salon", "Salong");
        sp.put( "shop_shoes", "Skoaffär");
        sp.put( "shop_toys", "Leksaksaffär");
        sp.put( "shop_travel_agency", "Resebyrå");
        sp.put( "tourism_alpine_hut", "Fjällbod");
        sp.put( "tourism_artwork", "Konstverk");
        sp.put( "tourism_attraction", "Attraktion");
        sp.put( "and_breakfast", "Bad");
        sp.put( "tourism_cabin", "Stuga");
        sp.put( "tourism_camp_site", "Campingplats");
        sp.put( "tourism_caravan_site", "Husvagnsuppställningsplats");
        sp.put( "tourism_hostel", "Vandrarhem");
        sp.put( "tourism_hotel", "Hotell");
        sp.put( "tourism_information", "Turistinformation");
        sp.put( "tourism_motel", "Motell");
        sp.put( "tourism_museum", "Museum");
        sp.put( "tourism_picnic_site", "Picknickplats");
        sp.put( "tourism_theme_park", "Nöjespark");
        sp.put( "tourism_theme_park", "Nöjesparks");
        sp.put( "tourism_valley", "Dal");
        sp.put( "tourism_viewpoint", "Utsiktspunkt");
        sp.put( "tourism_zoo", "Djurpark");
        sp.put( "waterway_canal", "Kanal");
        sp.put( "waterway_lock", "Sluss");
        sp.put( "waterway_lock_gate", "Slussport");
        sp.put( "waterway_waterfall", "Vattenfall");
        return sp;
    }
}
