package net.osmand.plus.specialPhrases;

/*
 * DO NOT EDIT THIS CLASS
 *  
 * This class is generated by the generate.sh script, and the data comes from 
 * http://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases
 * 
 * If you want to edit the data, please edit it on the wiki and run the script again
 * If you want to edit the formatting, please edit the generate.sh script and run it again
 */


import java.util.HashMap;
import java.util.Map;

/**
 * class that contains the special phrases and is used to create the map
 * 
 * Data CC-BY-SA http://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases
 * 
 * @author sander
 * 
 */
 public class SpecialPhrasesFA {
     public static Map<String,String> createMap(){
        HashMap<String,String> sp = new HashMap<String,String>(); // maybe search an optimal load factor and initial capacity
        sp.put( "aeroway_aerodrome", "فرودگاه");
        sp.put( "بانک_amenity", "عابر");
        sp.put( "amenity_bank", "بانک");
        sp.put( "amenity_bench", "نیمکت");
        sp.put( "خانه_amenity", "فاحشه");
        sp.put( "amenity_cafe", "کافه");
        sp.put( "amenity_cinema", "سینما");
        sp.put( "amenity_clinic", "درمانگاه");
        sp.put( "amenity_courthouse", "دادگاه");
        sp.put( "amenity_dentist", "دندانپزشک");
        sp.put( "دانشجویی_amenity", "خوابگاه");
        sp.put( "amenity_embassy", "سفارت");
        sp.put( "نشانی_amenity", "آتش");
        sp.put( "بنزین_amenity", "پمپ");
        sp.put( "amenity_hospital", "بیمارستان");
        sp.put( "amenity_hotel", "هتل");
        sp.put( "amenity_kindergarten", "کودکستان");
        sp.put( "amenity_library", "کتابخانه");
        sp.put( "amenity_market", "بازار");
        sp.put( "amenity_marketplace", "بازار");
        sp.put( "amenity_office", "دفتر");
        sp.put( "amenity_park", "پارک");
        sp.put( "amenity_parking", "پارکینگ");
        sp.put( "amenity_pharmacy", "داروخانه");
        sp.put( "amenity_police", "پلیس");
        sp.put( "پست_amenity", "صندوق");
        sp.put( "پست_amenity", "اداره");
        sp.put( "amenity_prison", "زندان");
        sp.put( "amenity_pub", "میخانه");
        sp.put( "amenity_recycling", "بازیافت");
        sp.put( "amenity_restaurant", "رستوران");
        sp.put( "amenity_school", "مدرسه");
        sp.put( "amenity_supermarket", "سوپرمارکت");
        sp.put( "amenity_taxi", "تاکسی");
        sp.put( "amenity_theatre", "تئاتر");
        sp.put( "داری_amenity", "شهر");
        sp.put( "amenity_university", "دانشگاه");
        sp.put( "اشغال_amenity", "سطل");
        sp.put( "building_garage", "گاراژ");
        sp.put( "building_hotel", "هتل");
        sp.put( "building_house", "خانه");
        sp.put( "building_stadium", "ورزشگاه");
        sp.put( "building_tower", "برج");
        sp.put( "اتوبوس_highway", "ایستگاه");
        sp.put( "highway_motorway", "اتوبان");
        sp.put( "highway_path", "مسیر");
        sp.put( "highway_road", "جاده");
        sp.put( "highway_steps", "پله");
        sp.put( "highway_trunk", "بزرگراه");
        sp.put( "historic_castle", "قلعه");
        sp.put( "historic_museum", "موزه");
        sp.put( "historic_tower", "برج");
        sp.put( "کشاورزی_landuse", "زمین");
        sp.put( "landuse_forest", "جنگل");
        sp.put( "landuse_mountain", "کوه");
        sp.put( "landuse_park", "پارک");
        sp.put( "landuse_railway", "ریل");
        sp.put( "leisure_garden", "باغ");
        sp.put( "leisure_park", "پارک");
        sp.put( "leisure_stadium", "ورزشگاه");
        sp.put( "natural_beach", "ساحل");
        sp.put( "natural_channel", "کانال");
        sp.put( "natural_coastline", "ساحل");
        sp.put( "natural_hill", "تپه");
        sp.put( "natural_island", "جزیره");
        sp.put( "natural_point", "نقطه");
        sp.put( "خانه_natural", "رود");
        sp.put( "natural_rock", "صخره");
        sp.put( "natural_tree", "درخت");
        sp.put( "natural_valley", "دره");
        sp.put( "آتشفشان_natural", "کوه");
        sp.put( "natural_water", "اب");
        sp.put( "natural_wood", "جنگل");
        sp.put( "بزرگ_place", "شهر");
        sp.put( "place_country", "کشور");
        sp.put( "place_farm", "مزرعه");
        sp.put( "place_house", "خانه");
        sp.put( "place_island", "جزیره");
        sp.put( "place_sea", "دریا");
        sp.put( "place_suburb", "محله");
        sp.put( "place_town", "شهر");
        sp.put( "place_village", "دهکده");
        sp.put( "shop_bakery", "نانوایی");
        sp.put( "shop_butcher", "قصاب");
        sp.put( "shop_kiosk", "کیوسک");
        sp.put( "shop_market", "بازار");
        sp.put( "shop_supermarket", "سوپرمارکت");
        sp.put( "tourism_hotel", "هتل");
        sp.put( "tourism_motel", "متل");
        sp.put( "tourism_museum", "موزه");
        sp.put( "tourism_valley", "دره");
        sp.put( "وحش_tourism", "باغ");
        sp.put( "waterway_canal", "کانال");
        sp.put( "waterway_river", "رودخانه");
        sp.put( "waterway_waterfall", "ابشار");
        return sp;
    }
}
