package net.osmand.plus.specialPhrases;

/*
 * DO NOT EDIT THIS CLASS
 *  
 * This class is generated by the generate.sh script, and the data comes from 
 * http://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases
 * 
 * If you want to edit the data, please edit it on the wiki and run the script again
 * If you want to edit the formatting, please edit the generate.sh script and run it again
 */


import java.util.HashMap;
import java.util.Map;

/**
 * class that contains the special phrases and is used to create the map
 * 
 * Data CC-BY-SA http://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases
 * 
 * @author sander
 * 
 */
 public class SpecialPhrasesJA {
     public static Map<String,String> createMap(){
        HashMap<String,String> sp = new HashMap<String,String>(); // maybe search an optimal load factor and initial capacity
        sp.put( "aerodrome", "空港");
        sp.put( "bank", "銀行");
        sp.put( "car_rental", "レンタカー");
        sp.put( "car_wash", "洗車");
        sp.put( "casino", "賭場");
        sp.put( "college", "大学");
        sp.put( "dentist", "歯科医");
        sp.put( "embassy", "大使館");
        sp.put( "hotel", "ホテル");
        sp.put( "kindergarten", "幼稚園");
        sp.put( "library", "図書館");
        sp.put( "pub", "パブ（立ち吞み屋）");
        sp.put( "sauna", "サウナ");
        sp.put( "school", "学校");
        sp.put( "shop", "店舗");
        sp.put( "taxi", "タクシー乗り場");
        sp.put( "university", "大学");
        sp.put( "wifi", "WiFiアクセスポイント");
        sp.put( "bus_stop", "バス停");
        sp.put( "steps", "階段");
        sp.put( "city", "市");
        sp.put( "theme_park", "テーマパーク");
        sp.put( "valley", "谷");
        sp.put( "zoo", "動物園");
        return sp;
    }
}
