package net.osmand.plus.specialPhrases;

/*
 * DO NOT EDIT THIS CLASS
 *  
 * This class is generated by the generate.sh script, and the data comes from 
 * http://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases
 * 
 * If you want to edit the data, please edit it on the wiki and run the script again
 * If you want to edit the formatting, please edit the generate.sh script and run it again
 */


import java.util.HashMap;
import java.util.Map;

/**
 * class that contains the special phrases and is used to create the map
 * 
 * Data CC-BY-SA http://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases
 * 
 * @author sander
 * 
 */
 public class SpecialPhrasesPS {
     public static Map<String,String> createMap(){
        HashMap<String,String> sp = new HashMap<String,String>(); // maybe search an optimal load factor and initial capacity
        sp.put( "amenity_bank", "بانک");
        sp.put( "amenity_clinic", "کلينيک");
        sp.put( "amenity_college", "پوهنځی");
        sp.put( "amenity_embassy", "سفارت");
        sp.put( "amenity_hospital", "روغتون");
        sp.put( "amenity_hotel", "هوټل");
        sp.put( "amenity_park", "پارک");
        sp.put( "amenity_pharmacy", "درملتون");
        sp.put( "amenity_police", "پوليس");
        sp.put( "amenity_school", "ښوونځی");
        sp.put( "amenity_shop", "هټۍ");
        sp.put( "amenity_theatre", "نندارتون");
        sp.put( "building_hotel", "هوټل");
        sp.put( "building_shop", "هټۍ");
        sp.put( "building_stadium", "لوبغالی");
        sp.put( "building_tower", "برج");
        sp.put( "highway_bus_stop", "تمځای");
        sp.put( "highway_road", "واټ");
        sp.put( "historic_castle", "ماڼۍ");
        sp.put( "historic_church", "کليسا");
        sp.put( "historic_house", "کور");
        sp.put( "historic_museum", "موزيم");
        sp.put( "historic_tower", "برج");
        sp.put( "landuse_cemetery", "هديره");
        sp.put( "landuse_forest", "ځنګل");
        sp.put( "landuse_park", "پارک");
        sp.put( "leisure_park", "پارک");
        sp.put( "natural_hill", "غونډۍ");
        sp.put( "natural_island", "ټاپو");
        sp.put( "natural_peak", "څوکه");
        sp.put( "natural_tree", "ونه");
        sp.put( "natural_valley", "دره");
        sp.put( "natural_water", "اوبه");
        sp.put( "ډګر_aeroway", "هوايي");
        sp.put( "place_city", "ښار");
        sp.put( "place_country", "هېواد");
        sp.put( "place_farm", "فارم");
        sp.put( "place_house", "کور");
        sp.put( "place_houses", "کورونه");
        sp.put( "place_island", "ټاپو");
        sp.put( "place_region", "سيمه");
        sp.put( "place_town", "ښارګوټی");
        sp.put( "place_village", "کلی");
        sp.put( "shop_bakery", "بټيارۍ");
        sp.put( "shop_gallery", "ګالېري");
        sp.put( "tourism_guest_house", "مېلمستون");
        sp.put( "tourism_hostel", "ليليه");
        sp.put( "tourism_hotel", "هوټل");
        sp.put( "tourism_information", "مالومات");
        sp.put( "tourism_museum", "موزيم");
        sp.put( "ځای_tourism", "مېله");
        sp.put( "tourism_valley", "دره");
        sp.put( "tourism_zoo", "ژوبڼ");
        return sp;
    }
}
