package net.osmand.plus.specialPhrases;

/*
 * DO NOT EDIT THIS CLASS
 *  
 * This class is generated by the generate.sh script, and the data comes from 
 * http://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases
 * 
 * If you want to edit the data, please edit it on the wiki and run the script again
 * If you want to edit the formatting, please edit the generate.sh script and run it again
 */


import java.util.HashMap;
import java.util.Map;

/**
 * class that contains the special phrases and is used to create the map
 * 
 * Data CC-BY-SA http://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases
 * 
 * @author sander
 * 
 */
 public class SpecialPhrasesFA {
     public static Map<String,String> createMap(){
        HashMap<String,String> sp = new HashMap<String,String>(); // maybe search an optimal load factor and initial capacity
        sp.put( "aerodrome", "فرودگاه");
        sp.put( "amenity", "عابر");
        sp.put( "bank", "بانک");
        sp.put( "bench", "نیمکت");
        sp.put( "amenity", "فاحشه");
        sp.put( "cafe", "کافه");
        sp.put( "cinema", "سینما");
        sp.put( "clinic", "درمانگاه");
        sp.put( "courthouse", "دادگاه");
        sp.put( "dentist", "دندانپزشک");
        sp.put( "amenity", "خوابگاه");
        sp.put( "embassy", "سفارت");
        sp.put( "amenity", "آتش");
        sp.put( "amenity", "پمپ");
        sp.put( "hospital", "بیمارستان");
        sp.put( "hotel", "هتل");
        sp.put( "kindergarten", "کودکستان");
        sp.put( "library", "کتابخانه");
        sp.put( "market", "بازار");
        sp.put( "marketplace", "بازار");
        sp.put( "office", "دفتر");
        sp.put( "park", "پارک");
        sp.put( "parking", "پارکینگ");
        sp.put( "pharmacy", "داروخانه");
        sp.put( "police", "پلیس");
        sp.put( "amenity", "صندوق");
        sp.put( "amenity", "اداره");
        sp.put( "prison", "زندان");
        sp.put( "pub", "میخانه");
        sp.put( "recycling", "بازیافت");
        sp.put( "restaurant", "رستوران");
        sp.put( "school", "مدرسه");
        sp.put( "supermarket", "سوپرمارکت");
        sp.put( "taxi", "تاکسی");
        sp.put( "theatre", "تئاتر");
        sp.put( "amenity", "شهر");
        sp.put( "university", "دانشگاه");
        sp.put( "amenity", "سطل");
        sp.put( "garage", "گاراژ");
        sp.put( "hotel", "هتل");
        sp.put( "house", "خانه");
        sp.put( "stadium", "ورزشگاه");
        sp.put( "tower", "برج");
        sp.put( "highway", "ایستگاه");
        sp.put( "motorway", "اتوبان");
        sp.put( "path", "مسیر");
        sp.put( "road", "جاده");
        sp.put( "steps", "پله");
        sp.put( "trunk", "بزرگراه");
        sp.put( "castle", "قلعه");
        sp.put( "museum", "موزه");
        sp.put( "tower", "برج");
        sp.put( "landuse", "زمین");
        sp.put( "forest", "جنگل");
        sp.put( "mountain", "کوه");
        sp.put( "park", "پارک");
        sp.put( "railway", "ریل");
        sp.put( "garden", "باغ");
        sp.put( "park", "پارک");
        sp.put( "stadium", "ورزشگاه");
        sp.put( "beach", "ساحل");
        sp.put( "channel", "کانال");
        sp.put( "coastline", "ساحل");
        sp.put( "hill", "تپه");
        sp.put( "island", "جزیره");
        sp.put( "point", "نقطه");
        sp.put( "natural", "رود");
        sp.put( "rock", "صخره");
        sp.put( "tree", "درخت");
        sp.put( "valley", "دره");
        sp.put( "natural", "کوه");
        sp.put( "water", "اب");
        sp.put( "wood", "جنگل");
        sp.put( "place", "شهر");
        sp.put( "country", "کشور");
        sp.put( "farm", "مزرعه");
        sp.put( "house", "خانه");
        sp.put( "island", "جزیره");
        sp.put( "sea", "دریا");
        sp.put( "suburb", "محله");
        sp.put( "town", "شهر");
        sp.put( "village", "دهکده");
        sp.put( "bakery", "نانوایی");
        sp.put( "butcher", "قصاب");
        sp.put( "kiosk", "کیوسک");
        sp.put( "market", "بازار");
        sp.put( "supermarket", "سوپرمارکت");
        sp.put( "hotel", "هتل");
        sp.put( "motel", "متل");
        sp.put( "museum", "موزه");
        sp.put( "valley", "دره");
        sp.put( "tourism", "باغ");
        sp.put( "canal", "کانال");
        sp.put( "river", "رودخانه");
        sp.put( "waterfall", "ابشار");
        return sp;
    }
}
