package net.osmand.plus.specialPhrases;

/*
 * DO NOT EDIT THIS CLASS
 *  
 * This class is generated by the generate.sh script, and the data comes from 
 * http://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases
 * 
 * If you want to edit the data, please edit it on the wiki and run the script again
 * If you want to edit the formatting, please edit the generate.sh script and run it again
 */


import java.util.HashMap;
import java.util.Map;

/**
 * class that contains the special phrases and is used to create the map
 * 
 * Data CC-BY-SA http://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases
 * 
 * @author sander
 * 
 */
 public class SpecialPhrasesIS {
     public static Map<String,String> createMap(){
        HashMap<String,String> sp = new HashMap<String,String>(); // maybe search an optimal load factor and initial capacity
        sp.put( "aeroway_aerodrome", "Flugvöllurinn");
        sp.put( "amenity_atm", "Hraðbankinn");
        sp.put( "amenity_bar", "Barinn");
        sp.put( "amenity_bicycle_rental", "Reiðhjólaleigan");
        sp.put( "amenity_brothel", "Hóruhúsið");
        sp.put( "amenity_cafe", "Kaffihúsið");
        sp.put( "amenity_car_rental", "Bílaleigan");
        sp.put( "amenity_car_wash", "Bílaþvottastöðin");
        sp.put( "amenity_cinema", "Kvikmyndarhúsið");
        sp.put( "amenity_dentist", "Tannlæknirinn");
        sp.put( "amenity_embassy", "Sendiráðið");
        sp.put( "amenity_fast_food", "Skyndibitastaðurinn");
        sp.put( "amenity_fire_hydrant", "Brunahaninn");
        sp.put( "amenity_hospital", "Sjúkrahúsið");
        sp.put( "amenity_hotel", "Hótelið");
        sp.put( "amenity_library", "Bókasafnið");
        sp.put( "amenity_post_box", "Póstkassinn");
        sp.put( "amenity_post_office", "Pósthúsið");
        sp.put( "amenity_prison", "Fangelsið");
        sp.put( "amenity_pub", "Pöbbinn");
        sp.put( "amenity_restaurant", "Veitingastaðurinn");
        sp.put( "amenity_sauna", "Gufubaðið");
        sp.put( "amenity_shop", "Verslunin");
        sp.put( "amenity_theatre", "Leikhúsið");
        sp.put( "building_chapel", "Kapellan");
        sp.put( "building_church", "Kirkjan");
        sp.put( "highway_ford", "Vaðið");
        sp.put( "highway_residential", "Íbúðargatan");
        sp.put( "historic_castle", "Kastalinn");
        sp.put( "landuse_military", "Hersvæðið");
        sp.put( "leisure_sports_centre", "Íþróttamiðstöðin");
        sp.put( "leisure_swimming_pool", "Sundlaugin");
        sp.put( "leisure_water_park", "Vatnsleikjagarðurinn");
        sp.put( "natural_bay", "Flóinn");
        sp.put( "natural_beach", "Ströndin");
        sp.put( "natural_cave_entrance", "Hellisop");
        sp.put( "natural_crater", "Gígurinn");
        sp.put( "natural_fell", "Fellið");
        sp.put( "natural_fjord", "Fjörðurinn");
        sp.put( "natural_geyser", "Goshverinn");
        sp.put( "natural_glacier", "Jökullinn");
        sp.put( "natural_hill", "Hæðin");
        sp.put( "natural_island", "Eyjan");
        sp.put( "eða_tindurinn", "Fjallið");
        sp.put( "natural_reef", "Rifið");
        sp.put( "natural_river", "Áin");
        sp.put( "natural_tree", "Tréð");
        sp.put( "natural_valley", "Dalurinn");
        sp.put( "natural_volcano", "Eldfjallið");
        sp.put( "natural_water", "Vatnið");
        sp.put( "place_city", "Borgin");
        sp.put( "place_country", "Landið");
        sp.put( "place_farm", "Sveitabærinn");
        sp.put( "place_house", "Húsið");
        sp.put( "place_island", "Eyjan");
        sp.put( "place_islet", "Smáeyjan");
        sp.put( "place_postcode", "Póstnúmerið");
        sp.put( "place_region", "Svæðið");
        sp.put( "place_sea", "Hafið");
        sp.put( "place_suburb", "Hverfið");
        sp.put( "place_town", "Bærinn");
        sp.put( "place_village", "Þorpið");
        sp.put( "shop_bakery", "Bakaríið");
        sp.put( "shop_bicycle", "Hjólabúðin");
        sp.put( "shop_books", "Bókabúðin");
        sp.put( "shop_butcher", "Slátrarinn");
        sp.put( "shop_car", "Bílabúðin");
        sp.put( "shop_carpet", "Teppabúðin");
        sp.put( "shop_clothes", "Fatabúðin");
        sp.put( "shop_computer", "Tölvubúðin");
        sp.put( "shop_electronics", "Raftækjaverslunin");
        sp.put( "shop_fish", "Fiskbúðin");
        sp.put( "shop_florist", "Blómabúðin");
        sp.put( "shop_food", "Matbúðin");
        sp.put( "shop_furniture", "Húsgagnaverslunin");
        sp.put( "shop_gift", "Gjafabúðin");
        sp.put( "shop_hardware", "Verkfærabúðin");
        sp.put( "shop_hifi", "Hljómtækjabúðin");
        sp.put( "shop_kiosk", "Söluturninn");
        sp.put( "shop_mobile_phone", "Farsímaverslunin");
        sp.put( "shop_outdoor", "Útivistarbúðin");
        sp.put( "shop_pet", "Gæludýrabúðin");
        sp.put( "shop_toys", "Leikfangaverslunin");
        sp.put( "shop_travel_agency", "Ferðaskrifstofan");
        sp.put( "shop_video", "Videoleigan");
        sp.put( "tourism_artwork", "Listaverkið");
        sp.put( "tourism_hotel", "Hótelið");
        sp.put( "tourism_museum", "Safnið");
        sp.put( "tourism_valley", "Dalurinn");
        sp.put( "tourism_zoo", "Dýragarðurinn");
        sp.put( "waterway_dam", "Vatnsaflsvirkjunin");
        sp.put( "waterway_river", "Áin");
        sp.put( "waterway_stream", "Lækurinn");
        sp.put( "waterway_waterfall", "Fossinn");
        return sp;
    }
}
