package net.osmand.plus.specialPhrases;

/*
 * DO NOT EDIT THIS CLASS
 *  
 * This class is generated by the generate.sh script, and the data comes from 
 * http://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases
 * 
 * If you want to edit the data, please edit it on the wiki and run the script again
 * If you want to edit the formatting, please edit the generate.sh script and run it again
 */


import java.util.HashMap;
import java.util.Map;

/**
 * class that contains the special phrases and is used to create the map
 * 
 * Data CC-BY-SA http://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases
 * 
 * @author sander
 * 
 */
 public class SpecialPhrasesSV {
     public static Map<String,String> createMap(){
        HashMap<String,String> sp = new HashMap<String,String>(); // maybe search an optimal load factor and initial capacity
        sp.put( "aerodrome", "Flygplats");
        sp.put( "atm", "Bankomat");
        sp.put( "bank", "Bank");
        sp.put( "bar", "Bar");
        sp.put( "bench", "Bänk");
        sp.put( "bicycle_parking", "Cykelparkering");
        sp.put( "bicycle_rental", "Cykeluthyrning");
        sp.put( "brothel", "Bordell");
        sp.put( "bureau_de_change", "Växlingskontor");
        sp.put( "bus_station", "Busstation");
        sp.put( "car_rental", "Biluthyrning");
        sp.put( "car_sharing", "Bilpool");
        sp.put( "car_wash", "Biltvätt");
        sp.put( "cinema", "Biograf");
        sp.put( "crematorium", "Krematorium");
        sp.put( "dentist", "Tandläkare");
        sp.put( "doctors", "Läkare");
        sp.put( "drinking_water", "Dricksvatten");
        sp.put( "driving_school", "Körskola");
        sp.put( "embassy", "Ambassad");
        sp.put( "emergency_phone", "Nödtelefon");
        sp.put( "emergency_phone", "Nödtelefons");
        sp.put( "fast_food", "Snabbmat");
        sp.put( "ferry_terminal", "Färjeterminal");
        sp.put( "fire_hydrant", "Brandpost");
        sp.put( "fire_station", "Brandstation");
        sp.put( "fountain", "Fontän");
        sp.put( "fuel", "Bränsle");
        sp.put( "grave_yard", "Begravningsplats");
        sp.put( "hospital", "Sjukhus");
        sp.put( "hotel", "Hotell");
        sp.put( "ice_cream", "Glass");
        sp.put( "kindergarten", "Dagis");
        sp.put( "library", "Bibliotek");
        sp.put( "market", "Torghandel");
        sp.put( "marketplace", "nMarknad");
        sp.put( "nightclub", "Nattklubb");
        sp.put( "nightclub", "Nattklubbs");
        sp.put( "office", "Kontor");
        sp.put( "parking", "Parkeringsplats");
        sp.put( "pharmacy", "Apotek");
        sp.put( "place_of_worship", "Plats för tillbedjan");
        sp.put( "police", "Polis");
        sp.put( "post_office", "Postkontor");
        sp.put( "preschool", "Förskola");
        sp.put( "prison", "Fängelse");
        sp.put( "pub", "Pub");
        sp.put( "public_building", "Offentlig byggnad");
        sp.put( "recycling", "Återvinningsstation");
        sp.put( "restaurant", "Restaurang");
        sp.put( "retirement_home", "Äldreboende");
        sp.put( "sauna", "Bastu");
        sp.put( "school", "Skola");
        sp.put( "shop", "Affär");
        sp.put( "taxi", "Taxi");
        sp.put( "theatre", "Teater");
        sp.put( "toilets", "Toaletter");
        sp.put( "vending_machine", "Varumaskin");
        sp.put( "veterinary", "Veterinär");
        sp.put( "waste_basket", "Papperskorg");
        sp.put( "youth_centre", "Ungdomscenter");
        sp.put( "chapel", "Kapell");
        sp.put( "church", "Kyrka");
        sp.put( "garage", "Garage");
        sp.put( "hospital", "Sjukhusbyggnad");
        sp.put( "hotel", "Hotell");
        sp.put( "house", "Hus");
        sp.put( "office", "Kontorsbyggnad");
        sp.put( "school", "Skolbyggnad");
        sp.put( "shop", "Affär");
        sp.put( "terrace", "Terass");
        sp.put( "train_station", "Järnvägsstation");
        sp.put( "bus_stop", "Busshållplats");
        sp.put( "construction", "Väg under konstruktion");
        sp.put( "cycleway", "Cykelspår");
        sp.put( "footway", "Gångväg");
        sp.put( "gate", "Grind");
        sp.put( "motorway", "Motorväg");
        sp.put( "pedestrian", "Gångväg");
        sp.put( "platform", "Perrong");
        sp.put( "road", "Väg");
        sp.put( "steps", "Trappa");
        sp.put( "trail", "Vandringsled");
        sp.put( "unsurfaced", "Oasfalterad väg");
        sp.put( "archaeological_site", "Arkeologisk plats");
        sp.put( "battlefield", "Slagfält");
        sp.put( "boundary_stone", "Gränssten");
        sp.put( "building", "Byggnad");
        sp.put( "castle", "Slott");
        sp.put( "church", "Kyrka");
        sp.put( "house", "Hus");
        sp.put( "icon", "Ikon");
        sp.put( "mine", "Gruva");
        sp.put( "monument", "Monument");
        sp.put( "museum", "Museum");
        sp.put( "ruins", "Ruin");
        sp.put( "tower", "Torn");
        sp.put( "wreck", "Vrak");
        sp.put( "allotments", "Kolonilotter");
        sp.put( "cemetery", "Begravningsplats");
        sp.put( "farm", "Bondgård");
        sp.put( "forest", "Skog");
        sp.put( "industrial", "Industriområde");
        sp.put( "military", "Militärområde");
        sp.put( "mine", "Gruva");
        sp.put( "park", "Park");
        sp.put( "residential", "Bostadsområde");
        sp.put( "vineyard", "Vingård");
        sp.put( "fishing", "Fiskevatten");
        sp.put( "garden", "Trädgård");
        sp.put( "golf_course", "Golfbana");
        sp.put( "ice_rink", "Isrink");
        sp.put( "marina", "Marina");
        sp.put( "miniature_golf", "Minigolf");
        sp.put( "nature_reserve", "Naturreservat");
        sp.put( "nature_reserve", "Naturreservats");
        sp.put( "park", "Park");
        sp.put( "playground", "Lekplats");
        sp.put( "sports_centre", "Sporthall");
        sp.put( "stadium", "Stadium");
        sp.put( "water_park", "Vattenpark");
        sp.put( "bay", "Bukt");
        sp.put( "beach", "Strand");
        sp.put( "cape", "Udde");
        sp.put( "cave_entrance", "Grottmynning");
        sp.put( "channel", "Kanal");
        sp.put( "cliff", "Klippa");
        sp.put( "coastline", "Kustlinje");
        sp.put( "crater", "Krater");
        sp.put( "fjord", "Fjord");
        sp.put( "geyser", "Gejser");
        sp.put( "glacier", "Glaciär");
        sp.put( "hill", "Kulle");
        sp.put( "island", "Ö");
        sp.put( "marsh", "Träsk");
        sp.put( "moor", "Hed");
        sp.put( "mud", "Lera");
        sp.put( "peak", "Topp");
        sp.put( "reef", "Rev");
        sp.put( "river", "Flod");
        sp.put( "rock", "Klippa");
        sp.put( "scree", "Taluskon");
        sp.put( "shoal", "Sandbank");
        sp.put( "spring", "Källa");
        sp.put( "tree", "Träd");
        sp.put( "valley", "Dal");
        sp.put( "volcano", "Vulkan");
        sp.put( "water", "Vatten");
        sp.put( "wetland", "Våtmark");
        sp.put( "wood", "Skog");
        sp.put( "city", "Stad");
        sp.put( "country", "Land");
        sp.put( "county", "Län");
        sp.put( "farm", "Bondgård");
        sp.put( "hamlet", "By");
        sp.put( "house", "Hus");
        sp.put( "houses", "Hus");
        sp.put( "island", "Ö");
        sp.put( "islet", "Holme");
        sp.put( "municipality", "Kommun");
        sp.put( "postcode", "Postnummer");
        sp.put( "region", "Region");
        sp.put( "sea", "Hav");
        sp.put( "suburb", "Förort");
        sp.put( "town", "Ort");
        sp.put( "village", "Mindre ort");
        sp.put( "disused_station", "Nedlagd järnvägsstation");
        sp.put( "disused_station", "Nedlagd järnvägsstations");
        sp.put( "funicular", "Bergbana");
        sp.put( "light_rail", "Spårvagn");
        sp.put( "narrow_gauge", "Smalspårsjärnväg");
        sp.put( "platform", "Tågperrong");
        sp.put( "station", "Tågstation");
        sp.put( "subway_entrance", "Tunnelbaneingång");
        sp.put( "bakery", "Bageri");
        sp.put( "bicycle", "Cykelaffär");
        sp.put( "books", "Bokhandel");
        sp.put( "butcher", "Slaktare");
        sp.put( "car_dealer", "Bilförsäljare");
        sp.put( "car_parts", "Bildelar");
        sp.put( "car_repair", "Bilverkstad");
        sp.put( "computer", "Datorbutik");
        sp.put( "convenience", "Närköp");
        sp.put( "convenience", "Närköps");
        sp.put( "dry_cleaning", "Kemtvätt");
        sp.put( "florist", "Blommor");
        sp.put( "food", "Mataffär");
        sp.put( "funeral_directors", "Begravningsbyrå");
        sp.put( "gallery", "Galleri");
        sp.put( "hairdresser", "Frisör");
        sp.put( "insurance", "Försäkring");
        sp.put( "jewelry", "Guldsmed");
        sp.put( "kiosk", "Kiosk");
        sp.put( "mall", "Köpcentrum");
        sp.put( "optician", "Optiker");
        sp.put( "pet", "Djuraffär");
        sp.put( "photo", "Fotoaffär");
        sp.put( "salon", "Salong");
        sp.put( "shoes", "Skoaffär");
        sp.put( "toys", "Leksaksaffär");
        sp.put( "travel_agency", "Resebyrå");
        sp.put( "alpine_hut", "Fjällbod");
        sp.put( "artwork", "Konstverk");
        sp.put( "attraction", "Attraktion");
        sp.put( "bed_and_breakfast", "Bad and breakfast");
        sp.put( "cabin", "Stuga");
        sp.put( "camp_site", "Campingplats");
        sp.put( "caravan_site", "Husvagnsuppställningsplats");
        sp.put( "hostel", "Vandrarhem");
        sp.put( "hotel", "Hotell");
        sp.put( "information", "Turistinformation");
        sp.put( "motel", "Motell");
        sp.put( "museum", "Museum");
        sp.put( "picnic_site", "Picknickplats");
        sp.put( "theme_park", "Nöjespark");
        sp.put( "theme_park", "Nöjesparks");
        sp.put( "valley", "Dal");
        sp.put( "viewpoint", "Utsiktspunkt");
        sp.put( "zoo", "Djurpark");
        sp.put( "canal", "Kanal");
        sp.put( "lock", "Sluss");
        sp.put( "lock_gate", "Slussport");
        sp.put( "waterfall", "Vattenfall");
        return sp;
    }
}
