package net.osmand.plus.plugins.aistracker;

import java.util.AbstractMap;
import java.util.Map;

public final class AisObjectConstants {
    public final static int INVALID_HEADING = 511;
    public final static int INVALID_NAV_STATUS = 15;
    public final static int INVALID_MANEUVER_INDICATOR = 0;
    public final static int INVALID_SHIP_TYPE = 0;
    public final static int INVALID_DIMENSION = 0;
    public final static int INVALID_ETA = 0;
    public final static int INVALID_ETA_HOUR = 24;
    public final static int INVALID_ETA_MIN = 60;
    public final static int INVALID_ALTITUDE = 4095;
    public final static int UNSPECIFIED_AID_TYPE = 0;
    public final static double INVALID_COG = 360.0;
    public final static double INVALID_SOG = 1023.0;
    public final static double INVALID_LAT = 91.0;
    public final static double INVALID_LON = 181.0;
    public final static double INVALID_ROT = 128.0;
    public final static double INVALID_DRAUGHT = 0.0;
    public final static double INVALID_TCPA = -10000.0d;
    public final static float INVALID_CPA = -1.0f;
    public final static int CPA_UPDATE_TIMEOUT_IN_SECONDS = 10;

    public static enum AisObjType {
        AIS_VESSEL,
        AIS_VESSEL_SPORT,
        AIS_VESSEL_FAST,
        AIS_VESSEL_PASSENGER,
        AIS_VESSEL_FREIGHT,
        AIS_VESSEL_COMMERCIAL,
        AIS_VESSEL_AUTHORITIES,
        AIS_VESSEL_SAR,
        AIS_LANDSTATION,
        AIS_AIRPLANE,
        AIS_SART,
        AIS_ATON, // aids to navigation
        AIS_ATON_VIRTUAL,
        AIS_INVALID
    }
    public static final Map<Integer, String> COUNTRY_CODES = Map.ofEntries(
            new AbstractMap.SimpleEntry<>(201, "Albania"),
            new AbstractMap.SimpleEntry<>(202, "Andorra"),
            new AbstractMap.SimpleEntry<>(203, "Austria"),
            new AbstractMap.SimpleEntry<>(204, "Portugal"),
            new AbstractMap.SimpleEntry<>(205, "Belgium"),
            new AbstractMap.SimpleEntry<>(206, "Belarus"),
            new AbstractMap.SimpleEntry<>(207, "Bulgaria"),
            new AbstractMap.SimpleEntry<>(208, "Vatican"),
            new AbstractMap.SimpleEntry<>(209, "Cyprus"),
            new AbstractMap.SimpleEntry<>(210, "Cyprus"),
            new AbstractMap.SimpleEntry<>(211, "Germany"),
            new AbstractMap.SimpleEntry<>(212, "Cyprus"),
            new AbstractMap.SimpleEntry<>(213, "Georgia"),
            new AbstractMap.SimpleEntry<>(214, "Moldova"),
            new AbstractMap.SimpleEntry<>(215, "Malta"),
            new AbstractMap.SimpleEntry<>(216, "Armenia"),
            new AbstractMap.SimpleEntry<>(218, "Germany"),
            new AbstractMap.SimpleEntry<>(219, "Denmark"),
            new AbstractMap.SimpleEntry<>(220, "Denmark"),
            new AbstractMap.SimpleEntry<>(224, "Spain"),
            new AbstractMap.SimpleEntry<>(225, "Spain"),
            new AbstractMap.SimpleEntry<>(226, "France"),
            new AbstractMap.SimpleEntry<>(227, "France"),
            new AbstractMap.SimpleEntry<>(228, "France"),
            new AbstractMap.SimpleEntry<>(229, "Malta"),
            new AbstractMap.SimpleEntry<>(230, "Finland"),
            new AbstractMap.SimpleEntry<>(231, "Faroe Is"),
            new AbstractMap.SimpleEntry<>(232, "United Kingdom"),
            new AbstractMap.SimpleEntry<>(233, "United Kingdom"),
            new AbstractMap.SimpleEntry<>(234, "United Kingdom"),
            new AbstractMap.SimpleEntry<>(235, "United Kingdom"),
            new AbstractMap.SimpleEntry<>(236, "Gibraltar"),
            new AbstractMap.SimpleEntry<>(237, "Greece"),
            new AbstractMap.SimpleEntry<>(238, "Croatia"),
            new AbstractMap.SimpleEntry<>(239, "Greece"),
            new AbstractMap.SimpleEntry<>(240, "Greece"),
            new AbstractMap.SimpleEntry<>(241, "Greece"),
            new AbstractMap.SimpleEntry<>(242, "Morocco"),
            new AbstractMap.SimpleEntry<>(243, "Hungary"),
            new AbstractMap.SimpleEntry<>(244, "Netherlands"),
            new AbstractMap.SimpleEntry<>(245, "Netherlands"),
            new AbstractMap.SimpleEntry<>(246, "Netherlands"),
            new AbstractMap.SimpleEntry<>(247, "Italy"),
            new AbstractMap.SimpleEntry<>(248, "Malta"),
            new AbstractMap.SimpleEntry<>(249, "Malta"),
            new AbstractMap.SimpleEntry<>(250, "Ireland"),
            new AbstractMap.SimpleEntry<>(251, "Iceland"),
            new AbstractMap.SimpleEntry<>(252, "Liechtenstein"),
            new AbstractMap.SimpleEntry<>(253, "Luxembourg"),
            new AbstractMap.SimpleEntry<>(254, "Monaco"),
            new AbstractMap.SimpleEntry<>(255, "Portugal"),
            new AbstractMap.SimpleEntry<>(256, "Malta"),
            new AbstractMap.SimpleEntry<>(257, "Norway"),
            new AbstractMap.SimpleEntry<>(258, "Norway"),
            new AbstractMap.SimpleEntry<>(259, "Norway"),
            new AbstractMap.SimpleEntry<>(261, "Poland"),
            new AbstractMap.SimpleEntry<>(262, "Montenegro"),
            new AbstractMap.SimpleEntry<>(263, "Portugal"),
            new AbstractMap.SimpleEntry<>(264, "Romania"),
            new AbstractMap.SimpleEntry<>(265, "Sweden"),
            new AbstractMap.SimpleEntry<>(266, "Sweden"),
            new AbstractMap.SimpleEntry<>(267, "Slovakia"),
            new AbstractMap.SimpleEntry<>(268, "San Marino"),
            new AbstractMap.SimpleEntry<>(269, "Switzerland"),
            new AbstractMap.SimpleEntry<>(270, "Czech Republic"),
            new AbstractMap.SimpleEntry<>(271, "Turkey"),
            new AbstractMap.SimpleEntry<>(272, "Ukraine"),
            new AbstractMap.SimpleEntry<>(273, "Russia"),
            new AbstractMap.SimpleEntry<>(274, "FYR Macedonia"),
            new AbstractMap.SimpleEntry<>(275, "Latvia"),
            new AbstractMap.SimpleEntry<>(276, "Estonia"),
            new AbstractMap.SimpleEntry<>(277, "Lithuania"),
            new AbstractMap.SimpleEntry<>(278, "Slovenia"),
            new AbstractMap.SimpleEntry<>(279, "Serbia"),
            new AbstractMap.SimpleEntry<>(301, "Anguilla"),
            new AbstractMap.SimpleEntry<>(303, "USA"),
            new AbstractMap.SimpleEntry<>(304, "Antigua Barbuda"),
            new AbstractMap.SimpleEntry<>(305, "Antigua Barbuda"),
            new AbstractMap.SimpleEntry<>(306, "Curacao"),
            new AbstractMap.SimpleEntry<>(307, "Aruba"),
            new AbstractMap.SimpleEntry<>(308, "Bahamas"),
            new AbstractMap.SimpleEntry<>(309, "Bahamas"),
            new AbstractMap.SimpleEntry<>(310, "Bermuda"),
            new AbstractMap.SimpleEntry<>(311, "Bahamas"),
            new AbstractMap.SimpleEntry<>(312, "Belize"),
            new AbstractMap.SimpleEntry<>(314, "Barbados"),
            new AbstractMap.SimpleEntry<>(316, "Canada"),
            new AbstractMap.SimpleEntry<>(319, "Cayman Is"),
            new AbstractMap.SimpleEntry<>(321, "Costa Rica"),
            new AbstractMap.SimpleEntry<>(323, "Cuba"),
            new AbstractMap.SimpleEntry<>(325, "Dominica"),
            new AbstractMap.SimpleEntry<>(327, "Dominican Rep"),
            new AbstractMap.SimpleEntry<>(329, "Guadeloupe"),
            new AbstractMap.SimpleEntry<>(330, "Grenada"),
            new AbstractMap.SimpleEntry<>(331, "Greenland"),
            new AbstractMap.SimpleEntry<>(332, "Guatemala"),
            new AbstractMap.SimpleEntry<>(334, "Honduras"),
            new AbstractMap.SimpleEntry<>(336, "Haiti"),
            new AbstractMap.SimpleEntry<>(338, "USA"),
            new AbstractMap.SimpleEntry<>(339, "Jamaica"),
            new AbstractMap.SimpleEntry<>(341, "St Kitts Nevis"),
            new AbstractMap.SimpleEntry<>(343, "St Lucia"),
            new AbstractMap.SimpleEntry<>(345, "Mexico"),
            new AbstractMap.SimpleEntry<>(347, "Martinique"),
            new AbstractMap.SimpleEntry<>(348, "Montserrat"),
            new AbstractMap.SimpleEntry<>(350, "Nicaragua"),
            new AbstractMap.SimpleEntry<>(351, "Panama"),
            new AbstractMap.SimpleEntry<>(352, "Panama"),
            new AbstractMap.SimpleEntry<>(353, "Panama"),
            new AbstractMap.SimpleEntry<>(354, "Panama"),
            new AbstractMap.SimpleEntry<>(355, "Panama"),
            new AbstractMap.SimpleEntry<>(356, "Panama"),
            new AbstractMap.SimpleEntry<>(357, "Panama"),
            new AbstractMap.SimpleEntry<>(358, "Puerto Rico"),
            new AbstractMap.SimpleEntry<>(359, "El Salvador"),
            new AbstractMap.SimpleEntry<>(361, "St Pierre Miquelon"),
            new AbstractMap.SimpleEntry<>(362, "Trinidad Tobago"),
            new AbstractMap.SimpleEntry<>(364, "Turks Caicos Is"),
            new AbstractMap.SimpleEntry<>(366, "USA"),
            new AbstractMap.SimpleEntry<>(367, "USA"),
            new AbstractMap.SimpleEntry<>(368, "USA"),
            new AbstractMap.SimpleEntry<>(369, "USA"),
            new AbstractMap.SimpleEntry<>(370, "Panama"),
            new AbstractMap.SimpleEntry<>(371, "Panama"),
            new AbstractMap.SimpleEntry<>(372, "Panama"),
            new AbstractMap.SimpleEntry<>(373, "Panama"),
            new AbstractMap.SimpleEntry<>(374, "Panama"),
            new AbstractMap.SimpleEntry<>(375, "St Vincent Grenadines"),
            new AbstractMap.SimpleEntry<>(376, "St Vincent Grenadines"),
            new AbstractMap.SimpleEntry<>(377, "St Vincent Grenadines"),
            new AbstractMap.SimpleEntry<>(378, "British Virgin Is"),
            new AbstractMap.SimpleEntry<>(379, "US Virgin Is"),
            new AbstractMap.SimpleEntry<>(401, "Afghanistan"),
            new AbstractMap.SimpleEntry<>(403, "Saudi Arabia"),
            new AbstractMap.SimpleEntry<>(405, "Bangladesh"),
            new AbstractMap.SimpleEntry<>(408, "Bahrain"),
            new AbstractMap.SimpleEntry<>(410, "Bhutan"),
            new AbstractMap.SimpleEntry<>(412, "China"),
            new AbstractMap.SimpleEntry<>(413, "China"),
            new AbstractMap.SimpleEntry<>(414, "China"),
            new AbstractMap.SimpleEntry<>(416, "Taiwan"),
            new AbstractMap.SimpleEntry<>(417, "Sri Lanka"),
            new AbstractMap.SimpleEntry<>(419, "India"),
            new AbstractMap.SimpleEntry<>(422, "Iran"),
            new AbstractMap.SimpleEntry<>(423, "Azerbaijan"),
            new AbstractMap.SimpleEntry<>(425, "Iraq"),
            new AbstractMap.SimpleEntry<>(428, "Israel"),
            new AbstractMap.SimpleEntry<>(431, "Japan"),
            new AbstractMap.SimpleEntry<>(432, "Japan"),
            new AbstractMap.SimpleEntry<>(434, "Turkmenistan"),
            new AbstractMap.SimpleEntry<>(436, "Kazakhstan"),
            new AbstractMap.SimpleEntry<>(437, "Uzbekistan"),
            new AbstractMap.SimpleEntry<>(438, "Jordan"),
            new AbstractMap.SimpleEntry<>(440, "Korea"),
            new AbstractMap.SimpleEntry<>(441, "Korea"),
            new AbstractMap.SimpleEntry<>(443, "Palestine"),
            new AbstractMap.SimpleEntry<>(445, "DPR Korea"),
            new AbstractMap.SimpleEntry<>(447, "Kuwait"),
            new AbstractMap.SimpleEntry<>(450, "Lebanon"),
            new AbstractMap.SimpleEntry<>(451, "Kyrgyz Republic"),
            new AbstractMap.SimpleEntry<>(453, "Macao"),
            new AbstractMap.SimpleEntry<>(455, "Maldives"),
            new AbstractMap.SimpleEntry<>(457, "Mongolia"),
            new AbstractMap.SimpleEntry<>(459, "Nepal"),
            new AbstractMap.SimpleEntry<>(461, "Oman"),
            new AbstractMap.SimpleEntry<>(463, "Pakistan"),
            new AbstractMap.SimpleEntry<>(466, "Qatar"),
            new AbstractMap.SimpleEntry<>(468, "Syria"),
            new AbstractMap.SimpleEntry<>(470, "UAE"),
            new AbstractMap.SimpleEntry<>(471, "UAE"),
            new AbstractMap.SimpleEntry<>(472, "Tajikistan"),
            new AbstractMap.SimpleEntry<>(473, "Yemen"),
            new AbstractMap.SimpleEntry<>(475, "Yemen"),
            new AbstractMap.SimpleEntry<>(477, "Hong Kong"),
            new AbstractMap.SimpleEntry<>(478, "Bosnia and Herzegovina"),
            new AbstractMap.SimpleEntry<>(501, "Antarctica"),
            new AbstractMap.SimpleEntry<>(503, "Australia"),
            new AbstractMap.SimpleEntry<>(506, "Myanmar"),
            new AbstractMap.SimpleEntry<>(508, "Brunei"),
            new AbstractMap.SimpleEntry<>(510, "Micronesia"),
            new AbstractMap.SimpleEntry<>(511, "Palau"),
            new AbstractMap.SimpleEntry<>(512, "New Zealand"),
            new AbstractMap.SimpleEntry<>(514, "Cambodia"),
            new AbstractMap.SimpleEntry<>(515, "Cambodia"),
            new AbstractMap.SimpleEntry<>(516, "Christmas Is"),
            new AbstractMap.SimpleEntry<>(518, "Cook Is"),
            new AbstractMap.SimpleEntry<>(520, "Fiji"),
            new AbstractMap.SimpleEntry<>(523, "Cocos Is"),
            new AbstractMap.SimpleEntry<>(525, "Indonesia"),
            new AbstractMap.SimpleEntry<>(529, "Kiribati"),
            new AbstractMap.SimpleEntry<>(531, "Laos"),
            new AbstractMap.SimpleEntry<>(533, "Malaysia"),
            new AbstractMap.SimpleEntry<>(536, "N Mariana Is"),
            new AbstractMap.SimpleEntry<>(538, "Marshall Is"),
            new AbstractMap.SimpleEntry<>(540, "New Caledonia"),
            new AbstractMap.SimpleEntry<>(542, "Niue"),
            new AbstractMap.SimpleEntry<>(544, "Nauru"),
            new AbstractMap.SimpleEntry<>(546, "French Polynesia"),
            new AbstractMap.SimpleEntry<>(548, "Philippines"),
            new AbstractMap.SimpleEntry<>(553, "Papua New Guinea"),
            new AbstractMap.SimpleEntry<>(555, "Pitcairn Is"),
            new AbstractMap.SimpleEntry<>(557, "Solomon Is"),
            new AbstractMap.SimpleEntry<>(559, "American Samoa"),
            new AbstractMap.SimpleEntry<>(561, "Samoa"),
            new AbstractMap.SimpleEntry<>(563, "Singapore"),
            new AbstractMap.SimpleEntry<>(564, "Singapore"),
            new AbstractMap.SimpleEntry<>(565, "Singapore"),
            new AbstractMap.SimpleEntry<>(566, "Singapore"),
            new AbstractMap.SimpleEntry<>(567, "Thailand"),
            new AbstractMap.SimpleEntry<>(570, "Tonga"),
            new AbstractMap.SimpleEntry<>(572, "Tuvalu"),
            new AbstractMap.SimpleEntry<>(574, "Vietnam"),
            new AbstractMap.SimpleEntry<>(576, "Vanuatu"),
            new AbstractMap.SimpleEntry<>(577, "Vanuatu"),
            new AbstractMap.SimpleEntry<>(578, "Wallis Futuna Is"),
            new AbstractMap.SimpleEntry<>(601, "South Africa"),
            new AbstractMap.SimpleEntry<>(603, "Angola"),
            new AbstractMap.SimpleEntry<>(605, "Algeria"),
            new AbstractMap.SimpleEntry<>(607, "St Paul Amsterdam Is"),
            new AbstractMap.SimpleEntry<>(608, "Ascension Is"),
            new AbstractMap.SimpleEntry<>(609, "Burundi"),
            new AbstractMap.SimpleEntry<>(610, "Benin"),
            new AbstractMap.SimpleEntry<>(611, "Botswana"),
            new AbstractMap.SimpleEntry<>(612, "Cen Afr Rep"),
            new AbstractMap.SimpleEntry<>(613, "Cameroon"),
            new AbstractMap.SimpleEntry<>(615, "Congo"),
            new AbstractMap.SimpleEntry<>(616, "Comoros"),
            new AbstractMap.SimpleEntry<>(617, "Cape Verde"),
            new AbstractMap.SimpleEntry<>(618, "Antarctica"),
            new AbstractMap.SimpleEntry<>(619, "Ivory Coast"),
            new AbstractMap.SimpleEntry<>(620, "Comoros"),
            new AbstractMap.SimpleEntry<>(621, "Djibouti"),
            new AbstractMap.SimpleEntry<>(622, "Egypt"),
            new AbstractMap.SimpleEntry<>(624, "Ethiopia"),
            new AbstractMap.SimpleEntry<>(625, "Eritrea"),
            new AbstractMap.SimpleEntry<>(626, "Gabon"),
            new AbstractMap.SimpleEntry<>(627, "Ghana"),
            new AbstractMap.SimpleEntry<>(629, "Gambia"),
            new AbstractMap.SimpleEntry<>(630, "Guinea-Bissau"),
            new AbstractMap.SimpleEntry<>(631, "Equ. Guinea"),
            new AbstractMap.SimpleEntry<>(632, "Guinea"),
            new AbstractMap.SimpleEntry<>(633, "Burkina Faso"),
            new AbstractMap.SimpleEntry<>(634, "Kenya"),
            new AbstractMap.SimpleEntry<>(635, "Antarctica"),
            new AbstractMap.SimpleEntry<>(636, "Liberia"),
            new AbstractMap.SimpleEntry<>(637, "Liberia"),
            new AbstractMap.SimpleEntry<>(642, "Libya"),
            new AbstractMap.SimpleEntry<>(644, "Lesotho"),
            new AbstractMap.SimpleEntry<>(645, "Mauritius"),
            new AbstractMap.SimpleEntry<>(647, "Madagascar"),
            new AbstractMap.SimpleEntry<>(649, "Mali"),
            new AbstractMap.SimpleEntry<>(650, "Mozambique"),
            new AbstractMap.SimpleEntry<>(654, "Mauritania"),
            new AbstractMap.SimpleEntry<>(655, "Malawi"),
            new AbstractMap.SimpleEntry<>(656, "Niger"),
            new AbstractMap.SimpleEntry<>(657, "Nigeria"),
            new AbstractMap.SimpleEntry<>(659, "Namibia"),
            new AbstractMap.SimpleEntry<>(660, "Reunion"),
            new AbstractMap.SimpleEntry<>(661, "Rwanda"),
            new AbstractMap.SimpleEntry<>(662, "Sudan"),
            new AbstractMap.SimpleEntry<>(663, "Senegal"),
            new AbstractMap.SimpleEntry<>(664, "Seychelles"),
            new AbstractMap.SimpleEntry<>(665, "St Helena"),
            new AbstractMap.SimpleEntry<>(666, "Somalia"),
            new AbstractMap.SimpleEntry<>(667, "Sierra Leone"),
            new AbstractMap.SimpleEntry<>(668, "Sao Tome Principe"),
            new AbstractMap.SimpleEntry<>(669, "Swaziland"),
            new AbstractMap.SimpleEntry<>(670, "Chad"),
            new AbstractMap.SimpleEntry<>(671, "Togo"),
            new AbstractMap.SimpleEntry<>(672, "Tunisia"),
            new AbstractMap.SimpleEntry<>(674, "Tanzania"),
            new AbstractMap.SimpleEntry<>(675, "Uganda"),
            new AbstractMap.SimpleEntry<>(676, "DR Congo"),
            new AbstractMap.SimpleEntry<>(677, "Tanzania"),
            new AbstractMap.SimpleEntry<>(678, "Zambia"),
            new AbstractMap.SimpleEntry<>(679, "Zimbabwe"),
            new AbstractMap.SimpleEntry<>(701, "Argentina"),
            new AbstractMap.SimpleEntry<>(710, "Brazil"),
            new AbstractMap.SimpleEntry<>(720, "Bolivia"),
            new AbstractMap.SimpleEntry<>(725, "Chile"),
            new AbstractMap.SimpleEntry<>(730, "Colombia"),
            new AbstractMap.SimpleEntry<>(735, "Ecuador"),
            new AbstractMap.SimpleEntry<>(740, "UK"),
            new AbstractMap.SimpleEntry<>(745, "Guiana"),
            new AbstractMap.SimpleEntry<>(750, "Guyana"),
            new AbstractMap.SimpleEntry<>(755, "Paraguay"),
            new AbstractMap.SimpleEntry<>(760, "Peru"),
            new AbstractMap.SimpleEntry<>(765, "Suriname"),
            new AbstractMap.SimpleEntry<>(770, "Uruguay"),
            new AbstractMap.SimpleEntry<>(775, "Venezuela")
            );
}

