package net.osmand.plus.plugins.aistracker;

import java.util.AbstractMap;
import java.util.Map;

public final class AisObjectConstants {
    /* after this time the object is outdated and can be removed: */
    public final static long maxAgeInMinutes = 7;
    /* after this time the (movable) object is lost, the bitmap can be changed: */
    public final static long maxVesselAgeInMinutes = 4;
    public final static int INVALID_HEADING = 511;
    public final static int INVALID_NAV_STATUS = 15;
    public final static int INVALID_MANEUVER_INDICATOR = 0;
    public final static int INVALID_SHIP_TYPE = 0;
    public final static int INVALID_DIMENSION = 0;
    public final static int INVALID_ETA = 0;
    public final static int INVALID_ETA_HOUR = 24;
    public final static int INVALID_ETA_MIN = 60;
    public final static int INVALID_ALTITUDE = 4095;
    public final static int UNSPECIFIED_AID_TYPE = 0;
    public final static double INVALID_COG = 360.0;
    public final static double INVALID_SOG = 1023.0;
    public final static double INVALID_LAT = 91.0;
    public final static double INVALID_LON = 181.0;
    public final static double INVALID_ROT = 128.0;
    public final static double INVALID_DRAUGHT = 0.0;

    public enum AisObjType {
        AIS_VESSEL,
        AIS_VESSEL_SPORT,
        AIS_VESSEL_FAST,
        AIS_VESSEL_PASSENGER,
        AIS_VESSEL_FREIGHT,
        AIS_VESSEL_COMMERCIAL,
        AIS_LANDSTATION,
        AIS_AIRPLANE,
        AIS_SART,
        AIS_ATON, // aids to navigation
        AIS_ATON_VIRTUAL,
        AIS_INVALID
    }
    public static final Map<Integer, String> COUNTRY_CODES = Map.ofEntries(
            new AbstractMap.SimpleEntry<Integer, String>(201, "Albania"),
            new AbstractMap.SimpleEntry<Integer, String>(202, "Andorra"),
            new AbstractMap.SimpleEntry<Integer, String>(203, "Austria"),
            new AbstractMap.SimpleEntry<Integer, String>(204, "Portugal"),
            new AbstractMap.SimpleEntry<Integer, String>(205, "Belgium"),
            new AbstractMap.SimpleEntry<Integer, String>(206, "Belarus"),
            new AbstractMap.SimpleEntry<Integer, String>(207, "Bulgaria"),
            new AbstractMap.SimpleEntry<Integer, String>(208, "Vatican"),
            new AbstractMap.SimpleEntry<Integer, String>(209, "Cyprus"),
            new AbstractMap.SimpleEntry<Integer, String>(210, "Cyprus"),
            new AbstractMap.SimpleEntry<Integer, String>(211, "Germany"),
            new AbstractMap.SimpleEntry<Integer, String>(212, "Cyprus"),
            new AbstractMap.SimpleEntry<Integer, String>(213, "Georgia"),
            new AbstractMap.SimpleEntry<Integer, String>(214, "Moldova"),
            new AbstractMap.SimpleEntry<Integer, String>(215, "Malta"),
            new AbstractMap.SimpleEntry<Integer, String>(216, "Armenia"),
            new AbstractMap.SimpleEntry<Integer, String>(218, "Germany"),
            new AbstractMap.SimpleEntry<Integer, String>(219, "Denmark"),
            new AbstractMap.SimpleEntry<Integer, String>(220, "Denmark"),
            new AbstractMap.SimpleEntry<Integer, String>(224, "Spain"),
            new AbstractMap.SimpleEntry<Integer, String>(225, "Spain"),
            new AbstractMap.SimpleEntry<Integer, String>(226, "France"),
            new AbstractMap.SimpleEntry<Integer, String>(227, "France"),
            new AbstractMap.SimpleEntry<Integer, String>(228, "France"),
            new AbstractMap.SimpleEntry<Integer, String>(229, "Malta"),
            new AbstractMap.SimpleEntry<Integer, String>(230, "Finland"),
            new AbstractMap.SimpleEntry<Integer, String>(231, "Faroe Is"),
            new AbstractMap.SimpleEntry<Integer, String>(232, "United Kingdom"),
            new AbstractMap.SimpleEntry<Integer, String>(233, "United Kingdom"),
            new AbstractMap.SimpleEntry<Integer, String>(234, "United Kingdom"),
            new AbstractMap.SimpleEntry<Integer, String>(235, "United Kingdom"),
            new AbstractMap.SimpleEntry<Integer, String>(236, "Gibraltar"),
            new AbstractMap.SimpleEntry<Integer, String>(237, "Greece"),
            new AbstractMap.SimpleEntry<Integer, String>(238, "Croatia"),
            new AbstractMap.SimpleEntry<Integer, String>(239, "Greece"),
            new AbstractMap.SimpleEntry<Integer, String>(240, "Greece"),
            new AbstractMap.SimpleEntry<Integer, String>(241, "Greece"),
            new AbstractMap.SimpleEntry<Integer, String>(242, "Morocco"),
            new AbstractMap.SimpleEntry<Integer, String>(243, "Hungary"),
            new AbstractMap.SimpleEntry<Integer, String>(244, "Netherlands"),
            new AbstractMap.SimpleEntry<Integer, String>(245, "Netherlands"),
            new AbstractMap.SimpleEntry<Integer, String>(246, "Netherlands"),
            new AbstractMap.SimpleEntry<Integer, String>(247, "Italy"),
            new AbstractMap.SimpleEntry<Integer, String>(248, "Malta"),
            new AbstractMap.SimpleEntry<Integer, String>(249, "Malta"),
            new AbstractMap.SimpleEntry<Integer, String>(250, "Ireland"),
            new AbstractMap.SimpleEntry<Integer, String>(251, "Iceland"),
            new AbstractMap.SimpleEntry<Integer, String>(252, "Liechtenstein"),
            new AbstractMap.SimpleEntry<Integer, String>(253, "Luxembourg"),
            new AbstractMap.SimpleEntry<Integer, String>(254, "Monaco"),
            new AbstractMap.SimpleEntry<Integer, String>(255, "Portugal"),
            new AbstractMap.SimpleEntry<Integer, String>(256, "Malta"),
            new AbstractMap.SimpleEntry<Integer, String>(257, "Norway"),
            new AbstractMap.SimpleEntry<Integer, String>(258, "Norway"),
            new AbstractMap.SimpleEntry<Integer, String>(259, "Norway"),
            new AbstractMap.SimpleEntry<Integer, String>(261, "Poland"),
            new AbstractMap.SimpleEntry<Integer, String>(262, "Montenegro"),
            new AbstractMap.SimpleEntry<Integer, String>(263, "Portugal"),
            new AbstractMap.SimpleEntry<Integer, String>(264, "Romania"),
            new AbstractMap.SimpleEntry<Integer, String>(265, "Sweden"),
            new AbstractMap.SimpleEntry<Integer, String>(266, "Sweden"),
            new AbstractMap.SimpleEntry<Integer, String>(267, "Slovakia"),
            new AbstractMap.SimpleEntry<Integer, String>(268, "San Marino"),
            new AbstractMap.SimpleEntry<Integer, String>(269, "Switzerland"),
            new AbstractMap.SimpleEntry<Integer, String>(270, "Czech Republic"),
            new AbstractMap.SimpleEntry<Integer, String>(271, "Turkey"),
            new AbstractMap.SimpleEntry<Integer, String>(272, "Ukraine"),
            new AbstractMap.SimpleEntry<Integer, String>(273, "Russia"),
            new AbstractMap.SimpleEntry<Integer, String>(274, "FYR Macedonia"),
            new AbstractMap.SimpleEntry<Integer, String>(275, "Latvia"),
            new AbstractMap.SimpleEntry<Integer, String>(276, "Estonia"),
            new AbstractMap.SimpleEntry<Integer, String>(277, "Lithuania"),
            new AbstractMap.SimpleEntry<Integer, String>(278, "Slovenia"),
            new AbstractMap.SimpleEntry<Integer, String>(279, "Serbia"),
            new AbstractMap.SimpleEntry<Integer, String>(301, "Anguilla"),
            new AbstractMap.SimpleEntry<Integer, String>(303, "USA"),
            new AbstractMap.SimpleEntry<Integer, String>(304, "Antigua Barbuda"),
            new AbstractMap.SimpleEntry<Integer, String>(305, "Antigua Barbuda"),
            new AbstractMap.SimpleEntry<Integer, String>(306, "Curacao"),
            new AbstractMap.SimpleEntry<Integer, String>(307, "Aruba"),
            new AbstractMap.SimpleEntry<Integer, String>(308, "Bahamas"),
            new AbstractMap.SimpleEntry<Integer, String>(309, "Bahamas"),
            new AbstractMap.SimpleEntry<Integer, String>(310, "Bermuda"),
            new AbstractMap.SimpleEntry<Integer, String>(311, "Bahamas"),
            new AbstractMap.SimpleEntry<Integer, String>(312, "Belize"),
            new AbstractMap.SimpleEntry<Integer, String>(314, "Barbados"),
            new AbstractMap.SimpleEntry<Integer, String>(316, "Canada"),
            new AbstractMap.SimpleEntry<Integer, String>(319, "Cayman Is"),
            new AbstractMap.SimpleEntry<Integer, String>(321, "Costa Rica"),
            new AbstractMap.SimpleEntry<Integer, String>(323, "Cuba"),
            new AbstractMap.SimpleEntry<Integer, String>(325, "Dominica"),
            new AbstractMap.SimpleEntry<Integer, String>(327, "Dominican Rep"),
            new AbstractMap.SimpleEntry<Integer, String>(329, "Guadeloupe"),
            new AbstractMap.SimpleEntry<Integer, String>(330, "Grenada"),
            new AbstractMap.SimpleEntry<Integer, String>(331, "Greenland"),
            new AbstractMap.SimpleEntry<Integer, String>(332, "Guatemala"),
            new AbstractMap.SimpleEntry<Integer, String>(334, "Honduras"),
            new AbstractMap.SimpleEntry<Integer, String>(336, "Haiti"),
            new AbstractMap.SimpleEntry<Integer, String>(338, "USA"),
            new AbstractMap.SimpleEntry<Integer, String>(339, "Jamaica"),
            new AbstractMap.SimpleEntry<Integer, String>(341, "St Kitts Nevis"),
            new AbstractMap.SimpleEntry<Integer, String>(343, "St Lucia"),
            new AbstractMap.SimpleEntry<Integer, String>(345, "Mexico"),
            new AbstractMap.SimpleEntry<Integer, String>(347, "Martinique"),
            new AbstractMap.SimpleEntry<Integer, String>(348, "Montserrat"),
            new AbstractMap.SimpleEntry<Integer, String>(350, "Nicaragua"),
            new AbstractMap.SimpleEntry<Integer, String>(351, "Panama"),
            new AbstractMap.SimpleEntry<Integer, String>(352, "Panama"),
            new AbstractMap.SimpleEntry<Integer, String>(353, "Panama"),
            new AbstractMap.SimpleEntry<Integer, String>(354, "Panama"),
            new AbstractMap.SimpleEntry<Integer, String>(355, "Panama"),
            new AbstractMap.SimpleEntry<Integer, String>(356, "Panama"),
            new AbstractMap.SimpleEntry<Integer, String>(357, "Panama"),
            new AbstractMap.SimpleEntry<Integer, String>(358, "Puerto Rico"),
            new AbstractMap.SimpleEntry<Integer, String>(359, "El Salvador"),
            new AbstractMap.SimpleEntry<Integer, String>(361, "St Pierre Miquelon"),
            new AbstractMap.SimpleEntry<Integer, String>(362, "Trinidad Tobago"),
            new AbstractMap.SimpleEntry<Integer, String>(364, "Turks Caicos Is"),
            new AbstractMap.SimpleEntry<Integer, String>(366, "USA"),
            new AbstractMap.SimpleEntry<Integer, String>(367, "USA"),
            new AbstractMap.SimpleEntry<Integer, String>(368, "USA"),
            new AbstractMap.SimpleEntry<Integer, String>(369, "USA"),
            new AbstractMap.SimpleEntry<Integer, String>(370, "Panama"),
            new AbstractMap.SimpleEntry<Integer, String>(371, "Panama"),
            new AbstractMap.SimpleEntry<Integer, String>(372, "Panama"),
            new AbstractMap.SimpleEntry<Integer, String>(373, "Panama"),
            new AbstractMap.SimpleEntry<Integer, String>(374, "Panama"),
            new AbstractMap.SimpleEntry<Integer, String>(375, "St Vincent Grenadines"),
            new AbstractMap.SimpleEntry<Integer, String>(376, "St Vincent Grenadines"),
            new AbstractMap.SimpleEntry<Integer, String>(377, "St Vincent Grenadines"),
            new AbstractMap.SimpleEntry<Integer, String>(378, "British Virgin Is"),
            new AbstractMap.SimpleEntry<Integer, String>(379, "US Virgin Is"),
            new AbstractMap.SimpleEntry<Integer, String>(401, "Afghanistan"),
            new AbstractMap.SimpleEntry<Integer, String>(403, "Saudi Arabia"),
            new AbstractMap.SimpleEntry<Integer, String>(405, "Bangladesh"),
            new AbstractMap.SimpleEntry<Integer, String>(408, "Bahrain"),
            new AbstractMap.SimpleEntry<Integer, String>(410, "Bhutan"),
            new AbstractMap.SimpleEntry<Integer, String>(412, "China"),
            new AbstractMap.SimpleEntry<Integer, String>(413, "China"),
            new AbstractMap.SimpleEntry<Integer, String>(414, "China"),
            new AbstractMap.SimpleEntry<Integer, String>(416, "Taiwan"),
            new AbstractMap.SimpleEntry<Integer, String>(417, "Sri Lanka"),
            new AbstractMap.SimpleEntry<Integer, String>(419, "India"),
            new AbstractMap.SimpleEntry<Integer, String>(422, "Iran"),
            new AbstractMap.SimpleEntry<Integer, String>(423, "Azerbaijan"),
            new AbstractMap.SimpleEntry<Integer, String>(425, "Iraq"),
            new AbstractMap.SimpleEntry<Integer, String>(428, "Israel"),
            new AbstractMap.SimpleEntry<Integer, String>(431, "Japan"),
            new AbstractMap.SimpleEntry<Integer, String>(432, "Japan"),
            new AbstractMap.SimpleEntry<Integer, String>(434, "Turkmenistan"),
            new AbstractMap.SimpleEntry<Integer, String>(436, "Kazakhstan"),
            new AbstractMap.SimpleEntry<Integer, String>(437, "Uzbekistan"),
            new AbstractMap.SimpleEntry<Integer, String>(438, "Jordan"),
            new AbstractMap.SimpleEntry<Integer, String>(440, "Korea"),
            new AbstractMap.SimpleEntry<Integer, String>(441, "Korea"),
            new AbstractMap.SimpleEntry<Integer, String>(443, "Palestine"),
            new AbstractMap.SimpleEntry<Integer, String>(445, "DPR Korea"),
            new AbstractMap.SimpleEntry<Integer, String>(447, "Kuwait"),
            new AbstractMap.SimpleEntry<Integer, String>(450, "Lebanon"),
            new AbstractMap.SimpleEntry<Integer, String>(451, "Kyrgyz Republic"),
            new AbstractMap.SimpleEntry<Integer, String>(453, "Macao"),
            new AbstractMap.SimpleEntry<Integer, String>(455, "Maldives"),
            new AbstractMap.SimpleEntry<Integer, String>(457, "Mongolia"),
            new AbstractMap.SimpleEntry<Integer, String>(459, "Nepal"),
            new AbstractMap.SimpleEntry<Integer, String>(461, "Oman"),
            new AbstractMap.SimpleEntry<Integer, String>(463, "Pakistan"),
            new AbstractMap.SimpleEntry<Integer, String>(466, "Qatar"),
            new AbstractMap.SimpleEntry<Integer, String>(468, "Syria"),
            new AbstractMap.SimpleEntry<Integer, String>(470, "UAE"),
            new AbstractMap.SimpleEntry<Integer, String>(471, "UAE"),
            new AbstractMap.SimpleEntry<Integer, String>(472, "Tajikistan"),
            new AbstractMap.SimpleEntry<Integer, String>(473, "Yemen"),
            new AbstractMap.SimpleEntry<Integer, String>(475, "Yemen"),
            new AbstractMap.SimpleEntry<Integer, String>(477, "Hong Kong"),
            new AbstractMap.SimpleEntry<Integer, String>(478, "Bosnia and Herzegovina"),
            new AbstractMap.SimpleEntry<Integer, String>(501, "Antarctica"),
            new AbstractMap.SimpleEntry<Integer, String>(503, "Australia"),
            new AbstractMap.SimpleEntry<Integer, String>(506, "Myanmar"),
            new AbstractMap.SimpleEntry<Integer, String>(508, "Brunei"),
            new AbstractMap.SimpleEntry<Integer, String>(510, "Micronesia"),
            new AbstractMap.SimpleEntry<Integer, String>(511, "Palau"),
            new AbstractMap.SimpleEntry<Integer, String>(512, "New Zealand"),
            new AbstractMap.SimpleEntry<Integer, String>(514, "Cambodia"),
            new AbstractMap.SimpleEntry<Integer, String>(515, "Cambodia"),
            new AbstractMap.SimpleEntry<Integer, String>(516, "Christmas Is"),
            new AbstractMap.SimpleEntry<Integer, String>(518, "Cook Is"),
            new AbstractMap.SimpleEntry<Integer, String>(520, "Fiji"),
            new AbstractMap.SimpleEntry<Integer, String>(523, "Cocos Is"),
            new AbstractMap.SimpleEntry<Integer, String>(525, "Indonesia"),
            new AbstractMap.SimpleEntry<Integer, String>(529, "Kiribati"),
            new AbstractMap.SimpleEntry<Integer, String>(531, "Laos"),
            new AbstractMap.SimpleEntry<Integer, String>(533, "Malaysia"),
            new AbstractMap.SimpleEntry<Integer, String>(536, "N Mariana Is"),
            new AbstractMap.SimpleEntry<Integer, String>(538, "Marshall Is"),
            new AbstractMap.SimpleEntry<Integer, String>(540, "New Caledonia"),
            new AbstractMap.SimpleEntry<Integer, String>(542, "Niue"),
            new AbstractMap.SimpleEntry<Integer, String>(544, "Nauru"),
            new AbstractMap.SimpleEntry<Integer, String>(546, "French Polynesia"),
            new AbstractMap.SimpleEntry<Integer, String>(548, "Philippines"),
            new AbstractMap.SimpleEntry<Integer, String>(553, "Papua New Guinea"),
            new AbstractMap.SimpleEntry<Integer, String>(555, "Pitcairn Is"),
            new AbstractMap.SimpleEntry<Integer, String>(557, "Solomon Is"),
            new AbstractMap.SimpleEntry<Integer, String>(559, "American Samoa"),
            new AbstractMap.SimpleEntry<Integer, String>(561, "Samoa"),
            new AbstractMap.SimpleEntry<Integer, String>(563, "Singapore"),
            new AbstractMap.SimpleEntry<Integer, String>(564, "Singapore"),
            new AbstractMap.SimpleEntry<Integer, String>(565, "Singapore"),
            new AbstractMap.SimpleEntry<Integer, String>(566, "Singapore"),
            new AbstractMap.SimpleEntry<Integer, String>(567, "Thailand"),
            new AbstractMap.SimpleEntry<Integer, String>(570, "Tonga"),
            new AbstractMap.SimpleEntry<Integer, String>(572, "Tuvalu"),
            new AbstractMap.SimpleEntry<Integer, String>(574, "Vietnam"),
            new AbstractMap.SimpleEntry<Integer, String>(576, "Vanuatu"),
            new AbstractMap.SimpleEntry<Integer, String>(577, "Vanuatu"),
            new AbstractMap.SimpleEntry<Integer, String>(578, "Wallis Futuna Is"),
            new AbstractMap.SimpleEntry<Integer, String>(601, "South Africa"),
            new AbstractMap.SimpleEntry<Integer, String>(603, "Angola"),
            new AbstractMap.SimpleEntry<Integer, String>(605, "Algeria"),
            new AbstractMap.SimpleEntry<Integer, String>(607, "St Paul Amsterdam Is"),
            new AbstractMap.SimpleEntry<Integer, String>(608, "Ascension Is"),
            new AbstractMap.SimpleEntry<Integer, String>(609, "Burundi"),
            new AbstractMap.SimpleEntry<Integer, String>(610, "Benin"),
            new AbstractMap.SimpleEntry<Integer, String>(611, "Botswana"),
            new AbstractMap.SimpleEntry<Integer, String>(612, "Cen Afr Rep"),
            new AbstractMap.SimpleEntry<Integer, String>(613, "Cameroon"),
            new AbstractMap.SimpleEntry<Integer, String>(615, "Congo"),
            new AbstractMap.SimpleEntry<Integer, String>(616, "Comoros"),
            new AbstractMap.SimpleEntry<Integer, String>(617, "Cape Verde"),
            new AbstractMap.SimpleEntry<Integer, String>(618, "Antarctica"),
            new AbstractMap.SimpleEntry<Integer, String>(619, "Ivory Coast"),
            new AbstractMap.SimpleEntry<Integer, String>(620, "Comoros"),
            new AbstractMap.SimpleEntry<Integer, String>(621, "Djibouti"),
            new AbstractMap.SimpleEntry<Integer, String>(622, "Egypt"),
            new AbstractMap.SimpleEntry<Integer, String>(624, "Ethiopia"),
            new AbstractMap.SimpleEntry<Integer, String>(625, "Eritrea"),
            new AbstractMap.SimpleEntry<Integer, String>(626, "Gabon"),
            new AbstractMap.SimpleEntry<Integer, String>(627, "Ghana"),
            new AbstractMap.SimpleEntry<Integer, String>(629, "Gambia"),
            new AbstractMap.SimpleEntry<Integer, String>(630, "Guinea-Bissau"),
            new AbstractMap.SimpleEntry<Integer, String>(631, "Equ. Guinea"),
            new AbstractMap.SimpleEntry<Integer, String>(632, "Guinea"),
            new AbstractMap.SimpleEntry<Integer, String>(633, "Burkina Faso"),
            new AbstractMap.SimpleEntry<Integer, String>(634, "Kenya"),
            new AbstractMap.SimpleEntry<Integer, String>(635, "Antarctica"),
            new AbstractMap.SimpleEntry<Integer, String>(636, "Liberia"),
            new AbstractMap.SimpleEntry<Integer, String>(637, "Liberia"),
            new AbstractMap.SimpleEntry<Integer, String>(642, "Libya"),
            new AbstractMap.SimpleEntry<Integer, String>(644, "Lesotho"),
            new AbstractMap.SimpleEntry<Integer, String>(645, "Mauritius"),
            new AbstractMap.SimpleEntry<Integer, String>(647, "Madagascar"),
            new AbstractMap.SimpleEntry<Integer, String>(649, "Mali"),
            new AbstractMap.SimpleEntry<Integer, String>(650, "Mozambique"),
            new AbstractMap.SimpleEntry<Integer, String>(654, "Mauritania"),
            new AbstractMap.SimpleEntry<Integer, String>(655, "Malawi"),
            new AbstractMap.SimpleEntry<Integer, String>(656, "Niger"),
            new AbstractMap.SimpleEntry<Integer, String>(657, "Nigeria"),
            new AbstractMap.SimpleEntry<Integer, String>(659, "Namibia"),
            new AbstractMap.SimpleEntry<Integer, String>(660, "Reunion"),
            new AbstractMap.SimpleEntry<Integer, String>(661, "Rwanda"),
            new AbstractMap.SimpleEntry<Integer, String>(662, "Sudan"),
            new AbstractMap.SimpleEntry<Integer, String>(663, "Senegal"),
            new AbstractMap.SimpleEntry<Integer, String>(664, "Seychelles"),
            new AbstractMap.SimpleEntry<Integer, String>(665, "St Helena"),
            new AbstractMap.SimpleEntry<Integer, String>(666, "Somalia"),
            new AbstractMap.SimpleEntry<Integer, String>(667, "Sierra Leone"),
            new AbstractMap.SimpleEntry<Integer, String>(668, "Sao Tome Principe"),
            new AbstractMap.SimpleEntry<Integer, String>(669, "Swaziland"),
            new AbstractMap.SimpleEntry<Integer, String>(670, "Chad"),
            new AbstractMap.SimpleEntry<Integer, String>(671, "Togo"),
            new AbstractMap.SimpleEntry<Integer, String>(672, "Tunisia"),
            new AbstractMap.SimpleEntry<Integer, String>(674, "Tanzania"),
            new AbstractMap.SimpleEntry<Integer, String>(675, "Uganda"),
            new AbstractMap.SimpleEntry<Integer, String>(676, "DR Congo"),
            new AbstractMap.SimpleEntry<Integer, String>(677, "Tanzania"),
            new AbstractMap.SimpleEntry<Integer, String>(678, "Zambia"),
            new AbstractMap.SimpleEntry<Integer, String>(679, "Zimbabwe"),
            new AbstractMap.SimpleEntry<Integer, String>(701, "Argentina"),
            new AbstractMap.SimpleEntry<Integer, String>(710, "Brazil"),
            new AbstractMap.SimpleEntry<Integer, String>(720, "Bolivia"),
            new AbstractMap.SimpleEntry<Integer, String>(725, "Chile"),
            new AbstractMap.SimpleEntry<Integer, String>(730, "Colombia"),
            new AbstractMap.SimpleEntry<Integer, String>(735, "Ecuador"),
            new AbstractMap.SimpleEntry<Integer, String>(740, "UK"),
            new AbstractMap.SimpleEntry<Integer, String>(745, "Guiana"),
            new AbstractMap.SimpleEntry<Integer, String>(750, "Guyana"),
            new AbstractMap.SimpleEntry<Integer, String>(755, "Paraguay"),
            new AbstractMap.SimpleEntry<Integer, String>(760, "Peru"),
            new AbstractMap.SimpleEntry<Integer, String>(765, "Suriname"),
            new AbstractMap.SimpleEntry<Integer, String>(770, "Uruguay"),
            new AbstractMap.SimpleEntry<Integer, String>(775, "Venezuela")
            );
}

