name: 🐞 Bug Report
description: Report a bug in OsmAnd
labels: [ ]
assignees: [ ]
body:
    -   type: markdown
        attributes:
            value: |
                Oh hi there! 😄

                To expedite issue processing please search open and closed issues before submitting a new one.
                Existing issues often contain information about workarounds, resolution, or progress updates.

                GitHub is our main development tool for our developers. There are hundreds of requests a month and there are relatively few developers.
                So by opening an issue, please know that your issue will be sent out to all developers and acknowledge that it could be closed without explanation or with just a brief message.
                Comments on the closed issues are also sent to all developers, so you definitely will be heard.
                However, there is no guarantee that a developer will pick up the issue to work on it.

                Please be sure to read our [FAQ](https://osmand.net/docs/user/troubleshooting/) before creating an issue here.

                The best way to get help about is to provide as many details as possible and follow the below template
                so that we can try to **reproduce** your issue.
    -   type: textarea
        id: describe-the-bug
        attributes:
            label: Describe the bug (required)
            description: Please provide a brief summary of the issue and provide a summarised description in the title above.
        validations:
            required: true
    -   type: textarea
        id: steps-to-reproduce
        attributes:
            label: Describe how the bug can be reproduced (required)
            description: Please provide a brief summary how the bug can be reproduced.
        validations:
            required: true
    -   type: textarea
        id: actual-result
        attributes:
            label: Describe the actual result (required)
            description: Please provide a brief summary of the actual result.
        validations:
            required: true
    -   type: textarea
        id: expected-result
        attributes:
            label: Describe the expected result (required)
            description: Please provide a brief summary of the expected result.
        validations:
            required: true
    -   type: textarea
        id: environment
        attributes:
            label: Your Environment (required)
            description: |
                Include as many relevant details about the environment you experienced the bug in.
                If possible you may also provide [Crash-Logs](https://osmand.net/docs/user/troubleshooting/crash-logs/),
                but be warned that **crash logs may contain sensitive information** you may not want to share publicly!
            value: |
                **WARNING** Crash-Logs **MAY** contain information you deem sensitive.
                Review this **CAREFULLY** before posting your issue!
                
                ```
                OsmAnd Version:
                Android/iOS version:
                Device model:
                Crash-Logs: ?
                ```
        validations:
            required: true

