package net.osmand.plus.dashboard;

public enum DashboardType {
	CONFIGURE_MAP,
	DASHBOARD,
	OVERLAY_MAP,
	UNDERLAY_MAP,
	MAPILLARY,
	CONTOUR_LINES,
	OSM_NOTES,
	WIKIPEDIA,
	TERRAIN,
	RELIEF_3D,
	CYCLE_ROUTES,
	HIKING_ROUTES,
	TRAVEL_ROUTES,
	TRANSPORT_LINES,
	WEATHER,
	WEATHER_LAYER,
	WEATHER_CONTOURS,
	NAUTICAL_DEPTH,
	MTB_ROUTES,
	ALPINE_HIKING
}
