package net.osmand.plus.dashboard;

public enum DashboardType {
	CONFIGURE_MAP,
	DASHBOARD,
	OVERLAY_MAP,
	UNDERLAY_MAP,
	MAPILLARY,
	CONTOUR_LINES,
	OSM_NOTES,
	WIKIPEDIA,
	TERRAIN,
	RELIEF_3D,
	TRAVEL_ROUTES,
	TRANSPORT_LINES,
	WEATHER,
	WEATHER_LAYER,
	WEATHER_CONTOURS,
	NAUTICAL_DEPTH,
	MAP_ROUTES,
	RENDERING_CLASS,
	COORDINATE_GRID
}
