package net.osmand.plus.settings.backend;

public enum ExportSettingsType {
	PROFILE,
	QUICK_ACTIONS,
	POI_TYPES,
	MAP_SOURCES,
	CUSTOM_RENDER_STYLE,
	CUSTOM_ROUTING,
	AVOID_ROADS,
	TRACKS,
	MULTIMEDIA_NOTES,
	GLOBAL,
	OSM_NOTES,
	OSM_EDITS,
	OFFLINE_MAPS
}
