package net.osmand.plus.search.listitems;

public enum QuickSearchListItemType {
	SEARCH_RESULT,
	HEADER,
	BUTTON,
	SEARCH_MORE,
	SEARCH_ON_WEB,
	BANNER,
	FREE_VERSION_BANNER,
	SELECT_ALL,
	TOP_SHADOW,
	BOTTOM_SHADOW,
	DISABLED_HISTORY,
	CARD_DIVIDER
}
