package net.osmand.plus.plugins.antplus.antdevices;

public enum AntDeviceConnectionResult {
	SUCCESS,
	USER_CANCELLED,
	CHANNEL_NOT_AVAILABLE,
	OTHER_FAILURE,
	DEPENDENCY_NOT_INSTALLED,
	DEVICE_ALREADY_IN_USE,
	SEARCH_TIMEOUT,
	ALREADY_SUBSCRIBED,
	BAD_PARAMS,
	ADAPTER_NOT_DETECTED,
	UNRECOGNIZED
}
