package net.osmand.plus.backup.trash;

public enum ScreenItemType {
	ALERT_CARD,
	BACKUP_STATUS_HEADER,
	CARD_DIVIDER,
	HEADER,
	TRASH_ITEM,
	DIVIDER,
	EMPTY_TRASH_BANNER,
	CARD_BOTTOM_SHADOW,
	SPACE,
	UNKNOWN
}
