apply plugin: 'com.android.library'
apply plugin: 'ivy-publish'
apply from: 'build-common.gradle'
apply from: rootProject.file("versions.gradle")

apply plugin: 'kotlin-parcelize'
apply plugin: 'org.jetbrains.kotlin.plugin.compose'

android {

	defaultConfig {
		minSdkVersion osmand_minSdk
	}

	lintOptions {
		tasks.lint.enabled = false
	}

	compileOptions {
		sourceCompatibility = JavaVersion.VERSION_17
		targetCompatibility = JavaVersion.VERSION_17
	}

	buildFeatures {
		aidl true
		buildConfig true
		resValues true
		compose true
	}

	sourceSets {
		main {
			manifest.srcFile "AndroidManifest-library.xml"
			java.srcDirs = ["src", "src-gms", "src-google"]
		}
	}

	productFlavors {
		// CoreVersion
		// Build that doesn't include 3D OpenGL
		legacy {
			dimension "coreversion"
			resValue "string", "app_edition", ""
		}
	}
}

androidComponents {
	onVariants(selector().all()) { variant ->
		def taskName = variant.name.capitalize()
		def dependOn = { String name, Object... deps ->
			tasks.matching { it.name == name }.configureEach { it.dependsOn(deps) }
		}
		dependOn("merge${taskName}Assets", copyProjDb, collectFonts, copyPoiCategories, copyRouteActivities, copyColorPalettes,
				copyBundledAssets, copy3DModels, collectVoiceAssets, downloadStarsDb, downloadWorldMiniBasemap)
		dependOn("map${taskName}SourceSetPaths", copyIcons)
		dependOn("process${taskName}NavigationResources", copyIcons)
		dependOn("package${taskName}Resources", copyIcons)
		dependOn("generate${taskName}Resources", copyIcons)
		dependOn("compile${taskName}JavaWithJavac", collectExternalResources, buildOsmAndCore, cleanupDuplicatesInCore)
	}
}

version = System.getenv("OSMAND_BINARIES_IVY_REVISION") ?: "master-snapshot"
project.afterEvaluate {
	publishing {
		repositories {
			ivy {
				url = System.getenv("OSMAND_BINARIES_IVY_ROOT") ?: "./"
			}
		}
		publications {
			aar(IvyPublication) {
				artifact bundleLegacyFatDebugAar {
					archiveClassifier = 'debug'
				}
				artifact bundleLegacyFatReleaseAar {
					archiveClassifier = 'release'
				}
			}
		}
	}
}

