package net.osmand.plus.download;

import androidx.annotation.NonNull;

import net.osmand.plus.download.DownloadSearchUIModelTest.ReportRow;
import net.osmand.plus.download.DownloadSearchUIModelTest.ReportScreen;
import net.osmand.util.Algorithms;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

/**
 * Renders the search results collected by {@link DownloadSearchUIModelTest} as a standalone page,
 * so the "Maps & Resources" search screens can be reviewed without taking screenshots.
 */
class DownloadSearchScreenReport {

	@NonNull
	static String build(@NonNull List<ReportScreen> screens) {
		Map<String, List<ReportScreen>> byCatalog = new LinkedHashMap<>();
		for (ReportScreen screen : screens) {
			byCatalog.computeIfAbsent(screen.catalog, key -> new ArrayList<>()).add(screen);
		}
		String date = new SimpleDateFormat("yyyy-MM-dd HH:mm", Locale.US).format(new Date());

		StringBuilder html = new StringBuilder();
		html.append("<meta charset=\"utf-8\">\n")
				.append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n")
				.append("<title>Maps &amp; Resources search results</title>\n")
				.append("<style>\n").append(css()).append("</style>\n");
		html.append("<header class=\"page\"><h1>Maps &amp; Resources search results</h1>")
				.append("<p>Rows produced by the search screen for every query below. Generated by ")
				.append("DownloadSearchUIModelTest on ").append(date).append(".</p></header>\n");

		for (Map.Entry<String, List<ReportScreen>> entry : byCatalog.entrySet()) {
			html.append("<section>\n<h2>").append(escape(entry.getKey())).append("</h2>\n")
					.append("<div class=\"screens\">\n");
			for (ReportScreen screen : entry.getValue()) {
				appendScreen(html, screen);
			}
			html.append("</div>\n</section>\n");
		}
		return html.toString();
	}

	private static void appendScreen(@NonNull StringBuilder html, @NonNull ReportScreen screen) {
		html.append("<article class=\"screen\">\n<header><code>").append(escape(screen.query)).append("</code>");
		if (!Algorithms.isEmpty(screen.note)) {
			html.append("<p>").append(escape(screen.note)).append("</p>");
		}
		html.append("</header>\n<ul>\n");
		if (screen.rows.isEmpty()) {
			html.append("<li class=\"empty\">Nothing found</li>\n");
		}
		for (ReportRow row : screen.rows) {
			if (row.header != null) {
				html.append("<li class=\"head\">").append(escape(row.header)).append("</li>\n");
			} else {
				html.append("<li><span class=\"title\">").append(escape(row.title)).append("</span>");
				if (row.subtitle != null) {
					html.append("<span class=\"sub\">").append(escape(row.subtitle)).append("</span>");
				}
				html.append("</li>\n");
			}
		}
		html.append("</ul>\n</article>\n");
	}

	@NonNull
	private static String css() {
		return ":root{--bg:#eff1f3;--card:#fff;--sunken:#e4e7ea;--ink:#1a1d21;--muted:#5f656c;"
				+ "--line:#dce0e4;--accent:#d9740a}\n"
				+ "@media (prefers-color-scheme:dark){:root{--bg:#131619;--card:#1c2025;--sunken:#23282e;"
				+ "--ink:#e7eaed;--muted:#969da5;--line:#2a2f35;--accent:#ff9f35}}\n"
				+ "*{box-sizing:border-box}\n"
				+ "body{margin:0;padding:32px 24px 64px;background:var(--bg);color:var(--ink);"
				+ "font:16px/1.55 -apple-system,'Segoe UI',Roboto,sans-serif}\n"
				+ ".page{max-width:900px;margin:0 auto 8px}\n"
				+ ".page h1{font-size:28px;margin:0 0 6px}\n"
				+ ".page p{margin:0;color:var(--muted);font-size:15px}\n"
				+ "section{max-width:1200px;margin:36px auto 0}\n"
				+ "h2{font-size:19px;margin:0 0 14px;padding-bottom:8px;border-bottom:1px solid var(--line)}\n"
				+ ".screens{display:grid;grid-template-columns:repeat(auto-fill,minmax(330px,1fr));gap:18px}\n"
				+ ".screen{background:var(--card);border:1px solid var(--line);border-radius:8px;overflow:hidden}\n"
				+ ".screen>header{padding:12px 16px;border-bottom:1px solid var(--line)}\n"
				+ ".screen>header code{font-size:14px;font-weight:600;color:var(--accent)}\n"
				+ ".screen>header code::before{content:'search: ';color:var(--muted);font-weight:400}\n"
				+ ".screen>header p{margin:4px 0 0;font-size:13.5px;color:var(--muted)}\n"
				+ "ul{list-style:none;margin:0;padding:0}\n"
				+ "li{display:flex;flex-direction:column;padding:8px 16px;border-bottom:1px solid var(--line)}\n"
				+ "li:last-child{border-bottom:0}\n"
				+ "li.head{background:var(--sunken);color:var(--muted);font-size:11.5px;font-weight:600;"
				+ "letter-spacing:.13em;text-transform:uppercase;padding:6px 16px}\n"
				+ "li.empty{color:var(--muted);font-style:italic;font-size:14.5px}\n"
				+ ".title{font-size:15.5px}\n"
				+ ".sub{font-size:13.5px;color:var(--muted)}\n";
	}

	@NonNull
	private static String escape(@NonNull String text) {
		return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
				.replace("\"", "&quot;");
	}
}
