# Include tools definitions
include ../Makefile.vars

# Include project files
LOCAL_PATH = .
include Common.mk

# Set library name
LIBNAME = $(LIBRARY_PREFIX)png
LIBTYPE = $(STATICLIB_EXT)

# Finally, include generic rules
include ../Makefile.rules
