/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.osmand.core.jni;

public class BinaryMapRasterBitmapTileProvider extends IMapRasterBitmapTileProvider {
  private long swigCPtr;
  private boolean swigCMemOwnDerived;

  protected BinaryMapRasterBitmapTileProvider(long cPtr, boolean cMemoryOwn) {
    super(OsmAndCoreJNI.BinaryMapRasterBitmapTileProvider_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BinaryMapRasterBitmapTileProvider obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        OsmAndCoreJNI.delete_BinaryMapRasterBitmapTileProvider(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public BinaryMapPrimitivesProvider getPrimitivesProvider() {
    long cPtr = OsmAndCoreJNI.BinaryMapRasterBitmapTileProvider_primitivesProvider_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BinaryMapPrimitivesProvider(cPtr, true);
  }

  public float getTileDensityFactor() {
    return OsmAndCoreJNI.BinaryMapRasterBitmapTileProvider_getTileDensityFactor(swigCPtr, this);
  }

  public long getTileSize() {
    return OsmAndCoreJNI.BinaryMapRasterBitmapTileProvider_getTileSize(swigCPtr, this);
  }

  public boolean obtainData(TileId tileId, ZoomLevel zoom, MapTiledData outTiledData, SWIGTYPE_p_OsmAnd__IQueryController queryController) {
    return OsmAndCoreJNI.BinaryMapRasterBitmapTileProvider_obtainData__SWIG_0(swigCPtr, this, TileId.getCPtr(tileId), tileId, zoom.swigValue(), MapTiledData.getCPtr(outTiledData), outTiledData, SWIGTYPE_p_OsmAnd__IQueryController.getCPtr(queryController));
  }

  public boolean obtainData(TileId tileId, ZoomLevel zoom, MapTiledData outTiledData) {
    return OsmAndCoreJNI.BinaryMapRasterBitmapTileProvider_obtainData__SWIG_1(swigCPtr, this, TileId.getCPtr(tileId), tileId, zoom.swigValue(), MapTiledData.getCPtr(outTiledData), outTiledData);
  }

  public boolean obtainData(TileId tileId, ZoomLevel zoom, MapTiledData outTiledData, SWIGTYPE_p_BinaryMapRasterBitmapTileProvider_Metrics__Metric_obtainData metric, SWIGTYPE_p_OsmAnd__IQueryController queryController) {
    return OsmAndCoreJNI.BinaryMapRasterBitmapTileProvider_obtainData__SWIG_2(swigCPtr, this, TileId.getCPtr(tileId), tileId, zoom.swigValue(), MapTiledData.getCPtr(outTiledData), outTiledData, SWIGTYPE_p_BinaryMapRasterBitmapTileProvider_Metrics__Metric_obtainData.getCPtr(metric), SWIGTYPE_p_OsmAnd__IQueryController.getCPtr(queryController));
  }

  public ZoomLevel getMinZoom() {
    return ZoomLevel.swigToEnum(OsmAndCoreJNI.BinaryMapRasterBitmapTileProvider_getMinZoom(swigCPtr, this));
  }

  public ZoomLevel getMaxZoom() {
    return ZoomLevel.swigToEnum(OsmAndCoreJNI.BinaryMapRasterBitmapTileProvider_getMaxZoom(swigCPtr, this));
  }

}
