/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.osmand.core.jni;

public class BoolPtr {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected BoolPtr(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BoolPtr obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OsmAndCoreJNI.delete_BoolPtr(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BoolPtr() {
    this(OsmAndCoreJNI.new_BoolPtr(), true);
  }

  public void assign(boolean value) {
    OsmAndCoreJNI.BoolPtr_assign(swigCPtr, this, value);
  }

  public boolean value() {
    return OsmAndCoreJNI.BoolPtr_value(swigCPtr, this);
  }

  public SWIGTYPE_p_bool cast() {
    long cPtr = OsmAndCoreJNI.BoolPtr_cast(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_bool(cPtr, false);
  }

  public static BoolPtr frompointer(SWIGTYPE_p_bool t) {
    long cPtr = OsmAndCoreJNI.BoolPtr_frompointer(SWIGTYPE_p_bool.getCPtr(t));
    return (cPtr == 0) ? null : new BoolPtr(cPtr, false);
  }

}
