/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.osmand.core.jni;

public class ColorRGB {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ColorRGB(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ColorRGB obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OsmAndCoreJNI.delete_ColorRGB(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ColorRGB() {
    this(OsmAndCoreJNI.new_ColorRGB__SWIG_0(), true);
  }

  public ColorRGB(short r_, short g_, short b_) {
    this(OsmAndCoreJNI.new_ColorRGB__SWIG_1(r_, g_, b_), true);
  }

  public ColorRGB(ColorARGB other) {
    this(OsmAndCoreJNI.new_ColorRGB__SWIG_2(ColorARGB.getCPtr(other), other), true);
  }

  public ColorRGB(FColorRGB other) {
    this(OsmAndCoreJNI.new_ColorRGB__SWIG_3(FColorRGB.getCPtr(other), other), true);
  }

  public void setR(short value) {
    OsmAndCoreJNI.ColorRGB_r_set(swigCPtr, this, value);
  }

  public short getR() {
    return OsmAndCoreJNI.ColorRGB_r_get(swigCPtr, this);
  }

  public void setG(short value) {
    OsmAndCoreJNI.ColorRGB_g_set(swigCPtr, this, value);
  }

  public short getG() {
    return OsmAndCoreJNI.ColorRGB_g_get(swigCPtr, this);
  }

  public void setB(short value) {
    OsmAndCoreJNI.ColorRGB_b_set(swigCPtr, this, value);
  }

  public short getB() {
    return OsmAndCoreJNI.ColorRGB_b_get(swigCPtr, this);
  }

  public ColorARGB withAlpha(short alpha) {
    return new ColorARGB(OsmAndCoreJNI.ColorRGB_withAlpha(swigCPtr, this, alpha), true);
  }

}
