/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.osmand.core.jni;

public class DefaultLogSink extends ILogSink {
  private long swigCPtr;
  private boolean swigCMemOwnDerived;

  protected DefaultLogSink(long cPtr, boolean cMemoryOwn) {
    super(OsmAndCoreJNI.DefaultLogSink_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DefaultLogSink obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        OsmAndCoreJNI.delete_DefaultLogSink(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public DefaultLogSink() {
    this(OsmAndCoreJNI.new_DefaultLogSink(), true);
  }

  public void flush() {
    OsmAndCoreJNI.DefaultLogSink_flush(swigCPtr, this);
  }

}
