/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.osmand.core.jni;

public class IMapStylesPresetsCollection {
  private long swigCPtr;
  private boolean swigCMemOwn;

  protected IMapStylesPresetsCollection(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IMapStylesPresetsCollection obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OsmAndCoreJNI.delete_IMapStylesPresetsCollection(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SWIGTYPE_p_QListT_std__shared_ptrT_OsmAnd__MapStylePreset_const_t_t getCollection() {
    return new SWIGTYPE_p_QListT_std__shared_ptrT_OsmAnd__MapStylePreset_const_t_t(OsmAndCoreJNI.IMapStylesPresetsCollection_getCollection(swigCPtr, this), true);
  }

  public SWIGTYPE_p_QListT_std__shared_ptrT_OsmAnd__MapStylePreset_const_t_t getCollectionFor(String styleName) {
    return new SWIGTYPE_p_QListT_std__shared_ptrT_OsmAnd__MapStylePreset_const_t_t(OsmAndCoreJNI.IMapStylesPresetsCollection_getCollectionFor(swigCPtr, this, styleName), true);
  }

  public MapStylePreset getPreset(String styleName, String presetName) {
    long cPtr = OsmAndCoreJNI.IMapStylesPresetsCollection_getPreset(swigCPtr, this, styleName, presetName);
    return (cPtr == 0) ? null : new MapStylePreset(cPtr, true);
  }

}
