/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.osmand.core.jni;

public class MapData {
  private long swigCPtr;
  private boolean swigCMemOwn;

  protected MapData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MapData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OsmAndCoreJNI.delete_MapData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public IMapDataProvider.DataType getDataType() {
    return IMapDataProvider.DataType.swigToEnum(OsmAndCoreJNI.MapData_dataType_get(swigCPtr, this));
  }

  public boolean getConsumableContentReleased() {
    return OsmAndCoreJNI.MapData_consumableContentReleased_get(swigCPtr, this);
  }

  public void releaseConsumableContent() {
    OsmAndCoreJNI.MapData_releaseConsumableContent(swigCPtr, this);
  }

}
