/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.osmand.core.jni;

public enum MapRendererStateChange {
  RasterLayers_Providers(OsmAndCoreJNI.MapRendererStateChange_RasterLayers_Providers_get()),
  RasterLayers_Opacity,
  ElevationData_Provider,
  ElevationData_ScaleFactor,
  Symbols_Providers,
  WindowSize,
  Viewport,
  FieldOfView,
  SkyColor,
  FogParameters,
  Azimuth,
  ElevationAngle,
  Target,
  Zoom;

  public final int swigValue() {
    return swigValue;
  }

  public static MapRendererStateChange swigToEnum(int swigValue) {
    MapRendererStateChange[] swigValues = MapRendererStateChange.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (MapRendererStateChange swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + MapRendererStateChange.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private MapRendererStateChange() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private MapRendererStateChange(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private MapRendererStateChange(MapRendererStateChange swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

