/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.osmand.core.jni;

public class MapStyleValueDefinition {
  private long swigCPtr;
  private boolean swigCMemOwn;

  protected MapStyleValueDefinition(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MapStyleValueDefinition obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OsmAndCoreJNI.delete_MapStyleValueDefinition(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public MapStyleValueDefinition(MapStyleValueDefinition.Class valueClass, MapStyleValueDataType dataType, String name, boolean isComplex) {
    this(OsmAndCoreJNI.new_MapStyleValueDefinition(valueClass.swigValue(), dataType.swigValue(), name, isComplex), true);
  }

  public MapStyleValueDefinition.Class getValueClass() {
    return MapStyleValueDefinition.Class.swigToEnum(OsmAndCoreJNI.MapStyleValueDefinition_valueClass_get(swigCPtr, this));
  }

  public MapStyleValueDataType getDataType() {
    return MapStyleValueDataType.swigToEnum(OsmAndCoreJNI.MapStyleValueDefinition_dataType_get(swigCPtr, this));
  }

  public String getName() {
    return OsmAndCoreJNI.MapStyleValueDefinition_name_get(swigCPtr, this);
  }

  public boolean getIsComplex() {
    return OsmAndCoreJNI.MapStyleValueDefinition_isComplex_get(swigCPtr, this);
  }

  public enum Class {
    Input,
    Output;

    public final int swigValue() {
      return swigValue;
    }

    public static Class swigToEnum(int swigValue) {
      Class[] swigValues = Class.class.getEnumConstants();
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (Class swigEnum : swigValues)
        if (swigEnum.swigValue == swigValue)
          return swigEnum;
      throw new IllegalArgumentException("No enum " + Class.class + " with value " + swigValue);
    }

    @SuppressWarnings("unused")
    private Class() {
      this.swigValue = SwigNext.next++;
    }

    @SuppressWarnings("unused")
    private Class(int swigValue) {
      this.swigValue = swigValue;
      SwigNext.next = swigValue+1;
    }

    @SuppressWarnings("unused")
    private Class(Class swigEnum) {
      this.swigValue = swigEnum.swigValue;
      SwigNext.next = this.swigValue+1;
    }

    private final int swigValue;

    private static class SwigNext {
      private static int next = 0;
    }
  }

}
