/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.osmand.core.jni;

public class MapStyleValueDefinition {
  private long swigCPtr;
  private boolean swigCMemOwn;

  protected MapStyleValueDefinition(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MapStyleValueDefinition obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OsmAndCoreJNI.delete_MapStyleValueDefinition(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int getId() {
    return OsmAndCoreJNI.MapStyleValueDefinition_id_get(swigCPtr, this);
  }

  public MapStyleValueClass getValueClass() {
    return MapStyleValueClass.swigToEnum(OsmAndCoreJNI.MapStyleValueDefinition_valueClass_get(swigCPtr, this));
  }

  public MapStyleValueDataType getDataType() {
    return MapStyleValueDataType.swigToEnum(OsmAndCoreJNI.MapStyleValueDefinition_dataType_get(swigCPtr, this));
  }

  public String getName() {
    return OsmAndCoreJNI.MapStyleValueDefinition_name_get(swigCPtr, this);
  }

  public boolean getIsComplex() {
    return OsmAndCoreJNI.MapStyleValueDefinition_isComplex_get(swigCPtr, this);
  }

}
