package net.osmand.aidl;

public interface OsmandAidlConstants {

	int COPY_FILE_PARAMS_ERROR = -1001;
	int COPY_FILE_PART_SIZE_LIMIT_ERROR = -1002;
	int COPY_FILE_WRITE_LOCK_ERROR = -1003;
	int COPY_FILE_IO_ERROR = -1004;
	int COPY_FILE_UNSUPPORTED_FILE_TYPE_ERROR = -1005;
	int COPY_FILE_START_FLAG = 1001;
	int COPY_FILE_FINISH_FLAG = 1002;
	int COPY_FILE_IN_PROGRESS_FLAG = 1000;
	long COPY_FILE_VALID_PAUSE = 10000;
	int COPY_FILE_OK_RESPONSE = 0;

}
