/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.osmand.core.jni;

public class AreaI {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected AreaI(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AreaI obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OsmAndCoreJNI.delete_AreaI(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public AreaI() {
    this(OsmAndCoreJNI.new_AreaI__SWIG_0(), true);
  }

  public AreaI(int t, int l, int b, int r) {
    this(OsmAndCoreJNI.new_AreaI__SWIG_1(t, l, b, r), true);
  }

  public AreaI(PointI tl, PointI br) {
    this(OsmAndCoreJNI.new_AreaI__SWIG_2(PointI.getCPtr(tl), tl, PointI.getCPtr(br), br), true);
  }

  public AreaI(AreaI that) {
    this(OsmAndCoreJNI.new_AreaI__SWIG_3(AreaI.getCPtr(that), that), true);
  }

  public void setTopLeft(PointI value) {
    OsmAndCoreJNI.AreaI_topLeft_set(swigCPtr, this, PointI.getCPtr(value), value);
  }

  public PointI getTopLeft() {
    long cPtr = OsmAndCoreJNI.AreaI_topLeft_get(swigCPtr, this);
    return (cPtr == 0) ? null : new PointI(cPtr, false);
  }

  public void setBottomRight(PointI value) {
    OsmAndCoreJNI.AreaI_bottomRight_set(swigCPtr, this, PointI.getCPtr(value), value);
  }

  public PointI getBottomRight() {
    long cPtr = OsmAndCoreJNI.AreaI_bottomRight_get(swigCPtr, this);
    return (cPtr == 0) ? null : new PointI(cPtr, false);
  }

  public boolean contains(int x, int y) {
    return OsmAndCoreJNI.AreaI_contains__SWIG_0(swigCPtr, this, x, y);
  }

  public boolean contains(PointI p) {
    return OsmAndCoreJNI.AreaI_contains__SWIG_1(swigCPtr, this, PointI.getCPtr(p), p);
  }

  public boolean contains(int t, int l, int b, int r) {
    return OsmAndCoreJNI.AreaI_contains__SWIG_2(swigCPtr, this, t, l, b, r);
  }

  public boolean contains(AreaI that) {
    return OsmAndCoreJNI.AreaI_contains__SWIG_3(swigCPtr, this, AreaI.getCPtr(that), that);
  }

  public boolean intersects(int t, int l, int b, int r) {
    return OsmAndCoreJNI.AreaI_intersects__SWIG_0(swigCPtr, this, t, l, b, r);
  }

  public boolean intersects(AreaI that) {
    return OsmAndCoreJNI.AreaI_intersects__SWIG_1(swigCPtr, this, AreaI.getCPtr(that), that);
  }

  public boolean contains(OOBBI that) {
    return OsmAndCoreJNI.AreaI_contains__SWIG_4(swigCPtr, this, OOBBI.getCPtr(that), that);
  }

  public boolean intersects(OOBBI that) {
    return OsmAndCoreJNI.AreaI_intersects__SWIG_2(swigCPtr, this, OOBBI.getCPtr(that), that);
  }

  public int width() {
    return OsmAndCoreJNI.AreaI_width(swigCPtr, this);
  }

  public int height() {
    return OsmAndCoreJNI.AreaI_height(swigCPtr, this);
  }

  public PointI center() {
    return new PointI(OsmAndCoreJNI.AreaI_center(swigCPtr, this), true);
  }

  public PointI topRight() {
    return new PointI(OsmAndCoreJNI.AreaI_topRight(swigCPtr, this), true);
  }

  public PointI bottomLeft() {
    return new PointI(OsmAndCoreJNI.AreaI_bottomLeft(swigCPtr, this), true);
  }

  public AreaI getQuadrant(Quadrant quadrant) {
    return new AreaI(OsmAndCoreJNI.AreaI_getQuadrant(swigCPtr, this, quadrant.swigValue()), true);
  }

  public AreaI getEnlargedToInclude(PointI p) {
    return new AreaI(OsmAndCoreJNI.AreaI_getEnlargedToInclude(swigCPtr, this, PointI.getCPtr(p), p), true);
  }

  public AreaI getEnlargedBy(PointI delta) {
    return new AreaI(OsmAndCoreJNI.AreaI_getEnlargedBy__SWIG_0(swigCPtr, this, PointI.getCPtr(delta), delta), true);
  }

  public AreaI getEnlargedBy(int dt, int dl, int db, int dr) {
    return new AreaI(OsmAndCoreJNI.AreaI_getEnlargedBy__SWIG_1(swigCPtr, this, dt, dl, db, dr), true);
  }

  public static AreaI largest() {
    return new AreaI(OsmAndCoreJNI.AreaI_largest(), true);
  }

  public static AreaI fromCenterAndSize(int cx, int cy, int width, int height) {
    return new AreaI(OsmAndCoreJNI.AreaI_fromCenterAndSize(cx, cy, width, height), true);
  }

}
