/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.osmand.core.jni;

public class ElevationDataTile extends MapTiledData {
  private long swigCPtr;
  private boolean swigCMemOwnDerived;

  protected ElevationDataTile(long cPtr, boolean cMemoryOwn) {
    super(OsmAndCoreJNI.ElevationDataTile_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ElevationDataTile obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        OsmAndCoreJNI.delete_ElevationDataTile(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ElevationDataTile(SWIGTYPE_p_float data, long rowLength, long size, TileId tileId, ZoomLevel zoom) {
    this(OsmAndCoreJNI.new_ElevationDataTile(SWIGTYPE_p_float.getCPtr(data), rowLength, size, TileId.getCPtr(tileId), tileId, zoom.swigValue()), true);
  }

  public void setData(SWIGTYPE_p_float value) {
    OsmAndCoreJNI.ElevationDataTile_data_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getData() {
    long cPtr = OsmAndCoreJNI.ElevationDataTile_data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public void setRowLength(long value) {
    OsmAndCoreJNI.ElevationDataTile_rowLength_set(swigCPtr, this, value);
  }

  public long getRowLength() {
    return OsmAndCoreJNI.ElevationDataTile_rowLength_get(swigCPtr, this);
  }

  public void setSize(long value) {
    OsmAndCoreJNI.ElevationDataTile_size_set(swigCPtr, this, value);
  }

  public long getSize() {
    return OsmAndCoreJNI.ElevationDataTile_size_get(swigCPtr, this);
  }

  public void releaseConsumableContent() {
    OsmAndCoreJNI.ElevationDataTile_releaseConsumableContent(swigCPtr, this);
  }

}
