/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.osmand.core.jni;

public class FColorRGB {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected FColorRGB(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FColorRGB obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OsmAndCoreJNI.delete_FColorRGB(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public FColorRGB() {
    this(OsmAndCoreJNI.new_FColorRGB__SWIG_0(), true);
  }

  public FColorRGB(float r_, float g_, float b_) {
    this(OsmAndCoreJNI.new_FColorRGB__SWIG_1(r_, g_, b_), true);
  }

  public FColorRGB(FColorARGB other) {
    this(OsmAndCoreJNI.new_FColorRGB__SWIG_2(FColorARGB.getCPtr(other), other), true);
  }

  public void setR(float value) {
    OsmAndCoreJNI.FColorRGB_r_set(swigCPtr, this, value);
  }

  public float getR() {
    return OsmAndCoreJNI.FColorRGB_r_get(swigCPtr, this);
  }

  public void setG(float value) {
    OsmAndCoreJNI.FColorRGB_g_set(swigCPtr, this, value);
  }

  public float getG() {
    return OsmAndCoreJNI.FColorRGB_g_get(swigCPtr, this);
  }

  public void setB(float value) {
    OsmAndCoreJNI.FColorRGB_b_set(swigCPtr, this, value);
  }

  public float getB() {
    return OsmAndCoreJNI.FColorRGB_b_get(swigCPtr, this);
  }

  public FColorARGB withAlpha(float alpha) {
    return new FColorARGB(OsmAndCoreJNI.FColorRGB_withAlpha(swigCPtr, this, alpha), true);
  }

}
