/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.osmand.core.jni;

public class IMapStylesCollection {
  private long swigCPtr;
  private boolean swigCMemOwn;

  protected IMapStylesCollection(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IMapStylesCollection obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OsmAndCoreJNI.delete_IMapStylesCollection(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SWIGTYPE_p_QListT_std__shared_ptrT_OsmAnd__UnresolvedMapStyle_const_t_t getCollection() {
    return new SWIGTYPE_p_QListT_std__shared_ptrT_OsmAnd__UnresolvedMapStyle_const_t_t(OsmAndCoreJNI.IMapStylesCollection_getCollection(swigCPtr, this), true);
  }

  public SWIGTYPE_p_std__shared_ptrT_OsmAnd__UnresolvedMapStyle_const_t getStyleByName(String name) {
    return new SWIGTYPE_p_std__shared_ptrT_OsmAnd__UnresolvedMapStyle_const_t(OsmAndCoreJNI.IMapStylesCollection_getStyleByName(swigCPtr, this, name), true);
  }

  public ResolvedMapStyle getResolvedStyleByName(String name) {
    long cPtr = OsmAndCoreJNI.IMapStylesCollection_getResolvedStyleByName(swigCPtr, this, name);
    return (cPtr == 0) ? null : new ResolvedMapStyle(cPtr, true);
  }

}
