/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.osmand.core.jni;

public class IMapRasterBitmapTileProvider extends IMapTiledDataProvider {
  private long swigCPtr;
  private boolean swigCMemOwnDerived;

  protected IMapRasterBitmapTileProvider(long cPtr, boolean cMemoryOwn) {
    super(OsmAndCoreJNI.IMapRasterBitmapTileProvider_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IMapRasterBitmapTileProvider obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        OsmAndCoreJNI.delete_IMapRasterBitmapTileProvider(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public long getTileSize() {
    return OsmAndCoreJNI.IMapRasterBitmapTileProvider_getTileSize(swigCPtr, this);
  }

  public float getTileDensityFactor() {
    return OsmAndCoreJNI.IMapRasterBitmapTileProvider_getTileDensityFactor(swigCPtr, this);
  }

}
