/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.osmand.core.jni;

public enum MapStyleValueDataType {
  Boolean,
  Integer,
  Float,
  String,
  Color;

  public final int swigValue() {
    return swigValue;
  }

  public static MapStyleValueDataType swigToEnum(int swigValue) {
    MapStyleValueDataType[] swigValues = MapStyleValueDataType.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (MapStyleValueDataType swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + MapStyleValueDataType.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private MapStyleValueDataType() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private MapStyleValueDataType(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private MapStyleValueDataType(MapStyleValueDataType swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

