/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.osmand.core.jni;

public class PointF {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected PointF(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PointF obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OsmAndCoreJNI.delete_PointF(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setX(float value) {
    OsmAndCoreJNI.PointF_x_set(swigCPtr, this, value);
  }

  public float getX() {
    return OsmAndCoreJNI.PointF_x_get(swigCPtr, this);
  }

  public void setY(float value) {
    OsmAndCoreJNI.PointF_y_set(swigCPtr, this, value);
  }

  public float getY() {
    return OsmAndCoreJNI.PointF_y_get(swigCPtr, this);
  }

  public PointF() {
    this(OsmAndCoreJNI.new_PointF__SWIG_0(), true);
  }

  public PointF(PointF that) {
    this(OsmAndCoreJNI.new_PointF__SWIG_1(PointF.getCPtr(that), that), true);
  }

  public PointF(float x, float y) {
    this(OsmAndCoreJNI.new_PointF__SWIG_2(x, y), true);
  }

}
