/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.osmand.core.jni;

public class SWIGTYPE_p_OsmAnd__BitmaskT_OsmAnd__MapRendererStateChange_unsigned_int_t__BitmaskT {
  private long swigCPtr;

  protected SWIGTYPE_p_OsmAnd__BitmaskT_OsmAnd__MapRendererStateChange_unsigned_int_t__BitmaskT(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_OsmAnd__BitmaskT_OsmAnd__MapRendererStateChange_unsigned_int_t__BitmaskT() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_OsmAnd__BitmaskT_OsmAnd__MapRendererStateChange_unsigned_int_t__BitmaskT obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

